FROM golang:1.13

MAINTAINER Victor Nwaokocha

WORKDIR /test

ARG PORT
ARG POSTGRES_USER
ARG POSTGRES_ADDRESS
ARG POSTGRES_PASSWORD
ARG POSTGRES_DATABASE
ARG POSTGRES_USER
ARG CLIENT_HOST
ARG BASIC_AUTH_USER
ARG BASIC_AUTH_PASS

COPY . /test

ENV PORT $PORT
ENV ENV $ENV
ENV POSTGRES_ADDRESS $POSTGRES_ADDRESS
ENV POSTGRES_USER $POSTGRES_USER
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD
ENV POSTGRES_DATABASE $POSTGRES_DATABASE
ENV CLIENT_HOST $CLIENT_HOST
ENV BASIC_AUTH_USER $BASIC_AUTH_USER
ENV BASIC_AUTH_PASS $BASIC_AUTH_PASS

ENV GO111MODULE=on \
    CGO_ENABLED=0 \
    GOOS=linux \
    CGO_ENABLED=1 \
    GOARCH=amd64

RUN go build scheduler0.go
RUN go clean -testcache

RUN go test ./server/managers/execution
RUN go test ./server/managers/job
RUN go test ./server/managers/project
RUN go test ./server/managers/credential

RUN go test ./server/http_server/controllers/execution
RUN go test ./server/http_server/controllers/credential
RUN go test ./server/http_server/controllers/job -cover
RUN go test ./server/http_server/controllers/project

RUN go test ./server/http_server/middlewares/auth/ios
RUN	go test ./server/http_server/middlewares/auth/android
RUN	go test ./server/http_server/middlewares/auth/server
RUN	go test ./server/http_server/middlewares/auth/web