// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package fsm

import (
	"scheduler0/pkg/constants"
	"scheduler0/pkg/db"
	"scheduler0/pkg/models"
	"scheduler0/pkg/utils"

	"github.com/hashicorp/go-hclog"
	"github.com/hashicorp/raft"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduler0RaftActions creates a new instance of MockScheduler0RaftActions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler0RaftActions(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler0RaftActions {
	mock := &MockScheduler0RaftActions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler0RaftActions is an autogenerated mock type for the Scheduler0RaftActions type
type MockScheduler0RaftActions struct {
	mock.Mock
}

type MockScheduler0RaftActions_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler0RaftActions) EXPECT() *MockScheduler0RaftActions_Expecter {
	return &MockScheduler0RaftActions_Expecter{mock: &_m.Mock}
}

// ApplyRaftLog provides a mock function for the type MockScheduler0RaftActions
func (_mock *MockScheduler0RaftActions) ApplyRaftLog(logger hclog.Logger, l *raft.Log, db1 db.DataStore, ignorePostProcessChannel bool) interface{} {
	ret := _mock.Called(logger, l, db1, ignorePostProcessChannel)

	if len(ret) == 0 {
		panic("no return value specified for ApplyRaftLog")
	}

	var r0 interface{}
	if returnFunc, ok := ret.Get(0).(func(hclog.Logger, *raft.Log, db.DataStore, bool) interface{}); ok {
		r0 = returnFunc(logger, l, db1, ignorePostProcessChannel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	return r0
}

// MockScheduler0RaftActions_ApplyRaftLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyRaftLog'
type MockScheduler0RaftActions_ApplyRaftLog_Call struct {
	*mock.Call
}

// ApplyRaftLog is a helper method to define mock.On call
//   - logger hclog.Logger
//   - l *raft.Log
//   - db1 db.DataStore
//   - ignorePostProcessChannel bool
func (_e *MockScheduler0RaftActions_Expecter) ApplyRaftLog(logger interface{}, l interface{}, db1 interface{}, ignorePostProcessChannel interface{}) *MockScheduler0RaftActions_ApplyRaftLog_Call {
	return &MockScheduler0RaftActions_ApplyRaftLog_Call{Call: _e.mock.On("ApplyRaftLog", logger, l, db1, ignorePostProcessChannel)}
}

func (_c *MockScheduler0RaftActions_ApplyRaftLog_Call) Run(run func(logger hclog.Logger, l *raft.Log, db1 db.DataStore, ignorePostProcessChannel bool)) *MockScheduler0RaftActions_ApplyRaftLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 hclog.Logger
		if args[0] != nil {
			arg0 = args[0].(hclog.Logger)
		}
		var arg1 *raft.Log
		if args[1] != nil {
			arg1 = args[1].(*raft.Log)
		}
		var arg2 db.DataStore
		if args[2] != nil {
			arg2 = args[2].(db.DataStore)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockScheduler0RaftActions_ApplyRaftLog_Call) Return(ifaceVal interface{}) *MockScheduler0RaftActions_ApplyRaftLog_Call {
	_c.Call.Return(ifaceVal)
	return _c
}

func (_c *MockScheduler0RaftActions_ApplyRaftLog_Call) RunAndReturn(run func(logger hclog.Logger, l *raft.Log, db1 db.DataStore, ignorePostProcessChannel bool) interface{}) *MockScheduler0RaftActions_ApplyRaftLog_Call {
	_c.Call.Return(run)
	return _c
}

// WriteCommandToRaftLog provides a mock function for the type MockScheduler0RaftActions
func (_mock *MockScheduler0RaftActions) WriteCommandToRaftLog(rft *raft.Raft, commandType constants.Command, sqlString string, params []interface{}, nodeIds []uint64, action constants.CommandAction) (*models.FSMResponse, *utils.GenericError) {
	ret := _mock.Called(rft, commandType, sqlString, params, nodeIds, action)

	if len(ret) == 0 {
		panic("no return value specified for WriteCommandToRaftLog")
	}

	var r0 *models.FSMResponse
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(*raft.Raft, constants.Command, string, []interface{}, []uint64, constants.CommandAction) (*models.FSMResponse, *utils.GenericError)); ok {
		return returnFunc(rft, commandType, sqlString, params, nodeIds, action)
	}
	if returnFunc, ok := ret.Get(0).(func(*raft.Raft, constants.Command, string, []interface{}, []uint64, constants.CommandAction) *models.FSMResponse); ok {
		r0 = returnFunc(rft, commandType, sqlString, params, nodeIds, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.FSMResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*raft.Raft, constants.Command, string, []interface{}, []uint64, constants.CommandAction) *utils.GenericError); ok {
		r1 = returnFunc(rft, commandType, sqlString, params, nodeIds, action)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockScheduler0RaftActions_WriteCommandToRaftLog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteCommandToRaftLog'
type MockScheduler0RaftActions_WriteCommandToRaftLog_Call struct {
	*mock.Call
}

// WriteCommandToRaftLog is a helper method to define mock.On call
//   - rft *raft.Raft
//   - commandType constants.Command
//   - sqlString string
//   - params []interface{}
//   - nodeIds []uint64
//   - action constants.CommandAction
func (_e *MockScheduler0RaftActions_Expecter) WriteCommandToRaftLog(rft interface{}, commandType interface{}, sqlString interface{}, params interface{}, nodeIds interface{}, action interface{}) *MockScheduler0RaftActions_WriteCommandToRaftLog_Call {
	return &MockScheduler0RaftActions_WriteCommandToRaftLog_Call{Call: _e.mock.On("WriteCommandToRaftLog", rft, commandType, sqlString, params, nodeIds, action)}
}

func (_c *MockScheduler0RaftActions_WriteCommandToRaftLog_Call) Run(run func(rft *raft.Raft, commandType constants.Command, sqlString string, params []interface{}, nodeIds []uint64, action constants.CommandAction)) *MockScheduler0RaftActions_WriteCommandToRaftLog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *raft.Raft
		if args[0] != nil {
			arg0 = args[0].(*raft.Raft)
		}
		var arg1 constants.Command
		if args[1] != nil {
			arg1 = args[1].(constants.Command)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []interface{}
		if args[3] != nil {
			arg3 = args[3].([]interface{})
		}
		var arg4 []uint64
		if args[4] != nil {
			arg4 = args[4].([]uint64)
		}
		var arg5 constants.CommandAction
		if args[5] != nil {
			arg5 = args[5].(constants.CommandAction)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockScheduler0RaftActions_WriteCommandToRaftLog_Call) Return(fSMResponse *models.FSMResponse, genericError *utils.GenericError) *MockScheduler0RaftActions_WriteCommandToRaftLog_Call {
	_c.Call.Return(fSMResponse, genericError)
	return _c
}

func (_c *MockScheduler0RaftActions_WriteCommandToRaftLog_Call) RunAndReturn(run func(rft *raft.Raft, commandType constants.Command, sqlString string, params []interface{}, nodeIds []uint64, action constants.CommandAction) (*models.FSMResponse, *utils.GenericError)) *MockScheduler0RaftActions_WriteCommandToRaftLog_Call {
	_c.Call.Return(run)
	return _c
}
