// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"context"
	"scheduler0/pkg/config"
	"scheduler0/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockNodeClient creates a new instance of MockNodeClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeClient {
	mock := &MockNodeClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeClient is an autogenerated mock type for the NodeClient type
type MockNodeClient struct {
	mock.Mock
}

type MockNodeClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeClient) EXPECT() *MockNodeClient_Expecter {
	return &MockNodeClient_Expecter{mock: &_m.Mock}
}

// ConnectNode provides a mock function for the type MockNodeClient
func (_mock *MockNodeClient) ConnectNode(replica config.RaftNode) (*Status, error) {
	ret := _mock.Called(replica)

	if len(ret) == 0 {
		panic("no return value specified for ConnectNode")
	}

	var r0 *Status
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(config.RaftNode) (*Status, error)); ok {
		return returnFunc(replica)
	}
	if returnFunc, ok := ret.Get(0).(func(config.RaftNode) *Status); ok {
		r0 = returnFunc(replica)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Status)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(config.RaftNode) error); ok {
		r1 = returnFunc(replica)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNodeClient_ConnectNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectNode'
type MockNodeClient_ConnectNode_Call struct {
	*mock.Call
}

// ConnectNode is a helper method to define mock.On call
//   - replica config.RaftNode
func (_e *MockNodeClient_Expecter) ConnectNode(replica interface{}) *MockNodeClient_ConnectNode_Call {
	return &MockNodeClient_ConnectNode_Call{Call: _e.mock.On("ConnectNode", replica)}
}

func (_c *MockNodeClient_ConnectNode_Call) Run(run func(replica config.RaftNode)) *MockNodeClient_ConnectNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.RaftNode
		if args[0] != nil {
			arg0 = args[0].(config.RaftNode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeClient_ConnectNode_Call) Return(status *Status, err error) *MockNodeClient_ConnectNode_Call {
	_c.Call.Return(status, err)
	return _c
}

func (_c *MockNodeClient_ConnectNode_Call) RunAndReturn(run func(replica config.RaftNode) (*Status, error)) *MockNodeClient_ConnectNode_Call {
	_c.Call.Return(run)
	return _c
}

// FetchUncommittedLogsFromPeersPhase1 provides a mock function for the type MockNodeClient
func (_mock *MockNodeClient) FetchUncommittedLogsFromPeersPhase1(ctx context.Context, node *nodeService, peerFanIns []models.PeerFanIn) {
	_mock.Called(ctx, node, peerFanIns)
	return
}

// MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUncommittedLogsFromPeersPhase1'
type MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call struct {
	*mock.Call
}

// FetchUncommittedLogsFromPeersPhase1 is a helper method to define mock.On call
//   - ctx context.Context
//   - node *nodeService
//   - peerFanIns []models.PeerFanIn
func (_e *MockNodeClient_Expecter) FetchUncommittedLogsFromPeersPhase1(ctx interface{}, node interface{}, peerFanIns interface{}) *MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call {
	return &MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call{Call: _e.mock.On("FetchUncommittedLogsFromPeersPhase1", ctx, node, peerFanIns)}
}

func (_c *MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call) Run(run func(ctx context.Context, node *nodeService, peerFanIns []models.PeerFanIn)) *MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *nodeService
		if args[1] != nil {
			arg1 = args[1].(*nodeService)
		}
		var arg2 []models.PeerFanIn
		if args[2] != nil {
			arg2 = args[2].([]models.PeerFanIn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call) Return() *MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call) RunAndReturn(run func(ctx context.Context, node *nodeService, peerFanIns []models.PeerFanIn)) *MockNodeClient_FetchUncommittedLogsFromPeersPhase1_Call {
	_c.Run(run)
	return _c
}

// FetchUncommittedLogsFromPeersPhase2 provides a mock function for the type MockNodeClient
func (_mock *MockNodeClient) FetchUncommittedLogsFromPeersPhase2(ctx context.Context, node *nodeService, peerFanIns []models.PeerFanIn) {
	_mock.Called(ctx, node, peerFanIns)
	return
}

// MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchUncommittedLogsFromPeersPhase2'
type MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call struct {
	*mock.Call
}

// FetchUncommittedLogsFromPeersPhase2 is a helper method to define mock.On call
//   - ctx context.Context
//   - node *nodeService
//   - peerFanIns []models.PeerFanIn
func (_e *MockNodeClient_Expecter) FetchUncommittedLogsFromPeersPhase2(ctx interface{}, node interface{}, peerFanIns interface{}) *MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call {
	return &MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call{Call: _e.mock.On("FetchUncommittedLogsFromPeersPhase2", ctx, node, peerFanIns)}
}

func (_c *MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call) Run(run func(ctx context.Context, node *nodeService, peerFanIns []models.PeerFanIn)) *MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *nodeService
		if args[1] != nil {
			arg1 = args[1].(*nodeService)
		}
		var arg2 []models.PeerFanIn
		if args[2] != nil {
			arg2 = args[2].([]models.PeerFanIn)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call) Return() *MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call) RunAndReturn(run func(ctx context.Context, node *nodeService, peerFanIns []models.PeerFanIn)) *MockNodeClient_FetchUncommittedLogsFromPeersPhase2_Call {
	_c.Run(run)
	return _c
}

// StartJobs provides a mock function for the type MockNodeClient
func (_mock *MockNodeClient) StartJobs(ctx context.Context, node *nodeService, peer config.RaftNode) error {
	ret := _mock.Called(ctx, node, peer)

	if len(ret) == 0 {
		panic("no return value specified for StartJobs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *nodeService, config.RaftNode) error); ok {
		r0 = returnFunc(ctx, node, peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeClient_StartJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartJobs'
type MockNodeClient_StartJobs_Call struct {
	*mock.Call
}

// StartJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - node *nodeService
//   - peer config.RaftNode
func (_e *MockNodeClient_Expecter) StartJobs(ctx interface{}, node interface{}, peer interface{}) *MockNodeClient_StartJobs_Call {
	return &MockNodeClient_StartJobs_Call{Call: _e.mock.On("StartJobs", ctx, node, peer)}
}

func (_c *MockNodeClient_StartJobs_Call) Run(run func(ctx context.Context, node *nodeService, peer config.RaftNode)) *MockNodeClient_StartJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *nodeService
		if args[1] != nil {
			arg1 = args[1].(*nodeService)
		}
		var arg2 config.RaftNode
		if args[2] != nil {
			arg2 = args[2].(config.RaftNode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNodeClient_StartJobs_Call) Return(err error) *MockNodeClient_StartJobs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeClient_StartJobs_Call) RunAndReturn(run func(ctx context.Context, node *nodeService, peer config.RaftNode) error) *MockNodeClient_StartJobs_Call {
	_c.Call.Return(run)
	return _c
}

// StopJobs provides a mock function for the type MockNodeClient
func (_mock *MockNodeClient) StopJobs(ctx context.Context, node *nodeService, peer config.RaftNode) error {
	ret := _mock.Called(ctx, node, peer)

	if len(ret) == 0 {
		panic("no return value specified for StopJobs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *nodeService, config.RaftNode) error); ok {
		r0 = returnFunc(ctx, node, peer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeClient_StopJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopJobs'
type MockNodeClient_StopJobs_Call struct {
	*mock.Call
}

// StopJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - node *nodeService
//   - peer config.RaftNode
func (_e *MockNodeClient_Expecter) StopJobs(ctx interface{}, node interface{}, peer interface{}) *MockNodeClient_StopJobs_Call {
	return &MockNodeClient_StopJobs_Call{Call: _e.mock.On("StopJobs", ctx, node, peer)}
}

func (_c *MockNodeClient_StopJobs_Call) Run(run func(ctx context.Context, node *nodeService, peer config.RaftNode)) *MockNodeClient_StopJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *nodeService
		if args[1] != nil {
			arg1 = args[1].(*nodeService)
		}
		var arg2 config.RaftNode
		if args[2] != nil {
			arg2 = args[2].(config.RaftNode)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNodeClient_StopJobs_Call) Return(err error) *MockNodeClient_StopJobs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeClient_StopJobs_Call) RunAndReturn(run func(ctx context.Context, node *nodeService, peer config.RaftNode) error) *MockNodeClient_StopJobs_Call {
	_c.Call.Return(run)
	return _c
}
