// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"context"
	"scheduler0/pkg/config"
	"scheduler0/pkg/models"
	"scheduler0/pkg/repository/job_queue"
	"scheduler0/pkg/service/executor"

	"github.com/hashicorp/raft"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNodeService creates a new instance of MockNodeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNodeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNodeService {
	mock := &MockNodeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNodeService is an autogenerated mock type for the NodeService type
type MockNodeService struct {
	mock.Mock
}

type MockNodeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNodeService) EXPECT() *MockNodeService_Expecter {
	return &MockNodeService_Expecter{mock: &_m.Mock}
}

// AddNode provides a mock function for the type MockNodeService
func (_mock *MockNodeService) AddNode(ctx context.Context, nodeId uint64, nodeAddress string, clientAddress string) error {
	ret := _mock.Called(ctx, nodeId, nodeAddress, clientAddress)

	if len(ret) == 0 {
		panic("no return value specified for AddNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64, string, string) error); ok {
		r0 = returnFunc(ctx, nodeId, nodeAddress, clientAddress)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_AddNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddNode'
type MockNodeService_AddNode_Call struct {
	*mock.Call
}

// AddNode is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeId uint64
//   - nodeAddress string
//   - clientAddress string
func (_e *MockNodeService_Expecter) AddNode(ctx interface{}, nodeId interface{}, nodeAddress interface{}, clientAddress interface{}) *MockNodeService_AddNode_Call {
	return &MockNodeService_AddNode_Call{Call: _e.mock.On("AddNode", ctx, nodeId, nodeAddress, clientAddress)}
}

func (_c *MockNodeService_AddNode_Call) Run(run func(ctx context.Context, nodeId uint64, nodeAddress string, clientAddress string)) *MockNodeService_AddNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockNodeService_AddNode_Call) Return(err error) *MockNodeService_AddNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_AddNode_Call) RunAndReturn(run func(ctx context.Context, nodeId uint64, nodeAddress string, clientAddress string) error) *MockNodeService_AddNode_Call {
	_c.Call.Return(run)
	return _c
}

// AddSelfToCluster provides a mock function for the type MockNodeService
func (_mock *MockNodeService) AddSelfToCluster(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AddSelfToCluster")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_AddSelfToCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSelfToCluster'
type MockNodeService_AddSelfToCluster_Call struct {
	*mock.Call
}

// AddSelfToCluster is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeService_Expecter) AddSelfToCluster(ctx interface{}) *MockNodeService_AddSelfToCluster_Call {
	return &MockNodeService_AddSelfToCluster_Call{Call: _e.mock.On("AddSelfToCluster", ctx)}
}

func (_c *MockNodeService_AddSelfToCluster_Call) Run(run func(ctx context.Context)) *MockNodeService_AddSelfToCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_AddSelfToCluster_Call) Return(err error) *MockNodeService_AddSelfToCluster_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_AddSelfToCluster_Call) RunAndReturn(run func(ctx context.Context) error) *MockNodeService_AddSelfToCluster_Call {
	_c.Call.Return(run)
	return _c
}

// AuthRaftConfiguration provides a mock function for the type MockNodeService
func (_mock *MockNodeService) AuthRaftConfiguration() raft.Configuration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthRaftConfiguration")
	}

	var r0 raft.Configuration
	if returnFunc, ok := ret.Get(0).(func() raft.Configuration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft.Configuration)
	}
	return r0
}

// MockNodeService_AuthRaftConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthRaftConfiguration'
type MockNodeService_AuthRaftConfiguration_Call struct {
	*mock.Call
}

// AuthRaftConfiguration is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) AuthRaftConfiguration() *MockNodeService_AuthRaftConfiguration_Call {
	return &MockNodeService_AuthRaftConfiguration_Call{Call: _e.mock.On("AuthRaftConfiguration")}
}

func (_c *MockNodeService_AuthRaftConfiguration_Call) Run(run func()) *MockNodeService_AuthRaftConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_AuthRaftConfiguration_Call) Return(configuration raft.Configuration) *MockNodeService_AuthRaftConfiguration_Call {
	_c.Call.Return(configuration)
	return _c
}

func (_c *MockNodeService_AuthRaftConfiguration_Call) RunAndReturn(run func() raft.Configuration) *MockNodeService_AuthRaftConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// AuthenticateWithPeersFromEtcd provides a mock function for the type MockNodeService
func (_mock *MockNodeService) AuthenticateWithPeersFromEtcd() map[string]Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateWithPeersFromEtcd")
	}

	var r0 map[string]Status
	if returnFunc, ok := ret.Get(0).(func() map[string]Status); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]Status)
		}
	}
	return r0
}

// MockNodeService_AuthenticateWithPeersFromEtcd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateWithPeersFromEtcd'
type MockNodeService_AuthenticateWithPeersFromEtcd_Call struct {
	*mock.Call
}

// AuthenticateWithPeersFromEtcd is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) AuthenticateWithPeersFromEtcd() *MockNodeService_AuthenticateWithPeersFromEtcd_Call {
	return &MockNodeService_AuthenticateWithPeersFromEtcd_Call{Call: _e.mock.On("AuthenticateWithPeersFromEtcd")}
}

func (_c *MockNodeService_AuthenticateWithPeersFromEtcd_Call) Run(run func()) *MockNodeService_AuthenticateWithPeersFromEtcd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_AuthenticateWithPeersFromEtcd_Call) Return(stringToStatus map[string]Status) *MockNodeService_AuthenticateWithPeersFromEtcd_Call {
	_c.Call.Return(stringToStatus)
	return _c
}

func (_c *MockNodeService_AuthenticateWithPeersFromEtcd_Call) RunAndReturn(run func() map[string]Status) *MockNodeService_AuthenticateWithPeersFromEtcd_Call {
	_c.Call.Return(run)
	return _c
}

// BackupDatabase provides a mock function for the type MockNodeService
func (_mock *MockNodeService) BackupDatabase(ctx context.Context, requestId string) error {
	ret := _mock.Called(ctx, requestId)

	if len(ret) == 0 {
		panic("no return value specified for BackupDatabase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, requestId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_BackupDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackupDatabase'
type MockNodeService_BackupDatabase_Call struct {
	*mock.Call
}

// BackupDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - requestId string
func (_e *MockNodeService_Expecter) BackupDatabase(ctx interface{}, requestId interface{}) *MockNodeService_BackupDatabase_Call {
	return &MockNodeService_BackupDatabase_Call{Call: _e.mock.On("BackupDatabase", ctx, requestId)}
}

func (_c *MockNodeService_BackupDatabase_Call) Run(run func(ctx context.Context, requestId string)) *MockNodeService_BackupDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeService_BackupDatabase_Call) Return(err error) *MockNodeService_BackupDatabase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_BackupDatabase_Call) RunAndReturn(run func(ctx context.Context, requestId string) error) *MockNodeService_BackupDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// BeginAcceptingClientRequest provides a mock function for the type MockNodeService
func (_mock *MockNodeService) BeginAcceptingClientRequest() {
	_mock.Called()
	return
}

// MockNodeService_BeginAcceptingClientRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginAcceptingClientRequest'
type MockNodeService_BeginAcceptingClientRequest_Call struct {
	*mock.Call
}

// BeginAcceptingClientRequest is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) BeginAcceptingClientRequest() *MockNodeService_BeginAcceptingClientRequest_Call {
	return &MockNodeService_BeginAcceptingClientRequest_Call{Call: _e.mock.On("BeginAcceptingClientRequest")}
}

func (_c *MockNodeService_BeginAcceptingClientRequest_Call) Run(run func()) *MockNodeService_BeginAcceptingClientRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_BeginAcceptingClientRequest_Call) Return() *MockNodeService_BeginAcceptingClientRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_BeginAcceptingClientRequest_Call) RunAndReturn(run func()) *MockNodeService_BeginAcceptingClientRequest_Call {
	_c.Run(run)
	return _c
}

// BeginAcceptingClientWriteRequest provides a mock function for the type MockNodeService
func (_mock *MockNodeService) BeginAcceptingClientWriteRequest() {
	_mock.Called()
	return
}

// MockNodeService_BeginAcceptingClientWriteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginAcceptingClientWriteRequest'
type MockNodeService_BeginAcceptingClientWriteRequest_Call struct {
	*mock.Call
}

// BeginAcceptingClientWriteRequest is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) BeginAcceptingClientWriteRequest() *MockNodeService_BeginAcceptingClientWriteRequest_Call {
	return &MockNodeService_BeginAcceptingClientWriteRequest_Call{Call: _e.mock.On("BeginAcceptingClientWriteRequest")}
}

func (_c *MockNodeService_BeginAcceptingClientWriteRequest_Call) Run(run func()) *MockNodeService_BeginAcceptingClientWriteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_BeginAcceptingClientWriteRequest_Call) Return() *MockNodeService_BeginAcceptingClientWriteRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_BeginAcceptingClientWriteRequest_Call) RunAndReturn(run func()) *MockNodeService_BeginAcceptingClientWriteRequest_Call {
	_c.Run(run)
	return _c
}

// CanAcceptClientWriteRequest provides a mock function for the type MockNodeService
func (_mock *MockNodeService) CanAcceptClientWriteRequest() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanAcceptClientWriteRequest")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNodeService_CanAcceptClientWriteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAcceptClientWriteRequest'
type MockNodeService_CanAcceptClientWriteRequest_Call struct {
	*mock.Call
}

// CanAcceptClientWriteRequest is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) CanAcceptClientWriteRequest() *MockNodeService_CanAcceptClientWriteRequest_Call {
	return &MockNodeService_CanAcceptClientWriteRequest_Call{Call: _e.mock.On("CanAcceptClientWriteRequest")}
}

func (_c *MockNodeService_CanAcceptClientWriteRequest_Call) Run(run func()) *MockNodeService_CanAcceptClientWriteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_CanAcceptClientWriteRequest_Call) Return(b bool) *MockNodeService_CanAcceptClientWriteRequest_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNodeService_CanAcceptClientWriteRequest_Call) RunAndReturn(run func() bool) *MockNodeService_CanAcceptClientWriteRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CanAcceptRequest provides a mock function for the type MockNodeService
func (_mock *MockNodeService) CanAcceptRequest() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CanAcceptRequest")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockNodeService_CanAcceptRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAcceptRequest'
type MockNodeService_CanAcceptRequest_Call struct {
	*mock.Call
}

// CanAcceptRequest is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) CanAcceptRequest() *MockNodeService_CanAcceptRequest_Call {
	return &MockNodeService_CanAcceptRequest_Call{Call: _e.mock.On("CanAcceptRequest")}
}

func (_c *MockNodeService_CanAcceptRequest_Call) Run(run func()) *MockNodeService_CanAcceptRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_CanAcceptRequest_Call) Return(b bool) *MockNodeService_CanAcceptRequest_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockNodeService_CanAcceptRequest_Call) RunAndReturn(run func() bool) *MockNodeService_CanAcceptRequest_Call {
	_c.Call.Return(run)
	return _c
}

// CommitFetchedUnCommittedLogs provides a mock function for the type MockNodeService
func (_mock *MockNodeService) CommitFetchedUnCommittedLogs(peerFanIns []models.PeerFanIn) {
	_mock.Called(peerFanIns)
	return
}

// MockNodeService_CommitFetchedUnCommittedLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitFetchedUnCommittedLogs'
type MockNodeService_CommitFetchedUnCommittedLogs_Call struct {
	*mock.Call
}

// CommitFetchedUnCommittedLogs is a helper method to define mock.On call
//   - peerFanIns []models.PeerFanIn
func (_e *MockNodeService_Expecter) CommitFetchedUnCommittedLogs(peerFanIns interface{}) *MockNodeService_CommitFetchedUnCommittedLogs_Call {
	return &MockNodeService_CommitFetchedUnCommittedLogs_Call{Call: _e.mock.On("CommitFetchedUnCommittedLogs", peerFanIns)}
}

func (_c *MockNodeService_CommitFetchedUnCommittedLogs_Call) Run(run func(peerFanIns []models.PeerFanIn)) *MockNodeService_CommitFetchedUnCommittedLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.PeerFanIn
		if args[0] != nil {
			arg0 = args[0].([]models.PeerFanIn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_CommitFetchedUnCommittedLogs_Call) Return() *MockNodeService_CommitFetchedUnCommittedLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_CommitFetchedUnCommittedLogs_Call) RunAndReturn(run func(peerFanIns []models.PeerFanIn)) *MockNodeService_CommitFetchedUnCommittedLogs_Call {
	_c.Run(run)
	return _c
}

// DemoteNode provides a mock function for the type MockNodeService
func (_mock *MockNodeService) DemoteNode(ctx context.Context, nodeId uint64) error {
	ret := _mock.Called(ctx, nodeId)

	if len(ret) == 0 {
		panic("no return value specified for DemoteNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, nodeId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_DemoteNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DemoteNode'
type MockNodeService_DemoteNode_Call struct {
	*mock.Call
}

// DemoteNode is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeId uint64
func (_e *MockNodeService_Expecter) DemoteNode(ctx interface{}, nodeId interface{}) *MockNodeService_DemoteNode_Call {
	return &MockNodeService_DemoteNode_Call{Call: _e.mock.On("DemoteNode", ctx, nodeId)}
}

func (_c *MockNodeService_DemoteNode_Call) Run(run func(ctx context.Context, nodeId uint64)) *MockNodeService_DemoteNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeService_DemoteNode_Call) Return(err error) *MockNodeService_DemoteNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_DemoteNode_Call) RunAndReturn(run func(ctx context.Context, nodeId uint64) error) *MockNodeService_DemoteNode_Call {
	_c.Call.Return(run)
	return _c
}

// FanInLocalDataFromPeers provides a mock function for the type MockNodeService
func (_mock *MockNodeService) FanInLocalDataFromPeers() {
	_mock.Called()
	return
}

// MockNodeService_FanInLocalDataFromPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FanInLocalDataFromPeers'
type MockNodeService_FanInLocalDataFromPeers_Call struct {
	*mock.Call
}

// FanInLocalDataFromPeers is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) FanInLocalDataFromPeers() *MockNodeService_FanInLocalDataFromPeers_Call {
	return &MockNodeService_FanInLocalDataFromPeers_Call{Call: _e.mock.On("FanInLocalDataFromPeers")}
}

func (_c *MockNodeService_FanInLocalDataFromPeers_Call) Run(run func()) *MockNodeService_FanInLocalDataFromPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_FanInLocalDataFromPeers_Call) Return() *MockNodeService_FanInLocalDataFromPeers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_FanInLocalDataFromPeers_Call) RunAndReturn(run func()) *MockNodeService_FanInLocalDataFromPeers_Call {
	_c.Run(run)
	return _c
}

// FanInLocalDataFromPeersSync provides a mock function for the type MockNodeService
func (_mock *MockNodeService) FanInLocalDataFromPeersSync() {
	_mock.Called()
	return
}

// MockNodeService_FanInLocalDataFromPeersSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FanInLocalDataFromPeersSync'
type MockNodeService_FanInLocalDataFromPeersSync_Call struct {
	*mock.Call
}

// FanInLocalDataFromPeersSync is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) FanInLocalDataFromPeersSync() *MockNodeService_FanInLocalDataFromPeersSync_Call {
	return &MockNodeService_FanInLocalDataFromPeersSync_Call{Call: _e.mock.On("FanInLocalDataFromPeersSync")}
}

func (_c *MockNodeService_FanInLocalDataFromPeersSync_Call) Run(run func()) *MockNodeService_FanInLocalDataFromPeersSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_FanInLocalDataFromPeersSync_Call) Return() *MockNodeService_FanInLocalDataFromPeersSync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_FanInLocalDataFromPeersSync_Call) RunAndReturn(run func()) *MockNodeService_FanInLocalDataFromPeersSync_Call {
	_c.Run(run)
	return _c
}

// ForceRebuildCluster provides a mock function for the type MockNodeService
func (_mock *MockNodeService) ForceRebuildCluster(ctx context.Context, seedNodeId uint64) error {
	ret := _mock.Called(ctx, seedNodeId)

	if len(ret) == 0 {
		panic("no return value specified for ForceRebuildCluster")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, seedNodeId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_ForceRebuildCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ForceRebuildCluster'
type MockNodeService_ForceRebuildCluster_Call struct {
	*mock.Call
}

// ForceRebuildCluster is a helper method to define mock.On call
//   - ctx context.Context
//   - seedNodeId uint64
func (_e *MockNodeService_Expecter) ForceRebuildCluster(ctx interface{}, seedNodeId interface{}) *MockNodeService_ForceRebuildCluster_Call {
	return &MockNodeService_ForceRebuildCluster_Call{Call: _e.mock.On("ForceRebuildCluster", ctx, seedNodeId)}
}

func (_c *MockNodeService_ForceRebuildCluster_Call) Run(run func(ctx context.Context, seedNodeId uint64)) *MockNodeService_ForceRebuildCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeService_ForceRebuildCluster_Call) Return(err error) *MockNodeService_ForceRebuildCluster_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_ForceRebuildCluster_Call) RunAndReturn(run func(ctx context.Context, seedNodeId uint64) error) *MockNodeService_ForceRebuildCluster_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobExecutor provides a mock function for the type MockNodeService
func (_mock *MockNodeService) GetJobExecutor() executor.JobExecutorService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJobExecutor")
	}

	var r0 executor.JobExecutorService
	if returnFunc, ok := ret.Get(0).(func() executor.JobExecutorService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(executor.JobExecutorService)
		}
	}
	return r0
}

// MockNodeService_GetJobExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobExecutor'
type MockNodeService_GetJobExecutor_Call struct {
	*mock.Call
}

// GetJobExecutor is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) GetJobExecutor() *MockNodeService_GetJobExecutor_Call {
	return &MockNodeService_GetJobExecutor_Call{Call: _e.mock.On("GetJobExecutor")}
}

func (_c *MockNodeService_GetJobExecutor_Call) Run(run func()) *MockNodeService_GetJobExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_GetJobExecutor_Call) Return(jobExecutorService executor.JobExecutorService) *MockNodeService_GetJobExecutor_Call {
	_c.Call.Return(jobExecutorService)
	return _c
}

func (_c *MockNodeService_GetJobExecutor_Call) RunAndReturn(run func() executor.JobExecutorService) *MockNodeService_GetJobExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobQueuesRepo provides a mock function for the type MockNodeService
func (_mock *MockNodeService) GetJobQueuesRepo() job_queue.JobQueuesRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJobQueuesRepo")
	}

	var r0 job_queue.JobQueuesRepo
	if returnFunc, ok := ret.Get(0).(func() job_queue.JobQueuesRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(job_queue.JobQueuesRepo)
		}
	}
	return r0
}

// MockNodeService_GetJobQueuesRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobQueuesRepo'
type MockNodeService_GetJobQueuesRepo_Call struct {
	*mock.Call
}

// GetJobQueuesRepo is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) GetJobQueuesRepo() *MockNodeService_GetJobQueuesRepo_Call {
	return &MockNodeService_GetJobQueuesRepo_Call{Call: _e.mock.On("GetJobQueuesRepo")}
}

func (_c *MockNodeService_GetJobQueuesRepo_Call) Run(run func()) *MockNodeService_GetJobQueuesRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_GetJobQueuesRepo_Call) Return(jobQueuesRepo job_queue.JobQueuesRepo) *MockNodeService_GetJobQueuesRepo_Call {
	_c.Call.Return(jobQueuesRepo)
	return _c
}

func (_c *MockNodeService_GetJobQueuesRepo_Call) RunAndReturn(run func() job_queue.JobQueuesRepo) *MockNodeService_GetJobQueuesRepo_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocalQuotaAllocations provides a mock function for the type MockNodeService
func (_mock *MockNodeService) GetLocalQuotaAllocations() map[uint64]uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLocalQuotaAllocations")
	}

	var r0 map[uint64]uint64
	if returnFunc, ok := ret.Get(0).(func() map[uint64]uint64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]uint64)
		}
	}
	return r0
}

// MockNodeService_GetLocalQuotaAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocalQuotaAllocations'
type MockNodeService_GetLocalQuotaAllocations_Call struct {
	*mock.Call
}

// GetLocalQuotaAllocations is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) GetLocalQuotaAllocations() *MockNodeService_GetLocalQuotaAllocations_Call {
	return &MockNodeService_GetLocalQuotaAllocations_Call{Call: _e.mock.On("GetLocalQuotaAllocations")}
}

func (_c *MockNodeService_GetLocalQuotaAllocations_Call) Run(run func()) *MockNodeService_GetLocalQuotaAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_GetLocalQuotaAllocations_Call) Return(uint64ToUint64 map[uint64]uint64) *MockNodeService_GetLocalQuotaAllocations_Call {
	_c.Call.Return(uint64ToUint64)
	return _c
}

func (_c *MockNodeService_GetLocalQuotaAllocations_Call) RunAndReturn(run func() map[uint64]uint64) *MockNodeService_GetLocalQuotaAllocations_Call {
	_c.Call.Return(run)
	return _c
}

// GetPeers provides a mock function for the type MockNodeService
func (_mock *MockNodeService) GetPeers() []config.RaftNode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPeers")
	}

	var r0 []config.RaftNode
	if returnFunc, ok := ret.Get(0).(func() []config.RaftNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.RaftNode)
		}
	}
	return r0
}

// MockNodeService_GetPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPeers'
type MockNodeService_GetPeers_Call struct {
	*mock.Call
}

// GetPeers is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) GetPeers() *MockNodeService_GetPeers_Call {
	return &MockNodeService_GetPeers_Call{Call: _e.mock.On("GetPeers")}
}

func (_c *MockNodeService_GetPeers_Call) Run(run func()) *MockNodeService_GetPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_GetPeers_Call) Return(raftNodes []config.RaftNode) *MockNodeService_GetPeers_Call {
	_c.Call.Return(raftNodes)
	return _c
}

func (_c *MockNodeService_GetPeers_Call) RunAndReturn(run func() []config.RaftNode) *MockNodeService_GetPeers_Call {
	_c.Call.Return(run)
	return _c
}

// GetRaftLeaderWithId provides a mock function for the type MockNodeService
func (_mock *MockNodeService) GetRaftLeaderWithId() (raft.ServerAddress, raft.ServerID) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRaftLeaderWithId")
	}

	var r0 raft.ServerAddress
	var r1 raft.ServerID
	if returnFunc, ok := ret.Get(0).(func() (raft.ServerAddress, raft.ServerID)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() raft.ServerAddress); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(raft.ServerAddress)
	}
	if returnFunc, ok := ret.Get(1).(func() raft.ServerID); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Get(1).(raft.ServerID)
	}
	return r0, r1
}

// MockNodeService_GetRaftLeaderWithId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRaftLeaderWithId'
type MockNodeService_GetRaftLeaderWithId_Call struct {
	*mock.Call
}

// GetRaftLeaderWithId is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) GetRaftLeaderWithId() *MockNodeService_GetRaftLeaderWithId_Call {
	return &MockNodeService_GetRaftLeaderWithId_Call{Call: _e.mock.On("GetRaftLeaderWithId")}
}

func (_c *MockNodeService_GetRaftLeaderWithId_Call) Run(run func()) *MockNodeService_GetRaftLeaderWithId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_GetRaftLeaderWithId_Call) Return(serverAddress raft.ServerAddress, serverID raft.ServerID) *MockNodeService_GetRaftLeaderWithId_Call {
	_c.Call.Return(serverAddress, serverID)
	return _c
}

func (_c *MockNodeService_GetRaftLeaderWithId_Call) RunAndReturn(run func() (raft.ServerAddress, raft.ServerID)) *MockNodeService_GetRaftLeaderWithId_Call {
	_c.Call.Return(run)
	return _c
}

// GetRaftStats provides a mock function for the type MockNodeService
func (_mock *MockNodeService) GetRaftStats() map[string]string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetRaftStats")
	}

	var r0 map[string]string
	if returnFunc, ok := ret.Get(0).(func() map[string]string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}
	return r0
}

// MockNodeService_GetRaftStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRaftStats'
type MockNodeService_GetRaftStats_Call struct {
	*mock.Call
}

// GetRaftStats is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) GetRaftStats() *MockNodeService_GetRaftStats_Call {
	return &MockNodeService_GetRaftStats_Call{Call: _e.mock.On("GetRaftStats")}
}

func (_c *MockNodeService_GetRaftStats_Call) Run(run func()) *MockNodeService_GetRaftStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_GetRaftStats_Call) Return(stringToString map[string]string) *MockNodeService_GetRaftStats_Call {
	_c.Call.Return(stringToString)
	return _c
}

func (_c *MockNodeService_GetRaftStats_Call) RunAndReturn(run func() map[string]string) *MockNodeService_GetRaftStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomFanInPeerHTTPAddresses provides a mock function for the type MockNodeService
func (_mock *MockNodeService) GetRandomFanInPeerHTTPAddresses(excludeList map[string]bool) []string {
	ret := _mock.Called(excludeList)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomFanInPeerHTTPAddresses")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(map[string]bool) []string); ok {
		r0 = returnFunc(excludeList)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockNodeService_GetRandomFanInPeerHTTPAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomFanInPeerHTTPAddresses'
type MockNodeService_GetRandomFanInPeerHTTPAddresses_Call struct {
	*mock.Call
}

// GetRandomFanInPeerHTTPAddresses is a helper method to define mock.On call
//   - excludeList map[string]bool
func (_e *MockNodeService_Expecter) GetRandomFanInPeerHTTPAddresses(excludeList interface{}) *MockNodeService_GetRandomFanInPeerHTTPAddresses_Call {
	return &MockNodeService_GetRandomFanInPeerHTTPAddresses_Call{Call: _e.mock.On("GetRandomFanInPeerHTTPAddresses", excludeList)}
}

func (_c *MockNodeService_GetRandomFanInPeerHTTPAddresses_Call) Run(run func(excludeList map[string]bool)) *MockNodeService_GetRandomFanInPeerHTTPAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]bool
		if args[0] != nil {
			arg0 = args[0].(map[string]bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_GetRandomFanInPeerHTTPAddresses_Call) Return(strings []string) *MockNodeService_GetRandomFanInPeerHTTPAddresses_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockNodeService_GetRandomFanInPeerHTTPAddresses_Call) RunAndReturn(run func(excludeList map[string]bool) []string) *MockNodeService_GetRandomFanInPeerHTTPAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// GetUncommittedLogs provides a mock function for the type MockNodeService
func (_mock *MockNodeService) GetUncommittedLogs(requestId string) {
	_mock.Called(requestId)
	return
}

// MockNodeService_GetUncommittedLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUncommittedLogs'
type MockNodeService_GetUncommittedLogs_Call struct {
	*mock.Call
}

// GetUncommittedLogs is a helper method to define mock.On call
//   - requestId string
func (_e *MockNodeService_Expecter) GetUncommittedLogs(requestId interface{}) *MockNodeService_GetUncommittedLogs_Call {
	return &MockNodeService_GetUncommittedLogs_Call{Call: _e.mock.On("GetUncommittedLogs", requestId)}
}

func (_c *MockNodeService_GetUncommittedLogs_Call) Run(run func(requestId string)) *MockNodeService_GetUncommittedLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_GetUncommittedLogs_Call) Return() *MockNodeService_GetUncommittedLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_GetUncommittedLogs_Call) RunAndReturn(run func(requestId string)) *MockNodeService_GetUncommittedLogs_Call {
	_c.Run(run)
	return _c
}

// HandleRaftLeadershipChanges provides a mock function for the type MockNodeService
func (_mock *MockNodeService) HandleRaftLeadershipChanges(isLeader bool) {
	_mock.Called(isLeader)
	return
}

// MockNodeService_HandleRaftLeadershipChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRaftLeadershipChanges'
type MockNodeService_HandleRaftLeadershipChanges_Call struct {
	*mock.Call
}

// HandleRaftLeadershipChanges is a helper method to define mock.On call
//   - isLeader bool
func (_e *MockNodeService_Expecter) HandleRaftLeadershipChanges(isLeader interface{}) *MockNodeService_HandleRaftLeadershipChanges_Call {
	return &MockNodeService_HandleRaftLeadershipChanges_Call{Call: _e.mock.On("HandleRaftLeadershipChanges", isLeader)}
}

func (_c *MockNodeService_HandleRaftLeadershipChanges_Call) Run(run func(isLeader bool)) *MockNodeService_HandleRaftLeadershipChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_HandleRaftLeadershipChanges_Call) Return() *MockNodeService_HandleRaftLeadershipChanges_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_HandleRaftLeadershipChanges_Call) RunAndReturn(run func(isLeader bool)) *MockNodeService_HandleRaftLeadershipChanges_Call {
	_c.Run(run)
	return _c
}

// HandleRaftLeadershipChangesDebounced provides a mock function for the type MockNodeService
func (_mock *MockNodeService) HandleRaftLeadershipChangesDebounced(isLeader bool) {
	_mock.Called(isLeader)
	return
}

// MockNodeService_HandleRaftLeadershipChangesDebounced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRaftLeadershipChangesDebounced'
type MockNodeService_HandleRaftLeadershipChangesDebounced_Call struct {
	*mock.Call
}

// HandleRaftLeadershipChangesDebounced is a helper method to define mock.On call
//   - isLeader bool
func (_e *MockNodeService_Expecter) HandleRaftLeadershipChangesDebounced(isLeader interface{}) *MockNodeService_HandleRaftLeadershipChangesDebounced_Call {
	return &MockNodeService_HandleRaftLeadershipChangesDebounced_Call{Call: _e.mock.On("HandleRaftLeadershipChangesDebounced", isLeader)}
}

func (_c *MockNodeService_HandleRaftLeadershipChangesDebounced_Call) Run(run func(isLeader bool)) *MockNodeService_HandleRaftLeadershipChangesDebounced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_HandleRaftLeadershipChangesDebounced_Call) Return() *MockNodeService_HandleRaftLeadershipChangesDebounced_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_HandleRaftLeadershipChangesDebounced_Call) RunAndReturn(run func(isLeader bool)) *MockNodeService_HandleRaftLeadershipChangesDebounced_Call {
	_c.Run(run)
	return _c
}

// HandleRaftObserverChannelChanges provides a mock function for the type MockNodeService
func (_mock *MockNodeService) HandleRaftObserverChannelChanges(o raft.Observation) {
	_mock.Called(o)
	return
}

// MockNodeService_HandleRaftObserverChannelChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleRaftObserverChannelChanges'
type MockNodeService_HandleRaftObserverChannelChanges_Call struct {
	*mock.Call
}

// HandleRaftObserverChannelChanges is a helper method to define mock.On call
//   - o raft.Observation
func (_e *MockNodeService_Expecter) HandleRaftObserverChannelChanges(o interface{}) *MockNodeService_HandleRaftObserverChannelChanges_Call {
	return &MockNodeService_HandleRaftObserverChannelChanges_Call{Call: _e.mock.On("HandleRaftObserverChannelChanges", o)}
}

func (_c *MockNodeService_HandleRaftObserverChannelChanges_Call) Run(run func(o raft.Observation)) *MockNodeService_HandleRaftObserverChannelChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 raft.Observation
		if args[0] != nil {
			arg0 = args[0].(raft.Observation)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_HandleRaftObserverChannelChanges_Call) Return() *MockNodeService_HandleRaftObserverChannelChanges_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_HandleRaftObserverChannelChanges_Call) RunAndReturn(run func(o raft.Observation)) *MockNodeService_HandleRaftObserverChannelChanges_Call {
	_c.Run(run)
	return _c
}

// HandleUncommittedAsyncTasks provides a mock function for the type MockNodeService
func (_mock *MockNodeService) HandleUncommittedAsyncTasks(asyncTasks []models.AsyncTask) {
	_mock.Called(asyncTasks)
	return
}

// MockNodeService_HandleUncommittedAsyncTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUncommittedAsyncTasks'
type MockNodeService_HandleUncommittedAsyncTasks_Call struct {
	*mock.Call
}

// HandleUncommittedAsyncTasks is a helper method to define mock.On call
//   - asyncTasks []models.AsyncTask
func (_e *MockNodeService_Expecter) HandleUncommittedAsyncTasks(asyncTasks interface{}) *MockNodeService_HandleUncommittedAsyncTasks_Call {
	return &MockNodeService_HandleUncommittedAsyncTasks_Call{Call: _e.mock.On("HandleUncommittedAsyncTasks", asyncTasks)}
}

func (_c *MockNodeService_HandleUncommittedAsyncTasks_Call) Run(run func(asyncTasks []models.AsyncTask)) *MockNodeService_HandleUncommittedAsyncTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.AsyncTask
		if args[0] != nil {
			arg0 = args[0].([]models.AsyncTask)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_HandleUncommittedAsyncTasks_Call) Return() *MockNodeService_HandleUncommittedAsyncTasks_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_HandleUncommittedAsyncTasks_Call) RunAndReturn(run func(asyncTasks []models.AsyncTask)) *MockNodeService_HandleUncommittedAsyncTasks_Call {
	_c.Run(run)
	return _c
}

// ListNodes provides a mock function for the type MockNodeService
func (_mock *MockNodeService) ListNodes(ctx context.Context) ([]config.RaftNode, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListNodes")
	}

	var r0 []config.RaftNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]config.RaftNode, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []config.RaftNode); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.RaftNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNodeService_ListNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNodes'
type MockNodeService_ListNodes_Call struct {
	*mock.Call
}

// ListNodes is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeService_Expecter) ListNodes(ctx interface{}) *MockNodeService_ListNodes_Call {
	return &MockNodeService_ListNodes_Call{Call: _e.mock.On("ListNodes", ctx)}
}

func (_c *MockNodeService_ListNodes_Call) Run(run func(ctx context.Context)) *MockNodeService_ListNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_ListNodes_Call) Return(raftNodes []config.RaftNode, err error) *MockNodeService_ListNodes_Call {
	_c.Call.Return(raftNodes, err)
	return _c
}

func (_c *MockNodeService_ListNodes_Call) RunAndReturn(run func(ctx context.Context) ([]config.RaftNode, error)) *MockNodeService_ListNodes_Call {
	_c.Call.Return(run)
	return _c
}

// ListenOnInputQueues provides a mock function for the type MockNodeService
func (_mock *MockNodeService) ListenOnInputQueues() {
	_mock.Called()
	return
}

// MockNodeService_ListenOnInputQueues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenOnInputQueues'
type MockNodeService_ListenOnInputQueues_Call struct {
	*mock.Call
}

// ListenOnInputQueues is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) ListenOnInputQueues() *MockNodeService_ListenOnInputQueues_Call {
	return &MockNodeService_ListenOnInputQueues_Call{Call: _e.mock.On("ListenOnInputQueues")}
}

func (_c *MockNodeService_ListenOnInputQueues_Call) Run(run func()) *MockNodeService_ListenOnInputQueues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_ListenOnInputQueues_Call) Return() *MockNodeService_ListenOnInputQueues_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_ListenOnInputQueues_Call) RunAndReturn(run func()) *MockNodeService_ListenOnInputQueues_Call {
	_c.Run(run)
	return _c
}

// NotifyLeaderAccountExhaustion provides a mock function for the type MockNodeService
func (_mock *MockNodeService) NotifyLeaderAccountExhaustion(accountId uint64) error {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for NotifyLeaderAccountExhaustion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = returnFunc(accountId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_NotifyLeaderAccountExhaustion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyLeaderAccountExhaustion'
type MockNodeService_NotifyLeaderAccountExhaustion_Call struct {
	*mock.Call
}

// NotifyLeaderAccountExhaustion is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockNodeService_Expecter) NotifyLeaderAccountExhaustion(accountId interface{}) *MockNodeService_NotifyLeaderAccountExhaustion_Call {
	return &MockNodeService_NotifyLeaderAccountExhaustion_Call{Call: _e.mock.On("NotifyLeaderAccountExhaustion", accountId)}
}

func (_c *MockNodeService_NotifyLeaderAccountExhaustion_Call) Run(run func(accountId uint64)) *MockNodeService_NotifyLeaderAccountExhaustion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_NotifyLeaderAccountExhaustion_Call) Return(err error) *MockNodeService_NotifyLeaderAccountExhaustion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_NotifyLeaderAccountExhaustion_Call) RunAndReturn(run func(accountId uint64) error) *MockNodeService_NotifyLeaderAccountExhaustion_Call {
	_c.Call.Return(run)
	return _c
}

// PromoteNode provides a mock function for the type MockNodeService
func (_mock *MockNodeService) PromoteNode(ctx context.Context, nodeId uint64) error {
	ret := _mock.Called(ctx, nodeId)

	if len(ret) == 0 {
		panic("no return value specified for PromoteNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, nodeId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_PromoteNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoteNode'
type MockNodeService_PromoteNode_Call struct {
	*mock.Call
}

// PromoteNode is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeId uint64
func (_e *MockNodeService_Expecter) PromoteNode(ctx interface{}, nodeId interface{}) *MockNodeService_PromoteNode_Call {
	return &MockNodeService_PromoteNode_Call{Call: _e.mock.On("PromoteNode", ctx, nodeId)}
}

func (_c *MockNodeService_PromoteNode_Call) Run(run func(ctx context.Context, nodeId uint64)) *MockNodeService_PromoteNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeService_PromoteNode_Call) Return(err error) *MockNodeService_PromoteNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_PromoteNode_Call) RunAndReturn(run func(ctx context.Context, nodeId uint64) error) *MockNodeService_PromoteNode_Call {
	_c.Call.Return(run)
	return _c
}

// ReconcileRaftMembershipWithPeers provides a mock function for the type MockNodeService
func (_mock *MockNodeService) ReconcileRaftMembershipWithPeers(peers []config.RaftNode) {
	_mock.Called(peers)
	return
}

// MockNodeService_ReconcileRaftMembershipWithPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReconcileRaftMembershipWithPeers'
type MockNodeService_ReconcileRaftMembershipWithPeers_Call struct {
	*mock.Call
}

// ReconcileRaftMembershipWithPeers is a helper method to define mock.On call
//   - peers []config.RaftNode
func (_e *MockNodeService_Expecter) ReconcileRaftMembershipWithPeers(peers interface{}) *MockNodeService_ReconcileRaftMembershipWithPeers_Call {
	return &MockNodeService_ReconcileRaftMembershipWithPeers_Call{Call: _e.mock.On("ReconcileRaftMembershipWithPeers", peers)}
}

func (_c *MockNodeService_ReconcileRaftMembershipWithPeers_Call) Run(run func(peers []config.RaftNode)) *MockNodeService_ReconcileRaftMembershipWithPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []config.RaftNode
		if args[0] != nil {
			arg0 = args[0].([]config.RaftNode)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_ReconcileRaftMembershipWithPeers_Call) Return() *MockNodeService_ReconcileRaftMembershipWithPeers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_ReconcileRaftMembershipWithPeers_Call) RunAndReturn(run func(peers []config.RaftNode)) *MockNodeService_ReconcileRaftMembershipWithPeers_Call {
	_c.Run(run)
	return _c
}

// RemoveNode provides a mock function for the type MockNodeService
func (_mock *MockNodeService) RemoveNode(ctx context.Context, nodeId uint64) error {
	ret := _mock.Called(ctx, nodeId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = returnFunc(ctx, nodeId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_RemoveNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveNode'
type MockNodeService_RemoveNode_Call struct {
	*mock.Call
}

// RemoveNode is a helper method to define mock.On call
//   - ctx context.Context
//   - nodeId uint64
func (_e *MockNodeService_Expecter) RemoveNode(ctx interface{}, nodeId interface{}) *MockNodeService_RemoveNode_Call {
	return &MockNodeService_RemoveNode_Call{Call: _e.mock.On("RemoveNode", ctx, nodeId)}
}

func (_c *MockNodeService_RemoveNode_Call) Run(run func(ctx context.Context, nodeId uint64)) *MockNodeService_RemoveNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeService_RemoveNode_Call) Return(err error) *MockNodeService_RemoveNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_RemoveNode_Call) RunAndReturn(run func(ctx context.Context, nodeId uint64) error) *MockNodeService_RemoveNode_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveSelfFromCluster provides a mock function for the type MockNodeService
func (_mock *MockNodeService) RemoveSelfFromCluster(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RemoveSelfFromCluster")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_RemoveSelfFromCluster_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveSelfFromCluster'
type MockNodeService_RemoveSelfFromCluster_Call struct {
	*mock.Call
}

// RemoveSelfFromCluster is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeService_Expecter) RemoveSelfFromCluster(ctx interface{}) *MockNodeService_RemoveSelfFromCluster_Call {
	return &MockNodeService_RemoveSelfFromCluster_Call{Call: _e.mock.On("RemoveSelfFromCluster", ctx)}
}

func (_c *MockNodeService_RemoveSelfFromCluster_Call) Run(run func(ctx context.Context)) *MockNodeService_RemoveSelfFromCluster_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_RemoveSelfFromCluster_Call) Return(err error) *MockNodeService_RemoveSelfFromCluster_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_RemoveSelfFromCluster_Call) RunAndReturn(run func(ctx context.Context) error) *MockNodeService_RemoveSelfFromCluster_Call {
	_c.Call.Return(run)
	return _c
}

// ResetLocalQuotaAllocations provides a mock function for the type MockNodeService
func (_mock *MockNodeService) ResetLocalQuotaAllocations() {
	_mock.Called()
	return
}

// MockNodeService_ResetLocalQuotaAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetLocalQuotaAllocations'
type MockNodeService_ResetLocalQuotaAllocations_Call struct {
	*mock.Call
}

// ResetLocalQuotaAllocations is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) ResetLocalQuotaAllocations() *MockNodeService_ResetLocalQuotaAllocations_Call {
	return &MockNodeService_ResetLocalQuotaAllocations_Call{Call: _e.mock.On("ResetLocalQuotaAllocations")}
}

func (_c *MockNodeService_ResetLocalQuotaAllocations_Call) Run(run func()) *MockNodeService_ResetLocalQuotaAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_ResetLocalQuotaAllocations_Call) Return() *MockNodeService_ResetLocalQuotaAllocations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_ResetLocalQuotaAllocations_Call) RunAndReturn(run func()) *MockNodeService_ResetLocalQuotaAllocations_Call {
	_c.Run(run)
	return _c
}

// ResetRaftState provides a mock function for the type MockNodeService
func (_mock *MockNodeService) ResetRaftState(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetRaftState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_ResetRaftState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetRaftState'
type MockNodeService_ResetRaftState_Call struct {
	*mock.Call
}

// ResetRaftState is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeService_Expecter) ResetRaftState(ctx interface{}) *MockNodeService_ResetRaftState_Call {
	return &MockNodeService_ResetRaftState_Call{Call: _e.mock.On("ResetRaftState", ctx)}
}

func (_c *MockNodeService_ResetRaftState_Call) Run(run func(ctx context.Context)) *MockNodeService_ResetRaftState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_ResetRaftState_Call) Return(err error) *MockNodeService_ResetRaftState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_ResetRaftState_Call) RunAndReturn(run func(ctx context.Context) error) *MockNodeService_ResetRaftState_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreDatabase provides a mock function for the type MockNodeService
func (_mock *MockNodeService) RestoreDatabase(ctx context.Context, filePath string, requestId string) error {
	ret := _mock.Called(ctx, filePath, requestId)

	if len(ret) == 0 {
		panic("no return value specified for RestoreDatabase")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, filePath, requestId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_RestoreDatabase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreDatabase'
type MockNodeService_RestoreDatabase_Call struct {
	*mock.Call
}

// RestoreDatabase is a helper method to define mock.On call
//   - ctx context.Context
//   - filePath string
//   - requestId string
func (_e *MockNodeService_Expecter) RestoreDatabase(ctx interface{}, filePath interface{}, requestId interface{}) *MockNodeService_RestoreDatabase_Call {
	return &MockNodeService_RestoreDatabase_Call{Call: _e.mock.On("RestoreDatabase", ctx, filePath, requestId)}
}

func (_c *MockNodeService_RestoreDatabase_Call) Run(run func(ctx context.Context, filePath string, requestId string)) *MockNodeService_RestoreDatabase_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockNodeService_RestoreDatabase_Call) Return(err error) *MockNodeService_RestoreDatabase_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_RestoreDatabase_Call) RunAndReturn(run func(ctx context.Context, filePath string, requestId string) error) *MockNodeService_RestoreDatabase_Call {
	_c.Call.Return(run)
	return _c
}

// ReturnUncommittedLogs provides a mock function for the type MockNodeService
func (_mock *MockNodeService) ReturnUncommittedLogs(requestId string) {
	_mock.Called(requestId)
	return
}

// MockNodeService_ReturnUncommittedLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnUncommittedLogs'
type MockNodeService_ReturnUncommittedLogs_Call struct {
	*mock.Call
}

// ReturnUncommittedLogs is a helper method to define mock.On call
//   - requestId string
func (_e *MockNodeService_Expecter) ReturnUncommittedLogs(requestId interface{}) *MockNodeService_ReturnUncommittedLogs_Call {
	return &MockNodeService_ReturnUncommittedLogs_Call{Call: _e.mock.On("ReturnUncommittedLogs", requestId)}
}

func (_c *MockNodeService_ReturnUncommittedLogs_Call) Run(run func(requestId string)) *MockNodeService_ReturnUncommittedLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_ReturnUncommittedLogs_Call) Return() *MockNodeService_ReturnUncommittedLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_ReturnUncommittedLogs_Call) RunAndReturn(run func(requestId string)) *MockNodeService_ReturnUncommittedLogs_Call {
	_c.Run(run)
	return _c
}

// SelectRandomPeersToFanIn provides a mock function for the type MockNodeService
func (_mock *MockNodeService) SelectRandomPeersToFanIn() []models.PeerFanIn {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SelectRandomPeersToFanIn")
	}

	var r0 []models.PeerFanIn
	if returnFunc, ok := ret.Get(0).(func() []models.PeerFanIn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PeerFanIn)
		}
	}
	return r0
}

// MockNodeService_SelectRandomPeersToFanIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectRandomPeersToFanIn'
type MockNodeService_SelectRandomPeersToFanIn_Call struct {
	*mock.Call
}

// SelectRandomPeersToFanIn is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) SelectRandomPeersToFanIn() *MockNodeService_SelectRandomPeersToFanIn_Call {
	return &MockNodeService_SelectRandomPeersToFanIn_Call{Call: _e.mock.On("SelectRandomPeersToFanIn")}
}

func (_c *MockNodeService_SelectRandomPeersToFanIn_Call) Run(run func()) *MockNodeService_SelectRandomPeersToFanIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_SelectRandomPeersToFanIn_Call) Return(peerFanIns []models.PeerFanIn) *MockNodeService_SelectRandomPeersToFanIn_Call {
	_c.Call.Return(peerFanIns)
	return _c
}

func (_c *MockNodeService_SelectRandomPeersToFanIn_Call) RunAndReturn(run func() []models.PeerFanIn) *MockNodeService_SelectRandomPeersToFanIn_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockNodeService
func (_mock *MockNodeService) Start() {
	_mock.Called()
	return
}

// MockNodeService_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockNodeService_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) Start() *MockNodeService_Start_Call {
	return &MockNodeService_Start_Call{Call: _e.mock.On("Start")}
}

func (_c *MockNodeService_Start_Call) Run(run func()) *MockNodeService_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_Start_Call) Return() *MockNodeService_Start_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_Start_Call) RunAndReturn(run func()) *MockNodeService_Start_Call {
	_c.Run(run)
	return _c
}

// StartJobs provides a mock function for the type MockNodeService
func (_mock *MockNodeService) StartJobs() {
	_mock.Called()
	return
}

// MockNodeService_StartJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartJobs'
type MockNodeService_StartJobs_Call struct {
	*mock.Call
}

// StartJobs is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) StartJobs() *MockNodeService_StartJobs_Call {
	return &MockNodeService_StartJobs_Call{Call: _e.mock.On("StartJobs")}
}

func (_c *MockNodeService_StartJobs_Call) Run(run func()) *MockNodeService_StartJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_StartJobs_Call) Return() *MockNodeService_StartJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_StartJobs_Call) RunAndReturn(run func()) *MockNodeService_StartJobs_Call {
	_c.Run(run)
	return _c
}

// StartJobsOnWorkerNodes provides a mock function for the type MockNodeService
func (_mock *MockNodeService) StartJobsOnWorkerNodes() {
	_mock.Called()
	return
}

// MockNodeService_StartJobsOnWorkerNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartJobsOnWorkerNodes'
type MockNodeService_StartJobsOnWorkerNodes_Call struct {
	*mock.Call
}

// StartJobsOnWorkerNodes is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) StartJobsOnWorkerNodes() *MockNodeService_StartJobsOnWorkerNodes_Call {
	return &MockNodeService_StartJobsOnWorkerNodes_Call{Call: _e.mock.On("StartJobsOnWorkerNodes")}
}

func (_c *MockNodeService_StartJobsOnWorkerNodes_Call) Run(run func()) *MockNodeService_StartJobsOnWorkerNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_StartJobsOnWorkerNodes_Call) Return() *MockNodeService_StartJobsOnWorkerNodes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_StartJobsOnWorkerNodes_Call) RunAndReturn(run func()) *MockNodeService_StartJobsOnWorkerNodes_Call {
	_c.Run(run)
	return _c
}

// StopAcceptingClientWriteRequest provides a mock function for the type MockNodeService
func (_mock *MockNodeService) StopAcceptingClientWriteRequest() {
	_mock.Called()
	return
}

// MockNodeService_StopAcceptingClientWriteRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAcceptingClientWriteRequest'
type MockNodeService_StopAcceptingClientWriteRequest_Call struct {
	*mock.Call
}

// StopAcceptingClientWriteRequest is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) StopAcceptingClientWriteRequest() *MockNodeService_StopAcceptingClientWriteRequest_Call {
	return &MockNodeService_StopAcceptingClientWriteRequest_Call{Call: _e.mock.On("StopAcceptingClientWriteRequest")}
}

func (_c *MockNodeService_StopAcceptingClientWriteRequest_Call) Run(run func()) *MockNodeService_StopAcceptingClientWriteRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_StopAcceptingClientWriteRequest_Call) Return() *MockNodeService_StopAcceptingClientWriteRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_StopAcceptingClientWriteRequest_Call) RunAndReturn(run func()) *MockNodeService_StopAcceptingClientWriteRequest_Call {
	_c.Run(run)
	return _c
}

// StopAllJobsOnAllWorkerNodes provides a mock function for the type MockNodeService
func (_mock *MockNodeService) StopAllJobsOnAllWorkerNodes() {
	_mock.Called()
	return
}

// MockNodeService_StopAllJobsOnAllWorkerNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAllJobsOnAllWorkerNodes'
type MockNodeService_StopAllJobsOnAllWorkerNodes_Call struct {
	*mock.Call
}

// StopAllJobsOnAllWorkerNodes is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) StopAllJobsOnAllWorkerNodes() *MockNodeService_StopAllJobsOnAllWorkerNodes_Call {
	return &MockNodeService_StopAllJobsOnAllWorkerNodes_Call{Call: _e.mock.On("StopAllJobsOnAllWorkerNodes")}
}

func (_c *MockNodeService_StopAllJobsOnAllWorkerNodes_Call) Run(run func()) *MockNodeService_StopAllJobsOnAllWorkerNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_StopAllJobsOnAllWorkerNodes_Call) Return() *MockNodeService_StopAllJobsOnAllWorkerNodes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_StopAllJobsOnAllWorkerNodes_Call) RunAndReturn(run func()) *MockNodeService_StopAllJobsOnAllWorkerNodes_Call {
	_c.Run(run)
	return _c
}

// StopJobs provides a mock function for the type MockNodeService
func (_mock *MockNodeService) StopJobs() {
	_mock.Called()
	return
}

// MockNodeService_StopJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopJobs'
type MockNodeService_StopJobs_Call struct {
	*mock.Call
}

// StopJobs is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) StopJobs() *MockNodeService_StopJobs_Call {
	return &MockNodeService_StopJobs_Call{Call: _e.mock.On("StopJobs")}
}

func (_c *MockNodeService_StopJobs_Call) Run(run func()) *MockNodeService_StopJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_StopJobs_Call) Return() *MockNodeService_StopJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_StopJobs_Call) RunAndReturn(run func()) *MockNodeService_StopJobs_Call {
	_c.Run(run)
	return _c
}

// TransferLeadership provides a mock function for the type MockNodeService
func (_mock *MockNodeService) TransferLeadership(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for TransferLeadership")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_TransferLeadership_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferLeadership'
type MockNodeService_TransferLeadership_Call struct {
	*mock.Call
}

// TransferLeadership is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockNodeService_Expecter) TransferLeadership(ctx interface{}) *MockNodeService_TransferLeadership_Call {
	return &MockNodeService_TransferLeadership_Call{Call: _e.mock.On("TransferLeadership", ctx)}
}

func (_c *MockNodeService_TransferLeadership_Call) Run(run func(ctx context.Context)) *MockNodeService_TransferLeadership_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_TransferLeadership_Call) Return(err error) *MockNodeService_TransferLeadership_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_TransferLeadership_Call) RunAndReturn(run func(ctx context.Context) error) *MockNodeService_TransferLeadership_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobOnLeader provides a mock function for the type MockNodeService
func (_mock *MockNodeService) UpdateJobOnLeader(job models.Job) error {
	ret := _mock.Called(job)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobOnLeader")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(models.Job) error); ok {
		r0 = returnFunc(job)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_UpdateJobOnLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobOnLeader'
type MockNodeService_UpdateJobOnLeader_Call struct {
	*mock.Call
}

// UpdateJobOnLeader is a helper method to define mock.On call
//   - job models.Job
func (_e *MockNodeService_Expecter) UpdateJobOnLeader(job interface{}) *MockNodeService_UpdateJobOnLeader_Call {
	return &MockNodeService_UpdateJobOnLeader_Call{Call: _e.mock.On("UpdateJobOnLeader", job)}
}

func (_c *MockNodeService_UpdateJobOnLeader_Call) Run(run func(job models.Job)) *MockNodeService_UpdateJobOnLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Job
		if args[0] != nil {
			arg0 = args[0].(models.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_UpdateJobOnLeader_Call) Return(err error) *MockNodeService_UpdateJobOnLeader_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_UpdateJobOnLeader_Call) RunAndReturn(run func(job models.Job) error) *MockNodeService_UpdateJobOnLeader_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJobsStatusByAccountId provides a mock function for the type MockNodeService
func (_mock *MockNodeService) UpdateJobsStatusByAccountId(accountId uint64, status string) error {
	ret := _mock.Called(accountId, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJobsStatusByAccountId")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uint64, string) error); ok {
		r0 = returnFunc(accountId, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_UpdateJobsStatusByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJobsStatusByAccountId'
type MockNodeService_UpdateJobsStatusByAccountId_Call struct {
	*mock.Call
}

// UpdateJobsStatusByAccountId is a helper method to define mock.On call
//   - accountId uint64
//   - status string
func (_e *MockNodeService_Expecter) UpdateJobsStatusByAccountId(accountId interface{}, status interface{}) *MockNodeService_UpdateJobsStatusByAccountId_Call {
	return &MockNodeService_UpdateJobsStatusByAccountId_Call{Call: _e.mock.On("UpdateJobsStatusByAccountId", accountId, status)}
}

func (_c *MockNodeService_UpdateJobsStatusByAccountId_Call) Run(run func(accountId uint64, status string)) *MockNodeService_UpdateJobsStatusByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockNodeService_UpdateJobsStatusByAccountId_Call) Return(err error) *MockNodeService_UpdateJobsStatusByAccountId_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_UpdateJobsStatusByAccountId_Call) RunAndReturn(run func(accountId uint64, status string) error) *MockNodeService_UpdateJobsStatusByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateLocalQuotaAllocations provides a mock function for the type MockNodeService
func (_mock *MockNodeService) UpdateLocalQuotaAllocations(accountAllocations map[uint64]uint64) error {
	ret := _mock.Called(accountAllocations)

	if len(ret) == 0 {
		panic("no return value specified for UpdateLocalQuotaAllocations")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(map[uint64]uint64) error); ok {
		r0 = returnFunc(accountAllocations)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNodeService_UpdateLocalQuotaAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLocalQuotaAllocations'
type MockNodeService_UpdateLocalQuotaAllocations_Call struct {
	*mock.Call
}

// UpdateLocalQuotaAllocations is a helper method to define mock.On call
//   - accountAllocations map[uint64]uint64
func (_e *MockNodeService_Expecter) UpdateLocalQuotaAllocations(accountAllocations interface{}) *MockNodeService_UpdateLocalQuotaAllocations_Call {
	return &MockNodeService_UpdateLocalQuotaAllocations_Call{Call: _e.mock.On("UpdateLocalQuotaAllocations", accountAllocations)}
}

func (_c *MockNodeService_UpdateLocalQuotaAllocations_Call) Run(run func(accountAllocations map[uint64]uint64)) *MockNodeService_UpdateLocalQuotaAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[uint64]uint64
		if args[0] != nil {
			arg0 = args[0].(map[uint64]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNodeService_UpdateLocalQuotaAllocations_Call) Return(err error) *MockNodeService_UpdateLocalQuotaAllocations_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNodeService_UpdateLocalQuotaAllocations_Call) RunAndReturn(run func(accountAllocations map[uint64]uint64) error) *MockNodeService_UpdateLocalQuotaAllocations_Call {
	_c.Call.Return(run)
	return _c
}

// WatchPeersFromEtcd provides a mock function for the type MockNodeService
func (_mock *MockNodeService) WatchPeersFromEtcd() {
	_mock.Called()
	return
}

// MockNodeService_WatchPeersFromEtcd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchPeersFromEtcd'
type MockNodeService_WatchPeersFromEtcd_Call struct {
	*mock.Call
}

// WatchPeersFromEtcd is a helper method to define mock.On call
func (_e *MockNodeService_Expecter) WatchPeersFromEtcd() *MockNodeService_WatchPeersFromEtcd_Call {
	return &MockNodeService_WatchPeersFromEtcd_Call{Call: _e.mock.On("WatchPeersFromEtcd")}
}

func (_c *MockNodeService_WatchPeersFromEtcd_Call) Run(run func()) *MockNodeService_WatchPeersFromEtcd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockNodeService_WatchPeersFromEtcd_Call) Return() *MockNodeService_WatchPeersFromEtcd_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockNodeService_WatchPeersFromEtcd_Call) RunAndReturn(run func()) *MockNodeService_WatchPeersFromEtcd_Call {
	_c.Run(run)
	return _c
}
