// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"scheduler0/pkg/config"
	"scheduler0/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPeerCommunicator creates a new instance of MockPeerCommunicator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPeerCommunicator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPeerCommunicator {
	mock := &MockPeerCommunicator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPeerCommunicator is an autogenerated mock type for the PeerCommunicator type
type MockPeerCommunicator struct {
	mock.Mock
}

type MockPeerCommunicator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPeerCommunicator) EXPECT() *MockPeerCommunicator_Expecter {
	return &MockPeerCommunicator_Expecter{mock: &_m.Mock}
}

// AuthenticateWithPeersFromEtcd provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) AuthenticateWithPeersFromEtcd() map[string]Status {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateWithPeersFromEtcd")
	}

	var r0 map[string]Status
	if returnFunc, ok := ret.Get(0).(func() map[string]Status); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]Status)
		}
	}
	return r0
}

// MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateWithPeersFromEtcd'
type MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call struct {
	*mock.Call
}

// AuthenticateWithPeersFromEtcd is a helper method to define mock.On call
func (_e *MockPeerCommunicator_Expecter) AuthenticateWithPeersFromEtcd() *MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call {
	return &MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call{Call: _e.mock.On("AuthenticateWithPeersFromEtcd")}
}

func (_c *MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call) Run(run func()) *MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call) Return(stringToStatus map[string]Status) *MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call {
	_c.Call.Return(stringToStatus)
	return _c
}

func (_c *MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call) RunAndReturn(run func() map[string]Status) *MockPeerCommunicator_AuthenticateWithPeersFromEtcd_Call {
	_c.Call.Return(run)
	return _c
}

// CommitFetchedUnCommittedLogs provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) CommitFetchedUnCommittedLogs(peerFanIns []models.PeerFanIn) {
	_mock.Called(peerFanIns)
	return
}

// MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitFetchedUnCommittedLogs'
type MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call struct {
	*mock.Call
}

// CommitFetchedUnCommittedLogs is a helper method to define mock.On call
//   - peerFanIns []models.PeerFanIn
func (_e *MockPeerCommunicator_Expecter) CommitFetchedUnCommittedLogs(peerFanIns interface{}) *MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call {
	return &MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call{Call: _e.mock.On("CommitFetchedUnCommittedLogs", peerFanIns)}
}

func (_c *MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call) Run(run func(peerFanIns []models.PeerFanIn)) *MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.PeerFanIn
		if args[0] != nil {
			arg0 = args[0].([]models.PeerFanIn)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call) Return() *MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call) RunAndReturn(run func(peerFanIns []models.PeerFanIn)) *MockPeerCommunicator_CommitFetchedUnCommittedLogs_Call {
	_c.Run(run)
	return _c
}

// FanInLocalDataFromPeers provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) FanInLocalDataFromPeers() {
	_mock.Called()
	return
}

// MockPeerCommunicator_FanInLocalDataFromPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FanInLocalDataFromPeers'
type MockPeerCommunicator_FanInLocalDataFromPeers_Call struct {
	*mock.Call
}

// FanInLocalDataFromPeers is a helper method to define mock.On call
func (_e *MockPeerCommunicator_Expecter) FanInLocalDataFromPeers() *MockPeerCommunicator_FanInLocalDataFromPeers_Call {
	return &MockPeerCommunicator_FanInLocalDataFromPeers_Call{Call: _e.mock.On("FanInLocalDataFromPeers")}
}

func (_c *MockPeerCommunicator_FanInLocalDataFromPeers_Call) Run(run func()) *MockPeerCommunicator_FanInLocalDataFromPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerCommunicator_FanInLocalDataFromPeers_Call) Return() *MockPeerCommunicator_FanInLocalDataFromPeers_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerCommunicator_FanInLocalDataFromPeers_Call) RunAndReturn(run func()) *MockPeerCommunicator_FanInLocalDataFromPeers_Call {
	_c.Run(run)
	return _c
}

// FanInLocalDataFromPeersSync provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) FanInLocalDataFromPeersSync() {
	_mock.Called()
	return
}

// MockPeerCommunicator_FanInLocalDataFromPeersSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FanInLocalDataFromPeersSync'
type MockPeerCommunicator_FanInLocalDataFromPeersSync_Call struct {
	*mock.Call
}

// FanInLocalDataFromPeersSync is a helper method to define mock.On call
func (_e *MockPeerCommunicator_Expecter) FanInLocalDataFromPeersSync() *MockPeerCommunicator_FanInLocalDataFromPeersSync_Call {
	return &MockPeerCommunicator_FanInLocalDataFromPeersSync_Call{Call: _e.mock.On("FanInLocalDataFromPeersSync")}
}

func (_c *MockPeerCommunicator_FanInLocalDataFromPeersSync_Call) Run(run func()) *MockPeerCommunicator_FanInLocalDataFromPeersSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerCommunicator_FanInLocalDataFromPeersSync_Call) Return() *MockPeerCommunicator_FanInLocalDataFromPeersSync_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerCommunicator_FanInLocalDataFromPeersSync_Call) RunAndReturn(run func()) *MockPeerCommunicator_FanInLocalDataFromPeersSync_Call {
	_c.Run(run)
	return _c
}

// GetPeers provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) GetPeers() []config.RaftNode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPeers")
	}

	var r0 []config.RaftNode
	if returnFunc, ok := ret.Get(0).(func() []config.RaftNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]config.RaftNode)
		}
	}
	return r0
}

// MockPeerCommunicator_GetPeers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPeers'
type MockPeerCommunicator_GetPeers_Call struct {
	*mock.Call
}

// GetPeers is a helper method to define mock.On call
func (_e *MockPeerCommunicator_Expecter) GetPeers() *MockPeerCommunicator_GetPeers_Call {
	return &MockPeerCommunicator_GetPeers_Call{Call: _e.mock.On("GetPeers")}
}

func (_c *MockPeerCommunicator_GetPeers_Call) Run(run func()) *MockPeerCommunicator_GetPeers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerCommunicator_GetPeers_Call) Return(raftNodes []config.RaftNode) *MockPeerCommunicator_GetPeers_Call {
	_c.Call.Return(raftNodes)
	return _c
}

func (_c *MockPeerCommunicator_GetPeers_Call) RunAndReturn(run func() []config.RaftNode) *MockPeerCommunicator_GetPeers_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomFanInPeerHTTPAddresses provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) GetRandomFanInPeerHTTPAddresses(excludeList map[string]bool) []string {
	ret := _mock.Called(excludeList)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomFanInPeerHTTPAddresses")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func(map[string]bool) []string); ok {
		r0 = returnFunc(excludeList)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomFanInPeerHTTPAddresses'
type MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call struct {
	*mock.Call
}

// GetRandomFanInPeerHTTPAddresses is a helper method to define mock.On call
//   - excludeList map[string]bool
func (_e *MockPeerCommunicator_Expecter) GetRandomFanInPeerHTTPAddresses(excludeList interface{}) *MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call {
	return &MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call{Call: _e.mock.On("GetRandomFanInPeerHTTPAddresses", excludeList)}
}

func (_c *MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call) Run(run func(excludeList map[string]bool)) *MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]bool
		if args[0] != nil {
			arg0 = args[0].(map[string]bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call) Return(strings []string) *MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call) RunAndReturn(run func(excludeList map[string]bool) []string) *MockPeerCommunicator_GetRandomFanInPeerHTTPAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// GetUncommittedLogs provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) GetUncommittedLogs(requestId string) {
	_mock.Called(requestId)
	return
}

// MockPeerCommunicator_GetUncommittedLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUncommittedLogs'
type MockPeerCommunicator_GetUncommittedLogs_Call struct {
	*mock.Call
}

// GetUncommittedLogs is a helper method to define mock.On call
//   - requestId string
func (_e *MockPeerCommunicator_Expecter) GetUncommittedLogs(requestId interface{}) *MockPeerCommunicator_GetUncommittedLogs_Call {
	return &MockPeerCommunicator_GetUncommittedLogs_Call{Call: _e.mock.On("GetUncommittedLogs", requestId)}
}

func (_c *MockPeerCommunicator_GetUncommittedLogs_Call) Run(run func(requestId string)) *MockPeerCommunicator_GetUncommittedLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerCommunicator_GetUncommittedLogs_Call) Return() *MockPeerCommunicator_GetUncommittedLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerCommunicator_GetUncommittedLogs_Call) RunAndReturn(run func(requestId string)) *MockPeerCommunicator_GetUncommittedLogs_Call {
	_c.Run(run)
	return _c
}

// ReturnUncommittedLogs provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) ReturnUncommittedLogs(requestId string) {
	_mock.Called(requestId)
	return
}

// MockPeerCommunicator_ReturnUncommittedLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReturnUncommittedLogs'
type MockPeerCommunicator_ReturnUncommittedLogs_Call struct {
	*mock.Call
}

// ReturnUncommittedLogs is a helper method to define mock.On call
//   - requestId string
func (_e *MockPeerCommunicator_Expecter) ReturnUncommittedLogs(requestId interface{}) *MockPeerCommunicator_ReturnUncommittedLogs_Call {
	return &MockPeerCommunicator_ReturnUncommittedLogs_Call{Call: _e.mock.On("ReturnUncommittedLogs", requestId)}
}

func (_c *MockPeerCommunicator_ReturnUncommittedLogs_Call) Run(run func(requestId string)) *MockPeerCommunicator_ReturnUncommittedLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPeerCommunicator_ReturnUncommittedLogs_Call) Return() *MockPeerCommunicator_ReturnUncommittedLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerCommunicator_ReturnUncommittedLogs_Call) RunAndReturn(run func(requestId string)) *MockPeerCommunicator_ReturnUncommittedLogs_Call {
	_c.Run(run)
	return _c
}

// SelectRandomPeersToFanIn provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) SelectRandomPeersToFanIn() []models.PeerFanIn {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SelectRandomPeersToFanIn")
	}

	var r0 []models.PeerFanIn
	if returnFunc, ok := ret.Get(0).(func() []models.PeerFanIn); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.PeerFanIn)
		}
	}
	return r0
}

// MockPeerCommunicator_SelectRandomPeersToFanIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SelectRandomPeersToFanIn'
type MockPeerCommunicator_SelectRandomPeersToFanIn_Call struct {
	*mock.Call
}

// SelectRandomPeersToFanIn is a helper method to define mock.On call
func (_e *MockPeerCommunicator_Expecter) SelectRandomPeersToFanIn() *MockPeerCommunicator_SelectRandomPeersToFanIn_Call {
	return &MockPeerCommunicator_SelectRandomPeersToFanIn_Call{Call: _e.mock.On("SelectRandomPeersToFanIn")}
}

func (_c *MockPeerCommunicator_SelectRandomPeersToFanIn_Call) Run(run func()) *MockPeerCommunicator_SelectRandomPeersToFanIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerCommunicator_SelectRandomPeersToFanIn_Call) Return(peerFanIns []models.PeerFanIn) *MockPeerCommunicator_SelectRandomPeersToFanIn_Call {
	_c.Call.Return(peerFanIns)
	return _c
}

func (_c *MockPeerCommunicator_SelectRandomPeersToFanIn_Call) RunAndReturn(run func() []models.PeerFanIn) *MockPeerCommunicator_SelectRandomPeersToFanIn_Call {
	_c.Call.Return(run)
	return _c
}

// StartJobsOnWorkerNodes provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) StartJobsOnWorkerNodes() {
	_mock.Called()
	return
}

// MockPeerCommunicator_StartJobsOnWorkerNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartJobsOnWorkerNodes'
type MockPeerCommunicator_StartJobsOnWorkerNodes_Call struct {
	*mock.Call
}

// StartJobsOnWorkerNodes is a helper method to define mock.On call
func (_e *MockPeerCommunicator_Expecter) StartJobsOnWorkerNodes() *MockPeerCommunicator_StartJobsOnWorkerNodes_Call {
	return &MockPeerCommunicator_StartJobsOnWorkerNodes_Call{Call: _e.mock.On("StartJobsOnWorkerNodes")}
}

func (_c *MockPeerCommunicator_StartJobsOnWorkerNodes_Call) Run(run func()) *MockPeerCommunicator_StartJobsOnWorkerNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerCommunicator_StartJobsOnWorkerNodes_Call) Return() *MockPeerCommunicator_StartJobsOnWorkerNodes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerCommunicator_StartJobsOnWorkerNodes_Call) RunAndReturn(run func()) *MockPeerCommunicator_StartJobsOnWorkerNodes_Call {
	_c.Run(run)
	return _c
}

// StopAllJobsOnAllWorkerNodes provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) StopAllJobsOnAllWorkerNodes() {
	_mock.Called()
	return
}

// MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAllJobsOnAllWorkerNodes'
type MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call struct {
	*mock.Call
}

// StopAllJobsOnAllWorkerNodes is a helper method to define mock.On call
func (_e *MockPeerCommunicator_Expecter) StopAllJobsOnAllWorkerNodes() *MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call {
	return &MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call{Call: _e.mock.On("StopAllJobsOnAllWorkerNodes")}
}

func (_c *MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call) Run(run func()) *MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call) Return() *MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call) RunAndReturn(run func()) *MockPeerCommunicator_StopAllJobsOnAllWorkerNodes_Call {
	_c.Run(run)
	return _c
}

// WatchPeersFromEtcd provides a mock function for the type MockPeerCommunicator
func (_mock *MockPeerCommunicator) WatchPeersFromEtcd() {
	_mock.Called()
	return
}

// MockPeerCommunicator_WatchPeersFromEtcd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchPeersFromEtcd'
type MockPeerCommunicator_WatchPeersFromEtcd_Call struct {
	*mock.Call
}

// WatchPeersFromEtcd is a helper method to define mock.On call
func (_e *MockPeerCommunicator_Expecter) WatchPeersFromEtcd() *MockPeerCommunicator_WatchPeersFromEtcd_Call {
	return &MockPeerCommunicator_WatchPeersFromEtcd_Call{Call: _e.mock.On("WatchPeersFromEtcd")}
}

func (_c *MockPeerCommunicator_WatchPeersFromEtcd_Call) Run(run func()) *MockPeerCommunicator_WatchPeersFromEtcd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPeerCommunicator_WatchPeersFromEtcd_Call) Return() *MockPeerCommunicator_WatchPeersFromEtcd_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPeerCommunicator_WatchPeersFromEtcd_Call) RunAndReturn(run func()) *MockPeerCommunicator_WatchPeersFromEtcd_Call {
	_c.Run(run)
	return _c
}
