// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package node

import (
	"context"
	"scheduler0/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockServer creates a new instance of MockServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServer {
	mock := &MockServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServer is an autogenerated mock type for the Server type
type MockServer struct {
	mock.Mock
}

type MockServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServer) EXPECT() *MockServer_Expecter {
	return &MockServer_Expecter{mock: &_m.Mock}
}

// BeginUncommittedLogsFetchRequest provides a mock function for the type MockServer
func (_mock *MockServer) BeginUncommittedLogsFetchRequest(data models.FetchRemoteData) models.String {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for BeginUncommittedLogsFetchRequest")
	}

	var r0 models.String
	if returnFunc, ok := ret.Get(0).(func(models.FetchRemoteData) models.String); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Get(0).(models.String)
	}
	return r0
}

// MockServer_BeginUncommittedLogsFetchRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginUncommittedLogsFetchRequest'
type MockServer_BeginUncommittedLogsFetchRequest_Call struct {
	*mock.Call
}

// BeginUncommittedLogsFetchRequest is a helper method to define mock.On call
//   - data models.FetchRemoteData
func (_e *MockServer_Expecter) BeginUncommittedLogsFetchRequest(data interface{}) *MockServer_BeginUncommittedLogsFetchRequest_Call {
	return &MockServer_BeginUncommittedLogsFetchRequest_Call{Call: _e.mock.On("BeginUncommittedLogsFetchRequest", data)}
}

func (_c *MockServer_BeginUncommittedLogsFetchRequest_Call) Run(run func(data models.FetchRemoteData)) *MockServer_BeginUncommittedLogsFetchRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.FetchRemoteData
		if args[0] != nil {
			arg0 = args[0].(models.FetchRemoteData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServer_BeginUncommittedLogsFetchRequest_Call) Return(stringParam models.String) *MockServer_BeginUncommittedLogsFetchRequest_Call {
	_c.Call.Return(stringParam)
	return _c
}

func (_c *MockServer_BeginUncommittedLogsFetchRequest_Call) RunAndReturn(run func(data models.FetchRemoteData) models.String) *MockServer_BeginUncommittedLogsFetchRequest_Call {
	_c.Call.Return(run)
	return _c
}

// HandelUncommittedLogsFetchRequest provides a mock function for the type MockServer
func (_mock *MockServer) HandelUncommittedLogsFetchRequest(ctx context.Context, data models.FetchRemoteData) models.AsyncTask {
	ret := _mock.Called(ctx, data)

	if len(ret) == 0 {
		panic("no return value specified for HandelUncommittedLogsFetchRequest")
	}

	var r0 models.AsyncTask
	if returnFunc, ok := ret.Get(0).(func(context.Context, models.FetchRemoteData) models.AsyncTask); ok {
		r0 = returnFunc(ctx, data)
	} else {
		r0 = ret.Get(0).(models.AsyncTask)
	}
	return r0
}

// MockServer_HandelUncommittedLogsFetchRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandelUncommittedLogsFetchRequest'
type MockServer_HandelUncommittedLogsFetchRequest_Call struct {
	*mock.Call
}

// HandelUncommittedLogsFetchRequest is a helper method to define mock.On call
//   - ctx context.Context
//   - data models.FetchRemoteData
func (_e *MockServer_Expecter) HandelUncommittedLogsFetchRequest(ctx interface{}, data interface{}) *MockServer_HandelUncommittedLogsFetchRequest_Call {
	return &MockServer_HandelUncommittedLogsFetchRequest_Call{Call: _e.mock.On("HandelUncommittedLogsFetchRequest", ctx, data)}
}

func (_c *MockServer_HandelUncommittedLogsFetchRequest_Call) Run(run func(ctx context.Context, data models.FetchRemoteData)) *MockServer_HandelUncommittedLogsFetchRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 models.FetchRemoteData
		if args[1] != nil {
			arg1 = args[1].(models.FetchRemoteData)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServer_HandelUncommittedLogsFetchRequest_Call) Return(asyncTask models.AsyncTask) *MockServer_HandelUncommittedLogsFetchRequest_Call {
	_c.Call.Return(asyncTask)
	return _c
}

func (_c *MockServer_HandelUncommittedLogsFetchRequest_Call) RunAndReturn(run func(ctx context.Context, data models.FetchRemoteData) models.AsyncTask) *MockServer_HandelUncommittedLogsFetchRequest_Call {
	_c.Call.Return(run)
	return _c
}

// SetupTCPListener provides a mock function for the type MockServer
func (_mock *MockServer) SetupTCPListener() {
	_mock.Called()
	return
}

// MockServer_SetupTCPListener_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupTCPListener'
type MockServer_SetupTCPListener_Call struct {
	*mock.Call
}

// SetupTCPListener is a helper method to define mock.On call
func (_e *MockServer_Expecter) SetupTCPListener() *MockServer_SetupTCPListener_Call {
	return &MockServer_SetupTCPListener_Call{Call: _e.mock.On("SetupTCPListener")}
}

func (_c *MockServer_SetupTCPListener_Call) Run(run func()) *MockServer_SetupTCPListener_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServer_SetupTCPListener_Call) Return() *MockServer_SetupTCPListener_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServer_SetupTCPListener_Call) RunAndReturn(run func()) *MockServer_SetupTCPListener_Call {
	_c.Run(run)
	return _c
}
