// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package feature

import (
	"scheduler0-private/pkg/models"
	"scheduler0-private/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFeatureService creates a new instance of MockFeatureService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeatureService {
	mock := &MockFeatureService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeatureService is an autogenerated mock type for the FeatureService type
type MockFeatureService struct {
	mock.Mock
}

type MockFeatureService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureService) EXPECT() *MockFeatureService_Expecter {
	return &MockFeatureService_Expecter{mock: &_m.Mock}
}

// GetFeatures provides a mock function for the type MockFeatureService
func (_mock *MockFeatureService) GetFeatures() (*[]models.Feature, *utils.GenericError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFeatures")
	}

	var r0 *[]models.Feature
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func() (*[]models.Feature, *utils.GenericError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *[]models.Feature); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Feature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *utils.GenericError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockFeatureService_GetFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeatures'
type MockFeatureService_GetFeatures_Call struct {
	*mock.Call
}

// GetFeatures is a helper method to define mock.On call
func (_e *MockFeatureService_Expecter) GetFeatures() *MockFeatureService_GetFeatures_Call {
	return &MockFeatureService_GetFeatures_Call{Call: _e.mock.On("GetFeatures")}
}

func (_c *MockFeatureService_GetFeatures_Call) Run(run func()) *MockFeatureService_GetFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFeatureService_GetFeatures_Call) Return(features *[]models.Feature, genericError *utils.GenericError) *MockFeatureService_GetFeatures_Call {
	_c.Call.Return(features, genericError)
	return _c
}

func (_c *MockFeatureService_GetFeatures_Call) RunAndReturn(run func() (*[]models.Feature, *utils.GenericError)) *MockFeatureService_GetFeatures_Call {
	_c.Call.Return(run)
	return _c
}
