// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package processor

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobProcessorService creates a new instance of MockJobProcessorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobProcessorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobProcessorService {
	mock := &MockJobProcessorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobProcessorService is an autogenerated mock type for the JobProcessorService type
type MockJobProcessorService struct {
	mock.Mock
}

type MockJobProcessorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobProcessorService) EXPECT() *MockJobProcessorService_Expecter {
	return &MockJobProcessorService_Expecter{mock: &_m.Mock}
}

// GetNodeIsLeader provides a mock function for the type MockJobProcessorService
func (_mock *MockJobProcessorService) GetNodeIsLeader() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNodeIsLeader")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockJobProcessorService_GetNodeIsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeIsLeader'
type MockJobProcessorService_GetNodeIsLeader_Call struct {
	*mock.Call
}

// GetNodeIsLeader is a helper method to define mock.On call
func (_e *MockJobProcessorService_Expecter) GetNodeIsLeader() *MockJobProcessorService_GetNodeIsLeader_Call {
	return &MockJobProcessorService_GetNodeIsLeader_Call{Call: _e.mock.On("GetNodeIsLeader")}
}

func (_c *MockJobProcessorService_GetNodeIsLeader_Call) Run(run func()) *MockJobProcessorService_GetNodeIsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobProcessorService_GetNodeIsLeader_Call) Return(b bool) *MockJobProcessorService_GetNodeIsLeader_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockJobProcessorService_GetNodeIsLeader_Call) RunAndReturn(run func() bool) *MockJobProcessorService_GetNodeIsLeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetSingleNodeMode provides a mock function for the type MockJobProcessorService
func (_mock *MockJobProcessorService) GetSingleNodeMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSingleNodeMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockJobProcessorService_GetSingleNodeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSingleNodeMode'
type MockJobProcessorService_GetSingleNodeMode_Call struct {
	*mock.Call
}

// GetSingleNodeMode is a helper method to define mock.On call
func (_e *MockJobProcessorService_Expecter) GetSingleNodeMode() *MockJobProcessorService_GetSingleNodeMode_Call {
	return &MockJobProcessorService_GetSingleNodeMode_Call{Call: _e.mock.On("GetSingleNodeMode")}
}

func (_c *MockJobProcessorService_GetSingleNodeMode_Call) Run(run func()) *MockJobProcessorService_GetSingleNodeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobProcessorService_GetSingleNodeMode_Call) Return(b bool) *MockJobProcessorService_GetSingleNodeMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockJobProcessorService_GetSingleNodeMode_Call) RunAndReturn(run func() bool) *MockJobProcessorService_GetSingleNodeMode_Call {
	_c.Call.Return(run)
	return _c
}

// RecoverJobs provides a mock function for the type MockJobProcessorService
func (_mock *MockJobProcessorService) RecoverJobs() {
	_mock.Called()
	return
}

// MockJobProcessorService_RecoverJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecoverJobs'
type MockJobProcessorService_RecoverJobs_Call struct {
	*mock.Call
}

// RecoverJobs is a helper method to define mock.On call
func (_e *MockJobProcessorService_Expecter) RecoverJobs() *MockJobProcessorService_RecoverJobs_Call {
	return &MockJobProcessorService_RecoverJobs_Call{Call: _e.mock.On("RecoverJobs")}
}

func (_c *MockJobProcessorService_RecoverJobs_Call) Run(run func()) *MockJobProcessorService_RecoverJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobProcessorService_RecoverJobs_Call) Return() *MockJobProcessorService_RecoverJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobProcessorService_RecoverJobs_Call) RunAndReturn(run func()) *MockJobProcessorService_RecoverJobs_Call {
	_c.Run(run)
	return _c
}

// SetNodeIsLeader provides a mock function for the type MockJobProcessorService
func (_mock *MockJobProcessorService) SetNodeIsLeader(nodeIsLeader bool) {
	_mock.Called(nodeIsLeader)
	return
}

// MockJobProcessorService_SetNodeIsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodeIsLeader'
type MockJobProcessorService_SetNodeIsLeader_Call struct {
	*mock.Call
}

// SetNodeIsLeader is a helper method to define mock.On call
//   - nodeIsLeader bool
func (_e *MockJobProcessorService_Expecter) SetNodeIsLeader(nodeIsLeader interface{}) *MockJobProcessorService_SetNodeIsLeader_Call {
	return &MockJobProcessorService_SetNodeIsLeader_Call{Call: _e.mock.On("SetNodeIsLeader", nodeIsLeader)}
}

func (_c *MockJobProcessorService_SetNodeIsLeader_Call) Run(run func(nodeIsLeader bool)) *MockJobProcessorService_SetNodeIsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobProcessorService_SetNodeIsLeader_Call) Return() *MockJobProcessorService_SetNodeIsLeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobProcessorService_SetNodeIsLeader_Call) RunAndReturn(run func(nodeIsLeader bool)) *MockJobProcessorService_SetNodeIsLeader_Call {
	_c.Run(run)
	return _c
}

// SetSingleNodeMode provides a mock function for the type MockJobProcessorService
func (_mock *MockJobProcessorService) SetSingleNodeMode(singleNodeMode bool) {
	_mock.Called(singleNodeMode)
	return
}

// MockJobProcessorService_SetSingleNodeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSingleNodeMode'
type MockJobProcessorService_SetSingleNodeMode_Call struct {
	*mock.Call
}

// SetSingleNodeMode is a helper method to define mock.On call
//   - singleNodeMode bool
func (_e *MockJobProcessorService_Expecter) SetSingleNodeMode(singleNodeMode interface{}) *MockJobProcessorService_SetSingleNodeMode_Call {
	return &MockJobProcessorService_SetSingleNodeMode_Call{Call: _e.mock.On("SetSingleNodeMode", singleNodeMode)}
}

func (_c *MockJobProcessorService_SetSingleNodeMode_Call) Run(run func(singleNodeMode bool)) *MockJobProcessorService_SetSingleNodeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobProcessorService_SetSingleNodeMode_Call) Return() *MockJobProcessorService_SetSingleNodeMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobProcessorService_SetSingleNodeMode_Call) RunAndReturn(run func(singleNodeMode bool)) *MockJobProcessorService_SetSingleNodeMode_Call {
	_c.Run(run)
	return _c
}

// StartJobs provides a mock function for the type MockJobProcessorService
func (_mock *MockJobProcessorService) StartJobs() {
	_mock.Called()
	return
}

// MockJobProcessorService_StartJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartJobs'
type MockJobProcessorService_StartJobs_Call struct {
	*mock.Call
}

// StartJobs is a helper method to define mock.On call
func (_e *MockJobProcessorService_Expecter) StartJobs() *MockJobProcessorService_StartJobs_Call {
	return &MockJobProcessorService_StartJobs_Call{Call: _e.mock.On("StartJobs")}
}

func (_c *MockJobProcessorService_StartJobs_Call) Run(run func()) *MockJobProcessorService_StartJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobProcessorService_StartJobs_Call) Return() *MockJobProcessorService_StartJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobProcessorService_StartJobs_Call) RunAndReturn(run func()) *MockJobProcessorService_StartJobs_Call {
	_c.Run(run)
	return _c
}
