// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package shared_repo

import (
	"scheduler0/pkg/db"
	"scheduler0/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSharedRepo creates a new instance of MockSharedRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSharedRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSharedRepo {
	mock := &MockSharedRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSharedRepo is an autogenerated mock type for the SharedRepo type
type MockSharedRepo struct {
	mock.Mock
}

type MockSharedRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSharedRepo) EXPECT() *MockSharedRepo_Expecter {
	return &MockSharedRepo_Expecter{mock: &_m.Mock}
}

// DeleteAsyncTasksLogs provides a mock function for the type MockSharedRepo
func (_mock *MockSharedRepo) DeleteAsyncTasksLogs(db1 db.DataStore, committed bool, asyncTasks []models.AsyncTask) error {
	ret := _mock.Called(db1, committed, asyncTasks)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAsyncTasksLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(db.DataStore, bool, []models.AsyncTask) error); ok {
		r0 = returnFunc(db1, committed, asyncTasks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSharedRepo_DeleteAsyncTasksLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAsyncTasksLogs'
type MockSharedRepo_DeleteAsyncTasksLogs_Call struct {
	*mock.Call
}

// DeleteAsyncTasksLogs is a helper method to define mock.On call
//   - db1 db.DataStore
//   - committed bool
//   - asyncTasks []models.AsyncTask
func (_e *MockSharedRepo_Expecter) DeleteAsyncTasksLogs(db1 interface{}, committed interface{}, asyncTasks interface{}) *MockSharedRepo_DeleteAsyncTasksLogs_Call {
	return &MockSharedRepo_DeleteAsyncTasksLogs_Call{Call: _e.mock.On("DeleteAsyncTasksLogs", db1, committed, asyncTasks)}
}

func (_c *MockSharedRepo_DeleteAsyncTasksLogs_Call) Run(run func(db1 db.DataStore, committed bool, asyncTasks []models.AsyncTask)) *MockSharedRepo_DeleteAsyncTasksLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 db.DataStore
		if args[0] != nil {
			arg0 = args[0].(db.DataStore)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 []models.AsyncTask
		if args[2] != nil {
			arg2 = args[2].([]models.AsyncTask)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSharedRepo_DeleteAsyncTasksLogs_Call) Return(err error) *MockSharedRepo_DeleteAsyncTasksLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSharedRepo_DeleteAsyncTasksLogs_Call) RunAndReturn(run func(db1 db.DataStore, committed bool, asyncTasks []models.AsyncTask) error) *MockSharedRepo_DeleteAsyncTasksLogs_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteExecutionLogs provides a mock function for the type MockSharedRepo
func (_mock *MockSharedRepo) DeleteExecutionLogs(db1 db.DataStore, committed bool, jobExecutionLogs []models.JobExecutionLog) error {
	ret := _mock.Called(db1, committed, jobExecutionLogs)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExecutionLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(db.DataStore, bool, []models.JobExecutionLog) error); ok {
		r0 = returnFunc(db1, committed, jobExecutionLogs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSharedRepo_DeleteExecutionLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExecutionLogs'
type MockSharedRepo_DeleteExecutionLogs_Call struct {
	*mock.Call
}

// DeleteExecutionLogs is a helper method to define mock.On call
//   - db1 db.DataStore
//   - committed bool
//   - jobExecutionLogs []models.JobExecutionLog
func (_e *MockSharedRepo_Expecter) DeleteExecutionLogs(db1 interface{}, committed interface{}, jobExecutionLogs interface{}) *MockSharedRepo_DeleteExecutionLogs_Call {
	return &MockSharedRepo_DeleteExecutionLogs_Call{Call: _e.mock.On("DeleteExecutionLogs", db1, committed, jobExecutionLogs)}
}

func (_c *MockSharedRepo_DeleteExecutionLogs_Call) Run(run func(db1 db.DataStore, committed bool, jobExecutionLogs []models.JobExecutionLog)) *MockSharedRepo_DeleteExecutionLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 db.DataStore
		if args[0] != nil {
			arg0 = args[0].(db.DataStore)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 []models.JobExecutionLog
		if args[2] != nil {
			arg2 = args[2].([]models.JobExecutionLog)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSharedRepo_DeleteExecutionLogs_Call) Return(err error) *MockSharedRepo_DeleteExecutionLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSharedRepo_DeleteExecutionLogs_Call) RunAndReturn(run func(db1 db.DataStore, committed bool, jobExecutionLogs []models.JobExecutionLog) error) *MockSharedRepo_DeleteExecutionLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetAsyncTasksLogs provides a mock function for the type MockSharedRepo
func (_mock *MockSharedRepo) GetAsyncTasksLogs(db1 db.DataStore, committed bool) ([]models.AsyncTask, error) {
	ret := _mock.Called(db1, committed)

	if len(ret) == 0 {
		panic("no return value specified for GetAsyncTasksLogs")
	}

	var r0 []models.AsyncTask
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(db.DataStore, bool) ([]models.AsyncTask, error)); ok {
		return returnFunc(db1, committed)
	}
	if returnFunc, ok := ret.Get(0).(func(db.DataStore, bool) []models.AsyncTask); ok {
		r0 = returnFunc(db1, committed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AsyncTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(db.DataStore, bool) error); ok {
		r1 = returnFunc(db1, committed)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSharedRepo_GetAsyncTasksLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAsyncTasksLogs'
type MockSharedRepo_GetAsyncTasksLogs_Call struct {
	*mock.Call
}

// GetAsyncTasksLogs is a helper method to define mock.On call
//   - db1 db.DataStore
//   - committed bool
func (_e *MockSharedRepo_Expecter) GetAsyncTasksLogs(db1 interface{}, committed interface{}) *MockSharedRepo_GetAsyncTasksLogs_Call {
	return &MockSharedRepo_GetAsyncTasksLogs_Call{Call: _e.mock.On("GetAsyncTasksLogs", db1, committed)}
}

func (_c *MockSharedRepo_GetAsyncTasksLogs_Call) Run(run func(db1 db.DataStore, committed bool)) *MockSharedRepo_GetAsyncTasksLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 db.DataStore
		if args[0] != nil {
			arg0 = args[0].(db.DataStore)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSharedRepo_GetAsyncTasksLogs_Call) Return(asyncTasks []models.AsyncTask, err error) *MockSharedRepo_GetAsyncTasksLogs_Call {
	_c.Call.Return(asyncTasks, err)
	return _c
}

func (_c *MockSharedRepo_GetAsyncTasksLogs_Call) RunAndReturn(run func(db1 db.DataStore, committed bool) ([]models.AsyncTask, error)) *MockSharedRepo_GetAsyncTasksLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionLogs provides a mock function for the type MockSharedRepo
func (_mock *MockSharedRepo) GetExecutionLogs(db1 db.DataStore, committed bool) ([]models.JobExecutionLog, error) {
	ret := _mock.Called(db1, committed)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionLogs")
	}

	var r0 []models.JobExecutionLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(db.DataStore, bool) ([]models.JobExecutionLog, error)); ok {
		return returnFunc(db1, committed)
	}
	if returnFunc, ok := ret.Get(0).(func(db.DataStore, bool) []models.JobExecutionLog); ok {
		r0 = returnFunc(db1, committed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobExecutionLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(db.DataStore, bool) error); ok {
		r1 = returnFunc(db1, committed)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSharedRepo_GetExecutionLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionLogs'
type MockSharedRepo_GetExecutionLogs_Call struct {
	*mock.Call
}

// GetExecutionLogs is a helper method to define mock.On call
//   - db1 db.DataStore
//   - committed bool
func (_e *MockSharedRepo_Expecter) GetExecutionLogs(db1 interface{}, committed interface{}) *MockSharedRepo_GetExecutionLogs_Call {
	return &MockSharedRepo_GetExecutionLogs_Call{Call: _e.mock.On("GetExecutionLogs", db1, committed)}
}

func (_c *MockSharedRepo_GetExecutionLogs_Call) Run(run func(db1 db.DataStore, committed bool)) *MockSharedRepo_GetExecutionLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 db.DataStore
		if args[0] != nil {
			arg0 = args[0].(db.DataStore)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSharedRepo_GetExecutionLogs_Call) Return(jobExecutionLogs []models.JobExecutionLog, err error) *MockSharedRepo_GetExecutionLogs_Call {
	_c.Call.Return(jobExecutionLogs, err)
	return _c
}

func (_c *MockSharedRepo_GetExecutionLogs_Call) RunAndReturn(run func(db1 db.DataStore, committed bool) ([]models.JobExecutionLog, error)) *MockSharedRepo_GetExecutionLogs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertAsyncTasksLogs provides a mock function for the type MockSharedRepo
func (_mock *MockSharedRepo) InsertAsyncTasksLogs(db1 db.DataStore, committed bool, asyncTasks []models.AsyncTask) error {
	ret := _mock.Called(db1, committed, asyncTasks)

	if len(ret) == 0 {
		panic("no return value specified for InsertAsyncTasksLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(db.DataStore, bool, []models.AsyncTask) error); ok {
		r0 = returnFunc(db1, committed, asyncTasks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSharedRepo_InsertAsyncTasksLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertAsyncTasksLogs'
type MockSharedRepo_InsertAsyncTasksLogs_Call struct {
	*mock.Call
}

// InsertAsyncTasksLogs is a helper method to define mock.On call
//   - db1 db.DataStore
//   - committed bool
//   - asyncTasks []models.AsyncTask
func (_e *MockSharedRepo_Expecter) InsertAsyncTasksLogs(db1 interface{}, committed interface{}, asyncTasks interface{}) *MockSharedRepo_InsertAsyncTasksLogs_Call {
	return &MockSharedRepo_InsertAsyncTasksLogs_Call{Call: _e.mock.On("InsertAsyncTasksLogs", db1, committed, asyncTasks)}
}

func (_c *MockSharedRepo_InsertAsyncTasksLogs_Call) Run(run func(db1 db.DataStore, committed bool, asyncTasks []models.AsyncTask)) *MockSharedRepo_InsertAsyncTasksLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 db.DataStore
		if args[0] != nil {
			arg0 = args[0].(db.DataStore)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 []models.AsyncTask
		if args[2] != nil {
			arg2 = args[2].([]models.AsyncTask)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSharedRepo_InsertAsyncTasksLogs_Call) Return(err error) *MockSharedRepo_InsertAsyncTasksLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSharedRepo_InsertAsyncTasksLogs_Call) RunAndReturn(run func(db1 db.DataStore, committed bool, asyncTasks []models.AsyncTask) error) *MockSharedRepo_InsertAsyncTasksLogs_Call {
	_c.Call.Return(run)
	return _c
}

// InsertExecutionLogs provides a mock function for the type MockSharedRepo
func (_mock *MockSharedRepo) InsertExecutionLogs(db1 db.DataStore, committed bool, jobExecutionLogs []models.JobExecutionLog) error {
	ret := _mock.Called(db1, committed, jobExecutionLogs)

	if len(ret) == 0 {
		panic("no return value specified for InsertExecutionLogs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(db.DataStore, bool, []models.JobExecutionLog) error); ok {
		r0 = returnFunc(db1, committed, jobExecutionLogs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSharedRepo_InsertExecutionLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertExecutionLogs'
type MockSharedRepo_InsertExecutionLogs_Call struct {
	*mock.Call
}

// InsertExecutionLogs is a helper method to define mock.On call
//   - db1 db.DataStore
//   - committed bool
//   - jobExecutionLogs []models.JobExecutionLog
func (_e *MockSharedRepo_Expecter) InsertExecutionLogs(db1 interface{}, committed interface{}, jobExecutionLogs interface{}) *MockSharedRepo_InsertExecutionLogs_Call {
	return &MockSharedRepo_InsertExecutionLogs_Call{Call: _e.mock.On("InsertExecutionLogs", db1, committed, jobExecutionLogs)}
}

func (_c *MockSharedRepo_InsertExecutionLogs_Call) Run(run func(db1 db.DataStore, committed bool, jobExecutionLogs []models.JobExecutionLog)) *MockSharedRepo_InsertExecutionLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 db.DataStore
		if args[0] != nil {
			arg0 = args[0].(db.DataStore)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 []models.JobExecutionLog
		if args[2] != nil {
			arg2 = args[2].([]models.JobExecutionLog)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSharedRepo_InsertExecutionLogs_Call) Return(err error) *MockSharedRepo_InsertExecutionLogs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSharedRepo_InsertExecutionLogs_Call) RunAndReturn(run func(db1 db.DataStore, committed bool, jobExecutionLogs []models.JobExecutionLog) error) *MockSharedRepo_InsertExecutionLogs_Call {
	_c.Call.Return(run)
	return _c
}
