// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: account_exhaustion.proto

package protobuffs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountExhaustionPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUsername  string                 `protobuf:"bytes,1,opt,name=auth_username,json=authUsername,proto3" json:"auth_username,omitempty"`
	AuthPassword  string                 `protobuf:"bytes,2,opt,name=auth_password,json=authPassword,proto3" json:"auth_password,omitempty"`
	AccountId     uint64                 `protobuf:"varint,3,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountExhaustionPayload) Reset() {
	*x = AccountExhaustionPayload{}
	mi := &file_account_exhaustion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountExhaustionPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountExhaustionPayload) ProtoMessage() {}

func (x *AccountExhaustionPayload) ProtoReflect() protoreflect.Message {
	mi := &file_account_exhaustion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountExhaustionPayload.ProtoReflect.Descriptor instead.
func (*AccountExhaustionPayload) Descriptor() ([]byte, []int) {
	return file_account_exhaustion_proto_rawDescGZIP(), []int{0}
}

func (x *AccountExhaustionPayload) GetAuthUsername() string {
	if x != nil {
		return x.AuthUsername
	}
	return ""
}

func (x *AccountExhaustionPayload) GetAuthPassword() string {
	if x != nil {
		return x.AuthPassword
	}
	return ""
}

func (x *AccountExhaustionPayload) GetAccountId() uint64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

var File_account_exhaustion_proto protoreflect.FileDescriptor

const file_account_exhaustion_proto_rawDesc = "" +
	"\n" +
	"\x18account_exhaustion.proto\x12\n" +
	"protobuffs\"\x83\x01\n" +
	"\x18AccountExhaustionPayload\x12#\n" +
	"\rauth_username\x18\x01 \x01(\tR\fauthUsername\x12#\n" +
	"\rauth_password\x18\x02 \x01(\tR\fauthPassword\x12\x1d\n" +
	"\n" +
	"account_id\x18\x03 \x01(\x04R\taccountIdb\x06proto3"

var (
	file_account_exhaustion_proto_rawDescOnce sync.Once
	file_account_exhaustion_proto_rawDescData []byte
)

func file_account_exhaustion_proto_rawDescGZIP() []byte {
	file_account_exhaustion_proto_rawDescOnce.Do(func() {
		file_account_exhaustion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_exhaustion_proto_rawDesc), len(file_account_exhaustion_proto_rawDesc)))
	})
	return file_account_exhaustion_proto_rawDescData
}

var file_account_exhaustion_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_account_exhaustion_proto_goTypes = []any{
	(*AccountExhaustionPayload)(nil), // 0: protobuffs.AccountExhaustionPayload
}
var file_account_exhaustion_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_exhaustion_proto_init() }
func file_account_exhaustion_proto_init() {
	if File_account_exhaustion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_exhaustion_proto_rawDesc), len(file_account_exhaustion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_exhaustion_proto_goTypes,
		DependencyIndexes: file_account_exhaustion_proto_depIdxs,
		MessageInfos:      file_account_exhaustion_proto_msgTypes,
	}.Build()
	File_account_exhaustion_proto = out.File
	file_account_exhaustion_proto_goTypes = nil
	file_account_exhaustion_proto_depIdxs = nil
}
