// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: fetch_remote_data_payload.proto

package protobuffs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRemoteDataPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Phase        string `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	AuthUsername string `protobuf:"bytes,2,opt,name=auth_username,json=authUsername,proto3" json:"auth_username,omitempty"`
	AuthPassword string `protobuf:"bytes,3,opt,name=auth_password,json=authPassword,proto3" json:"auth_password,omitempty"`
	RequestId    string `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
}

func (x *FetchRemoteDataPayload) Reset() {
	*x = FetchRemoteDataPayload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_fetch_remote_data_payload_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchRemoteDataPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRemoteDataPayload) ProtoMessage() {}

func (x *FetchRemoteDataPayload) ProtoReflect() protoreflect.Message {
	mi := &file_fetch_remote_data_payload_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRemoteDataPayload.ProtoReflect.Descriptor instead.
func (*FetchRemoteDataPayload) Descriptor() ([]byte, []int) {
	return file_fetch_remote_data_payload_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRemoteDataPayload) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *FetchRemoteDataPayload) GetAuthUsername() string {
	if x != nil {
		return x.AuthUsername
	}
	return ""
}

func (x *FetchRemoteDataPayload) GetAuthPassword() string {
	if x != nil {
		return x.AuthPassword
	}
	return ""
}

func (x *FetchRemoteDataPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

var File_fetch_remote_data_payload_proto protoreflect.FileDescriptor

var file_fetch_remote_data_payload_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x19, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x97, 0x01, 0x0a,
	0x16, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x61, 0x73, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x50,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_fetch_remote_data_payload_proto_rawDescOnce sync.Once
	file_fetch_remote_data_payload_proto_rawDescData = file_fetch_remote_data_payload_proto_rawDesc
)

func file_fetch_remote_data_payload_proto_rawDescGZIP() []byte {
	file_fetch_remote_data_payload_proto_rawDescOnce.Do(func() {
		file_fetch_remote_data_payload_proto_rawDescData = protoimpl.X.CompressGZIP(file_fetch_remote_data_payload_proto_rawDescData)
	})
	return file_fetch_remote_data_payload_proto_rawDescData
}

var file_fetch_remote_data_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_fetch_remote_data_payload_proto_goTypes = []interface{}{
	(*FetchRemoteDataPayload)(nil), // 0: fetch_remote_data_payload.FetchRemoteDataPayload
}
var file_fetch_remote_data_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fetch_remote_data_payload_proto_init() }
func file_fetch_remote_data_payload_proto_init() {
	if File_fetch_remote_data_payload_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_fetch_remote_data_payload_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchRemoteDataPayload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_fetch_remote_data_payload_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fetch_remote_data_payload_proto_goTypes,
		DependencyIndexes: file_fetch_remote_data_payload_proto_depIdxs,
		MessageInfos:      file_fetch_remote_data_payload_proto_msgTypes,
	}.Build()
	File_fetch_remote_data_payload_proto = out.File
	file_fetch_remote_data_payload_proto_rawDesc = nil
	file_fetch_remote_data_payload_proto_goTypes = nil
	file_fetch_remote_data_payload_proto_depIdxs = nil
}
