// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: job_update_request.proto

package protobuffs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobUpdateRequestPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUsername  string                 `protobuf:"bytes,1,opt,name=auth_username,json=authUsername,proto3" json:"auth_username,omitempty"`
	AuthPassword  string                 `protobuf:"bytes,2,opt,name=auth_password,json=authPassword,proto3" json:"auth_password,omitempty"`
	JobData       []byte                 `protobuf:"bytes,3,opt,name=job_data,json=jobData,proto3" json:"job_data,omitempty"` // JSON-encoded Job
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobUpdateRequestPayload) Reset() {
	*x = JobUpdateRequestPayload{}
	mi := &file_job_update_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobUpdateRequestPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobUpdateRequestPayload) ProtoMessage() {}

func (x *JobUpdateRequestPayload) ProtoReflect() protoreflect.Message {
	mi := &file_job_update_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobUpdateRequestPayload.ProtoReflect.Descriptor instead.
func (*JobUpdateRequestPayload) Descriptor() ([]byte, []int) {
	return file_job_update_request_proto_rawDescGZIP(), []int{0}
}

func (x *JobUpdateRequestPayload) GetAuthUsername() string {
	if x != nil {
		return x.AuthUsername
	}
	return ""
}

func (x *JobUpdateRequestPayload) GetAuthPassword() string {
	if x != nil {
		return x.AuthPassword
	}
	return ""
}

func (x *JobUpdateRequestPayload) GetJobData() []byte {
	if x != nil {
		return x.JobData
	}
	return nil
}

var File_job_update_request_proto protoreflect.FileDescriptor

const file_job_update_request_proto_rawDesc = "" +
	"\n" +
	"\x18job_update_request.proto\x12\n" +
	"protobuffs\"~\n" +
	"\x17JobUpdateRequestPayload\x12#\n" +
	"\rauth_username\x18\x01 \x01(\tR\fauthUsername\x12#\n" +
	"\rauth_password\x18\x02 \x01(\tR\fauthPassword\x12\x19\n" +
	"\bjob_data\x18\x03 \x01(\fR\ajobDatab\x06proto3"

var (
	file_job_update_request_proto_rawDescOnce sync.Once
	file_job_update_request_proto_rawDescData []byte
)

func file_job_update_request_proto_rawDescGZIP() []byte {
	file_job_update_request_proto_rawDescOnce.Do(func() {
		file_job_update_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_update_request_proto_rawDesc), len(file_job_update_request_proto_rawDesc)))
	})
	return file_job_update_request_proto_rawDescData
}

var file_job_update_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_job_update_request_proto_goTypes = []any{
	(*JobUpdateRequestPayload)(nil), // 0: protobuffs.JobUpdateRequestPayload
}
var file_job_update_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_job_update_request_proto_init() }
func file_job_update_request_proto_init() {
	if File_job_update_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_update_request_proto_rawDesc), len(file_job_update_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_job_update_request_proto_goTypes,
		DependencyIndexes: file_job_update_request_proto_depIdxs,
		MessageInfos:      file_job_update_request_proto_msgTypes,
	}.Build()
	File_job_update_request_proto = out.File
	file_job_update_request_proto_goTypes = nil
	file_job_update_request_proto_depIdxs = nil
}
