// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: local_quota_response.proto

package protobuffs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocalQuotaResponsePayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of account_id -> remaining_count
	AccountAllocations map[uint64]uint64 `protobuf:"bytes,1,rep,name=account_allocations,json=accountAllocations,proto3" json:"account_allocations,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LocalQuotaResponsePayload) Reset() {
	*x = LocalQuotaResponsePayload{}
	mi := &file_local_quota_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocalQuotaResponsePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocalQuotaResponsePayload) ProtoMessage() {}

func (x *LocalQuotaResponsePayload) ProtoReflect() protoreflect.Message {
	mi := &file_local_quota_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocalQuotaResponsePayload.ProtoReflect.Descriptor instead.
func (*LocalQuotaResponsePayload) Descriptor() ([]byte, []int) {
	return file_local_quota_response_proto_rawDescGZIP(), []int{0}
}

func (x *LocalQuotaResponsePayload) GetAccountAllocations() map[uint64]uint64 {
	if x != nil {
		return x.AccountAllocations
	}
	return nil
}

var File_local_quota_response_proto protoreflect.FileDescriptor

const file_local_quota_response_proto_rawDesc = "" +
	"\n" +
	"\x1alocal_quota_response.proto\x12\n" +
	"protobuffs\"\xd2\x01\n" +
	"\x19LocalQuotaResponsePayload\x12n\n" +
	"\x13account_allocations\x18\x01 \x03(\v2=.protobuffs.LocalQuotaResponsePayload.AccountAllocationsEntryR\x12accountAllocations\x1aE\n" +
	"\x17AccountAllocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01b\x06proto3"

var (
	file_local_quota_response_proto_rawDescOnce sync.Once
	file_local_quota_response_proto_rawDescData []byte
)

func file_local_quota_response_proto_rawDescGZIP() []byte {
	file_local_quota_response_proto_rawDescOnce.Do(func() {
		file_local_quota_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_local_quota_response_proto_rawDesc), len(file_local_quota_response_proto_rawDesc)))
	})
	return file_local_quota_response_proto_rawDescData
}

var file_local_quota_response_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_local_quota_response_proto_goTypes = []any{
	(*LocalQuotaResponsePayload)(nil), // 0: protobuffs.LocalQuotaResponsePayload
	nil,                               // 1: protobuffs.LocalQuotaResponsePayload.AccountAllocationsEntry
}
var file_local_quota_response_proto_depIdxs = []int32{
	1, // 0: protobuffs.LocalQuotaResponsePayload.account_allocations:type_name -> protobuffs.LocalQuotaResponsePayload.AccountAllocationsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_local_quota_response_proto_init() }
func file_local_quota_response_proto_init() {
	if File_local_quota_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_local_quota_response_proto_rawDesc), len(file_local_quota_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_local_quota_response_proto_goTypes,
		DependencyIndexes: file_local_quota_response_proto_depIdxs,
		MessageInfos:      file_local_quota_response_proto_msgTypes,
	}.Build()
	File_local_quota_response_proto = out.File
	file_local_quota_response_proto_goTypes = nil
	file_local_quota_response_proto_depIdxs = nil
}
