// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: node_auth.proto

package protobuffs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeAuth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthUsername string `protobuf:"bytes,1,opt,name=auth_username,json=authUsername,proto3" json:"auth_username,omitempty"`
	AuthPassword string `protobuf:"bytes,2,opt,name=auth_password,json=authPassword,proto3" json:"auth_password,omitempty"`
}

func (x *NodeAuth) Reset() {
	*x = NodeAuth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_node_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAuth) ProtoMessage() {}

func (x *NodeAuth) ProtoReflect() protoreflect.Message {
	mi := &file_node_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAuth.ProtoReflect.Descriptor instead.
func (*NodeAuth) Descriptor() ([]byte, []int) {
	return file_node_auth_proto_rawDescGZIP(), []int{0}
}

func (x *NodeAuth) GetAuthUsername() string {
	if x != nil {
		return x.AuthUsername
	}
	return ""
}

func (x *NodeAuth) GetAuthPassword() string {
	if x != nil {
		return x.AuthPassword
	}
	return ""
}

var File_node_auth_proto protoreflect.FileDescriptor

var file_node_auth_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x22, 0x54, 0x0a, 0x08,
	0x4e, 0x6f, 0x64, 0x65, 0x41, 0x75, 0x74, 0x68, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x75, 0x74, 0x68,
	0x5f, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x61, 0x75, 0x74, 0x68, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a,
	0x0d, 0x61, 0x75, 0x74, 0x68, 0x5f, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x75, 0x74, 0x68, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_node_auth_proto_rawDescOnce sync.Once
	file_node_auth_proto_rawDescData = file_node_auth_proto_rawDesc
)

func file_node_auth_proto_rawDescGZIP() []byte {
	file_node_auth_proto_rawDescOnce.Do(func() {
		file_node_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_node_auth_proto_rawDescData)
	})
	return file_node_auth_proto_rawDescData
}

var file_node_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_node_auth_proto_goTypes = []interface{}{
	(*NodeAuth)(nil), // 0: node_auth.NodeAuth
}
var file_node_auth_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_node_auth_proto_init() }
func file_node_auth_proto_init() {
	if File_node_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_node_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeAuth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_node_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_node_auth_proto_goTypes,
		DependencyIndexes: file_node_auth_proto_depIdxs,
		MessageInfos:      file_node_auth_proto_msgTypes,
	}.Build()
	File_node_auth_proto = out.File
	file_node_auth_proto_rawDesc = nil
	file_node_auth_proto_goTypes = nil
	file_node_auth_proto_depIdxs = nil
}
