// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: quota_allocation.proto

package protobuffs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuotaAllocationPayload struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	AuthUsername string                 `protobuf:"bytes,1,opt,name=auth_username,json=authUsername,proto3" json:"auth_username,omitempty"`
	AuthPassword string                 `protobuf:"bytes,2,opt,name=auth_password,json=authPassword,proto3" json:"auth_password,omitempty"`
	// Map of account_id -> allocated_count
	AccountAllocations map[uint64]uint64 `protobuf:"bytes,3,rep,name=account_allocations,json=accountAllocations,proto3" json:"account_allocations,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuotaAllocationPayload) Reset() {
	*x = QuotaAllocationPayload{}
	mi := &file_quota_allocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuotaAllocationPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuotaAllocationPayload) ProtoMessage() {}

func (x *QuotaAllocationPayload) ProtoReflect() protoreflect.Message {
	mi := &file_quota_allocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuotaAllocationPayload.ProtoReflect.Descriptor instead.
func (*QuotaAllocationPayload) Descriptor() ([]byte, []int) {
	return file_quota_allocation_proto_rawDescGZIP(), []int{0}
}

func (x *QuotaAllocationPayload) GetAuthUsername() string {
	if x != nil {
		return x.AuthUsername
	}
	return ""
}

func (x *QuotaAllocationPayload) GetAuthPassword() string {
	if x != nil {
		return x.AuthPassword
	}
	return ""
}

func (x *QuotaAllocationPayload) GetAccountAllocations() map[uint64]uint64 {
	if x != nil {
		return x.AccountAllocations
	}
	return nil
}

var File_quota_allocation_proto protoreflect.FileDescriptor

const file_quota_allocation_proto_rawDesc = "" +
	"\n" +
	"\x16quota_allocation.proto\x12\n" +
	"protobuffs\"\x96\x02\n" +
	"\x16QuotaAllocationPayload\x12#\n" +
	"\rauth_username\x18\x01 \x01(\tR\fauthUsername\x12#\n" +
	"\rauth_password\x18\x02 \x01(\tR\fauthPassword\x12k\n" +
	"\x13account_allocations\x18\x03 \x03(\v2:.protobuffs.QuotaAllocationPayload.AccountAllocationsEntryR\x12accountAllocations\x1aE\n" +
	"\x17AccountAllocationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01b\x06proto3"

var (
	file_quota_allocation_proto_rawDescOnce sync.Once
	file_quota_allocation_proto_rawDescData []byte
)

func file_quota_allocation_proto_rawDescGZIP() []byte {
	file_quota_allocation_proto_rawDescOnce.Do(func() {
		file_quota_allocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_quota_allocation_proto_rawDesc), len(file_quota_allocation_proto_rawDesc)))
	})
	return file_quota_allocation_proto_rawDescData
}

var file_quota_allocation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_quota_allocation_proto_goTypes = []any{
	(*QuotaAllocationPayload)(nil), // 0: protobuffs.QuotaAllocationPayload
	nil,                            // 1: protobuffs.QuotaAllocationPayload.AccountAllocationsEntry
}
var file_quota_allocation_proto_depIdxs = []int32{
	1, // 0: protobuffs.QuotaAllocationPayload.account_allocations:type_name -> protobuffs.QuotaAllocationPayload.AccountAllocationsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_quota_allocation_proto_init() }
func file_quota_allocation_proto_init() {
	if File_quota_allocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_quota_allocation_proto_rawDesc), len(file_quota_allocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quota_allocation_proto_goTypes,
		DependencyIndexes: file_quota_allocation_proto_depIdxs,
		MessageInfos:      file_quota_allocation_proto_msgTypes,
	}.Build()
	File_quota_allocation_proto = out.File
	file_quota_allocation_proto_goTypes = nil
	file_quota_allocation_proto_depIdxs = nil
}
