// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package job_queue

import (
	"scheduler0/pkg/models"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJobQueuesRepo creates a new instance of MockJobQueuesRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobQueuesRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobQueuesRepo {
	mock := &MockJobQueuesRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobQueuesRepo is an autogenerated mock type for the JobQueuesRepo type
type MockJobQueuesRepo struct {
	mock.Mock
}

type MockJobQueuesRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobQueuesRepo) EXPECT() *MockJobQueuesRepo_Expecter {
	return &MockJobQueuesRepo_Expecter{mock: &_m.Mock}
}

// GetAllJobQueueVersions provides a mock function for the type MockJobQueuesRepo
func (_mock *MockJobQueuesRepo) GetAllJobQueueVersions() ([]models.JobQueueVersion, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllJobQueueVersions")
	}

	var r0 []models.JobQueueVersion
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.JobQueueVersion, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.JobQueueVersion); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobQueueVersion)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobQueuesRepo_GetAllJobQueueVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllJobQueueVersions'
type MockJobQueuesRepo_GetAllJobQueueVersions_Call struct {
	*mock.Call
}

// GetAllJobQueueVersions is a helper method to define mock.On call
func (_e *MockJobQueuesRepo_Expecter) GetAllJobQueueVersions() *MockJobQueuesRepo_GetAllJobQueueVersions_Call {
	return &MockJobQueuesRepo_GetAllJobQueueVersions_Call{Call: _e.mock.On("GetAllJobQueueVersions")}
}

func (_c *MockJobQueuesRepo_GetAllJobQueueVersions_Call) Run(run func()) *MockJobQueuesRepo_GetAllJobQueueVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobQueuesRepo_GetAllJobQueueVersions_Call) Return(jobQueueVersions []models.JobQueueVersion, err error) *MockJobQueuesRepo_GetAllJobQueueVersions_Call {
	_c.Call.Return(jobQueueVersions, err)
	return _c
}

func (_c *MockJobQueuesRepo_GetAllJobQueueVersions_Call) RunAndReturn(run func() ([]models.JobQueueVersion, error)) *MockJobQueuesRepo_GetAllJobQueueVersions_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllJobQueues provides a mock function for the type MockJobQueuesRepo
func (_mock *MockJobQueuesRepo) GetAllJobQueues() ([]models.JobQueueLog, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllJobQueues")
	}

	var r0 []models.JobQueueLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]models.JobQueueLog, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.JobQueueLog); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobQueueLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobQueuesRepo_GetAllJobQueues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllJobQueues'
type MockJobQueuesRepo_GetAllJobQueues_Call struct {
	*mock.Call
}

// GetAllJobQueues is a helper method to define mock.On call
func (_e *MockJobQueuesRepo_Expecter) GetAllJobQueues() *MockJobQueuesRepo_GetAllJobQueues_Call {
	return &MockJobQueuesRepo_GetAllJobQueues_Call{Call: _e.mock.On("GetAllJobQueues")}
}

func (_c *MockJobQueuesRepo_GetAllJobQueues_Call) Run(run func()) *MockJobQueuesRepo_GetAllJobQueues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobQueuesRepo_GetAllJobQueues_Call) Return(jobQueueLogs []models.JobQueueLog, err error) *MockJobQueuesRepo_GetAllJobQueues_Call {
	_c.Call.Return(jobQueueLogs, err)
	return _c
}

func (_c *MockJobQueuesRepo_GetAllJobQueues_Call) RunAndReturn(run func() ([]models.JobQueueLog, error)) *MockJobQueuesRepo_GetAllJobQueues_Call {
	_c.Call.Return(run)
	return _c
}

// GetJobQueueByLastInsertedAndRowsAffected provides a mock function for the type MockJobQueuesRepo
func (_mock *MockJobQueuesRepo) GetJobQueueByLastInsertedAndRowsAffected(lastInsertedId int64, rowsAffected int64) []models.JobQueueLog {
	ret := _mock.Called(lastInsertedId, rowsAffected)

	if len(ret) == 0 {
		panic("no return value specified for GetJobQueueByLastInsertedAndRowsAffected")
	}

	var r0 []models.JobQueueLog
	if returnFunc, ok := ret.Get(0).(func(int64, int64) []models.JobQueueLog); ok {
		r0 = returnFunc(lastInsertedId, rowsAffected)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobQueueLog)
		}
	}
	return r0
}

// MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJobQueueByLastInsertedAndRowsAffected'
type MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call struct {
	*mock.Call
}

// GetJobQueueByLastInsertedAndRowsAffected is a helper method to define mock.On call
//   - lastInsertedId int64
//   - rowsAffected int64
func (_e *MockJobQueuesRepo_Expecter) GetJobQueueByLastInsertedAndRowsAffected(lastInsertedId interface{}, rowsAffected interface{}) *MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call {
	return &MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call{Call: _e.mock.On("GetJobQueueByLastInsertedAndRowsAffected", lastInsertedId, rowsAffected)}
}

func (_c *MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call) Run(run func(lastInsertedId int64, rowsAffected int64)) *MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call) Return(jobQueueLogs []models.JobQueueLog) *MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call {
	_c.Call.Return(jobQueueLogs)
	return _c
}

func (_c *MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call) RunAndReturn(run func(lastInsertedId int64, rowsAffected int64) []models.JobQueueLog) *MockJobQueuesRepo_GetJobQueueByLastInsertedAndRowsAffected_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastJobQueueLogForNode provides a mock function for the type MockJobQueuesRepo
func (_mock *MockJobQueuesRepo) GetLastJobQueueLogForNode(nodeId uint64, version uint64) []models.JobQueueLog {
	ret := _mock.Called(nodeId, version)

	if len(ret) == 0 {
		panic("no return value specified for GetLastJobQueueLogForNode")
	}

	var r0 []models.JobQueueLog
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) []models.JobQueueLog); ok {
		r0 = returnFunc(nodeId, version)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobQueueLog)
		}
	}
	return r0
}

// MockJobQueuesRepo_GetLastJobQueueLogForNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastJobQueueLogForNode'
type MockJobQueuesRepo_GetLastJobQueueLogForNode_Call struct {
	*mock.Call
}

// GetLastJobQueueLogForNode is a helper method to define mock.On call
//   - nodeId uint64
//   - version uint64
func (_e *MockJobQueuesRepo_Expecter) GetLastJobQueueLogForNode(nodeId interface{}, version interface{}) *MockJobQueuesRepo_GetLastJobQueueLogForNode_Call {
	return &MockJobQueuesRepo_GetLastJobQueueLogForNode_Call{Call: _e.mock.On("GetLastJobQueueLogForNode", nodeId, version)}
}

func (_c *MockJobQueuesRepo_GetLastJobQueueLogForNode_Call) Run(run func(nodeId uint64, version uint64)) *MockJobQueuesRepo_GetLastJobQueueLogForNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobQueuesRepo_GetLastJobQueueLogForNode_Call) Return(jobQueueLogs []models.JobQueueLog) *MockJobQueuesRepo_GetLastJobQueueLogForNode_Call {
	_c.Call.Return(jobQueueLogs)
	return _c
}

func (_c *MockJobQueuesRepo_GetLastJobQueueLogForNode_Call) RunAndReturn(run func(nodeId uint64, version uint64) []models.JobQueueLog) *MockJobQueuesRepo_GetLastJobQueueLogForNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetLastVersion provides a mock function for the type MockJobQueuesRepo
func (_mock *MockJobQueuesRepo) GetLastVersion() uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastVersion")
	}

	var r0 uint64
	if returnFunc, ok := ret.Get(0).(func() uint64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(uint64)
	}
	return r0
}

// MockJobQueuesRepo_GetLastVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastVersion'
type MockJobQueuesRepo_GetLastVersion_Call struct {
	*mock.Call
}

// GetLastVersion is a helper method to define mock.On call
func (_e *MockJobQueuesRepo_Expecter) GetLastVersion() *MockJobQueuesRepo_GetLastVersion_Call {
	return &MockJobQueuesRepo_GetLastVersion_Call{Call: _e.mock.On("GetLastVersion")}
}

func (_c *MockJobQueuesRepo_GetLastVersion_Call) Run(run func()) *MockJobQueuesRepo_GetLastVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobQueuesRepo_GetLastVersion_Call) Return(v uint64) *MockJobQueuesRepo_GetLastVersion_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockJobQueuesRepo_GetLastVersion_Call) RunAndReturn(run func() uint64) *MockJobQueuesRepo_GetLastVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetMostRecentJobQueueDate provides a mock function for the type MockJobQueuesRepo
func (_mock *MockJobQueuesRepo) GetMostRecentJobQueueDate() (time.Time, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMostRecentJobQueueDate")
	}

	var r0 time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (time.Time, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobQueuesRepo_GetMostRecentJobQueueDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMostRecentJobQueueDate'
type MockJobQueuesRepo_GetMostRecentJobQueueDate_Call struct {
	*mock.Call
}

// GetMostRecentJobQueueDate is a helper method to define mock.On call
func (_e *MockJobQueuesRepo_Expecter) GetMostRecentJobQueueDate() *MockJobQueuesRepo_GetMostRecentJobQueueDate_Call {
	return &MockJobQueuesRepo_GetMostRecentJobQueueDate_Call{Call: _e.mock.On("GetMostRecentJobQueueDate")}
}

func (_c *MockJobQueuesRepo_GetMostRecentJobQueueDate_Call) Run(run func()) *MockJobQueuesRepo_GetMostRecentJobQueueDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobQueuesRepo_GetMostRecentJobQueueDate_Call) Return(time1 time.Time, err error) *MockJobQueuesRepo_GetMostRecentJobQueueDate_Call {
	_c.Call.Return(time1, err)
	return _c
}

func (_c *MockJobQueuesRepo_GetMostRecentJobQueueDate_Call) RunAndReturn(run func() (time.Time, error)) *MockJobQueuesRepo_GetMostRecentJobQueueDate_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementQueueVersion provides a mock function for the type MockJobQueuesRepo
func (_mock *MockJobQueuesRepo) IncrementQueueVersion(numberOfServer int) {
	_mock.Called(numberOfServer)
	return
}

// MockJobQueuesRepo_IncrementQueueVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementQueueVersion'
type MockJobQueuesRepo_IncrementQueueVersion_Call struct {
	*mock.Call
}

// IncrementQueueVersion is a helper method to define mock.On call
//   - numberOfServer int
func (_e *MockJobQueuesRepo_Expecter) IncrementQueueVersion(numberOfServer interface{}) *MockJobQueuesRepo_IncrementQueueVersion_Call {
	return &MockJobQueuesRepo_IncrementQueueVersion_Call{Call: _e.mock.On("IncrementQueueVersion", numberOfServer)}
}

func (_c *MockJobQueuesRepo_IncrementQueueVersion_Call) Run(run func(numberOfServer int)) *MockJobQueuesRepo_IncrementQueueVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobQueuesRepo_IncrementQueueVersion_Call) Return() *MockJobQueuesRepo_IncrementQueueVersion_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobQueuesRepo_IncrementQueueVersion_Call) RunAndReturn(run func(numberOfServer int)) *MockJobQueuesRepo_IncrementQueueVersion_Call {
	_c.Run(run)
	return _c
}

// InsertJobQueueLogs provides a mock function for the type MockJobQueuesRepo
func (_mock *MockJobQueuesRepo) InsertJobQueueLogs(logs []models.JobQueueLog) {
	_mock.Called(logs)
	return
}

// MockJobQueuesRepo_InsertJobQueueLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertJobQueueLogs'
type MockJobQueuesRepo_InsertJobQueueLogs_Call struct {
	*mock.Call
}

// InsertJobQueueLogs is a helper method to define mock.On call
//   - logs []models.JobQueueLog
func (_e *MockJobQueuesRepo_Expecter) InsertJobQueueLogs(logs interface{}) *MockJobQueuesRepo_InsertJobQueueLogs_Call {
	return &MockJobQueuesRepo_InsertJobQueueLogs_Call{Call: _e.mock.On("InsertJobQueueLogs", logs)}
}

func (_c *MockJobQueuesRepo_InsertJobQueueLogs_Call) Run(run func(logs []models.JobQueueLog)) *MockJobQueuesRepo_InsertJobQueueLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.JobQueueLog
		if args[0] != nil {
			arg0 = args[0].([]models.JobQueueLog)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobQueuesRepo_InsertJobQueueLogs_Call) Return() *MockJobQueuesRepo_InsertJobQueueLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobQueuesRepo_InsertJobQueueLogs_Call) RunAndReturn(run func(logs []models.JobQueueLog)) *MockJobQueuesRepo_InsertJobQueueLogs_Call {
	_c.Run(run)
	return _c
}
