// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package async_task

import (
	"scheduler0/pkg/models"
	"scheduler0/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAsyncTaskService creates a new instance of MockAsyncTaskService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAsyncTaskService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAsyncTaskService {
	mock := &MockAsyncTaskService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAsyncTaskService is an autogenerated mock type for the AsyncTaskService type
type MockAsyncTaskService struct {
	mock.Mock
}

type MockAsyncTaskService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAsyncTaskService) EXPECT() *MockAsyncTaskService_Expecter {
	return &MockAsyncTaskService_Expecter{mock: &_m.Mock}
}

// AddSubscriber provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) AddSubscriber(taskId uint64, subscriber func(task models.AsyncTask)) (uint64, *utils.GenericError) {
	ret := _mock.Called(taskId, subscriber)

	if len(ret) == 0 {
		panic("no return value specified for AddSubscriber")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, func(task models.AsyncTask)) (uint64, *utils.GenericError)); ok {
		return returnFunc(taskId, subscriber)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, func(task models.AsyncTask)) uint64); ok {
		r0 = returnFunc(taskId, subscriber)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, func(task models.AsyncTask)) *utils.GenericError); ok {
		r1 = returnFunc(taskId, subscriber)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAsyncTaskService_AddSubscriber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSubscriber'
type MockAsyncTaskService_AddSubscriber_Call struct {
	*mock.Call
}

// AddSubscriber is a helper method to define mock.On call
//   - taskId uint64
//   - subscriber func(task models.AsyncTask)
func (_e *MockAsyncTaskService_Expecter) AddSubscriber(taskId interface{}, subscriber interface{}) *MockAsyncTaskService_AddSubscriber_Call {
	return &MockAsyncTaskService_AddSubscriber_Call{Call: _e.mock.On("AddSubscriber", taskId, subscriber)}
}

func (_c *MockAsyncTaskService_AddSubscriber_Call) Run(run func(taskId uint64, subscriber func(task models.AsyncTask))) *MockAsyncTaskService_AddSubscriber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 func(task models.AsyncTask)
		if args[1] != nil {
			arg1 = args[1].(func(task models.AsyncTask))
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_AddSubscriber_Call) Return(v uint64, genericError *utils.GenericError) *MockAsyncTaskService_AddSubscriber_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockAsyncTaskService_AddSubscriber_Call) RunAndReturn(run func(taskId uint64, subscriber func(task models.AsyncTask)) (uint64, *utils.GenericError)) *MockAsyncTaskService_AddSubscriber_Call {
	_c.Call.Return(run)
	return _c
}

// AddTasks provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) AddTasks(input string, requestId string, service string, accountId uint64) ([]uint64, *utils.GenericError) {
	ret := _mock.Called(input, requestId, service, accountId)

	if len(ret) == 0 {
		panic("no return value specified for AddTasks")
	}

	var r0 []uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(string, string, string, uint64) ([]uint64, *utils.GenericError)); ok {
		return returnFunc(input, requestId, service, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, uint64) []uint64); ok {
		r0 = returnFunc(input, requestId, service, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, uint64) *utils.GenericError); ok {
		r1 = returnFunc(input, requestId, service, accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAsyncTaskService_AddTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTasks'
type MockAsyncTaskService_AddTasks_Call struct {
	*mock.Call
}

// AddTasks is a helper method to define mock.On call
//   - input string
//   - requestId string
//   - service string
//   - accountId uint64
func (_e *MockAsyncTaskService_Expecter) AddTasks(input interface{}, requestId interface{}, service interface{}, accountId interface{}) *MockAsyncTaskService_AddTasks_Call {
	return &MockAsyncTaskService_AddTasks_Call{Call: _e.mock.On("AddTasks", input, requestId, service, accountId)}
}

func (_c *MockAsyncTaskService_AddTasks_Call) Run(run func(input string, requestId string, service string, accountId uint64)) *MockAsyncTaskService_AddTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_AddTasks_Call) Return(uint64s []uint64, genericError *utils.GenericError) *MockAsyncTaskService_AddTasks_Call {
	_c.Call.Return(uint64s, genericError)
	return _c
}

func (_c *MockAsyncTaskService_AddTasks_Call) RunAndReturn(run func(input string, requestId string, service string, accountId uint64) ([]uint64, *utils.GenericError)) *MockAsyncTaskService_AddTasks_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNewUncommittedAsyncLogs provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) DeleteNewUncommittedAsyncLogs(lastInsertedId int64, rowsAffected int64) {
	_mock.Called(lastInsertedId, rowsAffected)
	return
}

// MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNewUncommittedAsyncLogs'
type MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call struct {
	*mock.Call
}

// DeleteNewUncommittedAsyncLogs is a helper method to define mock.On call
//   - lastInsertedId int64
//   - rowsAffected int64
func (_e *MockAsyncTaskService_Expecter) DeleteNewUncommittedAsyncLogs(lastInsertedId interface{}, rowsAffected interface{}) *MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call {
	return &MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call{Call: _e.mock.On("DeleteNewUncommittedAsyncLogs", lastInsertedId, rowsAffected)}
}

func (_c *MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call) Run(run func(lastInsertedId int64, rowsAffected int64)) *MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call) Return() *MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call) RunAndReturn(run func(lastInsertedId int64, rowsAffected int64)) *MockAsyncTaskService_DeleteNewUncommittedAsyncLogs_Call {
	_c.Run(run)
	return _c
}

// DeleteSubscriber provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) DeleteSubscriber(taskId uint64, subscriberId uint64) *utils.GenericError {
	ret := _mock.Called(taskId, subscriberId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSubscriber")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(taskId, subscriberId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAsyncTaskService_DeleteSubscriber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSubscriber'
type MockAsyncTaskService_DeleteSubscriber_Call struct {
	*mock.Call
}

// DeleteSubscriber is a helper method to define mock.On call
//   - taskId uint64
//   - subscriberId uint64
func (_e *MockAsyncTaskService_Expecter) DeleteSubscriber(taskId interface{}, subscriberId interface{}) *MockAsyncTaskService_DeleteSubscriber_Call {
	return &MockAsyncTaskService_DeleteSubscriber_Call{Call: _e.mock.On("DeleteSubscriber", taskId, subscriberId)}
}

func (_c *MockAsyncTaskService_DeleteSubscriber_Call) Run(run func(taskId uint64, subscriberId uint64)) *MockAsyncTaskService_DeleteSubscriber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_DeleteSubscriber_Call) Return(genericError *utils.GenericError) *MockAsyncTaskService_DeleteSubscriber_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAsyncTaskService_DeleteSubscriber_Call) RunAndReturn(run func(taskId uint64, subscriberId uint64) *utils.GenericError) *MockAsyncTaskService_DeleteSubscriber_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeIsLeader provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) GetNodeIsLeader() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNodeIsLeader")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAsyncTaskService_GetNodeIsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeIsLeader'
type MockAsyncTaskService_GetNodeIsLeader_Call struct {
	*mock.Call
}

// GetNodeIsLeader is a helper method to define mock.On call
func (_e *MockAsyncTaskService_Expecter) GetNodeIsLeader() *MockAsyncTaskService_GetNodeIsLeader_Call {
	return &MockAsyncTaskService_GetNodeIsLeader_Call{Call: _e.mock.On("GetNodeIsLeader")}
}

func (_c *MockAsyncTaskService_GetNodeIsLeader_Call) Run(run func()) *MockAsyncTaskService_GetNodeIsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAsyncTaskService_GetNodeIsLeader_Call) Return(b bool) *MockAsyncTaskService_GetNodeIsLeader_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAsyncTaskService_GetNodeIsLeader_Call) RunAndReturn(run func() bool) *MockAsyncTaskService_GetNodeIsLeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetSingleNodeMode provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) GetSingleNodeMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSingleNodeMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAsyncTaskService_GetSingleNodeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSingleNodeMode'
type MockAsyncTaskService_GetSingleNodeMode_Call struct {
	*mock.Call
}

// GetSingleNodeMode is a helper method to define mock.On call
func (_e *MockAsyncTaskService_Expecter) GetSingleNodeMode() *MockAsyncTaskService_GetSingleNodeMode_Call {
	return &MockAsyncTaskService_GetSingleNodeMode_Call{Call: _e.mock.On("GetSingleNodeMode")}
}

func (_c *MockAsyncTaskService_GetSingleNodeMode_Call) Run(run func()) *MockAsyncTaskService_GetSingleNodeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAsyncTaskService_GetSingleNodeMode_Call) Return(b bool) *MockAsyncTaskService_GetSingleNodeMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAsyncTaskService_GetSingleNodeMode_Call) RunAndReturn(run func() bool) *MockAsyncTaskService_GetSingleNodeMode_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskBlocking provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) GetTaskBlocking(taskId uint64) (chan models.AsyncTask, uint64, *utils.GenericError) {
	ret := _mock.Called(taskId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskBlocking")
	}

	var r0 chan models.AsyncTask
	var r1 uint64
	var r2 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (chan models.AsyncTask, uint64, *utils.GenericError)); ok {
		return returnFunc(taskId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) chan models.AsyncTask); ok {
		r0 = returnFunc(taskId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan models.AsyncTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) uint64); ok {
		r1 = returnFunc(taskId)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(uint64) *utils.GenericError); ok {
		r2 = returnFunc(taskId)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*utils.GenericError)
		}
	}
	return r0, r1, r2
}

// MockAsyncTaskService_GetTaskBlocking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskBlocking'
type MockAsyncTaskService_GetTaskBlocking_Call struct {
	*mock.Call
}

// GetTaskBlocking is a helper method to define mock.On call
//   - taskId uint64
func (_e *MockAsyncTaskService_Expecter) GetTaskBlocking(taskId interface{}) *MockAsyncTaskService_GetTaskBlocking_Call {
	return &MockAsyncTaskService_GetTaskBlocking_Call{Call: _e.mock.On("GetTaskBlocking", taskId)}
}

func (_c *MockAsyncTaskService_GetTaskBlocking_Call) Run(run func(taskId uint64)) *MockAsyncTaskService_GetTaskBlocking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_GetTaskBlocking_Call) Return(asyncTaskCh chan models.AsyncTask, v uint64, genericError *utils.GenericError) *MockAsyncTaskService_GetTaskBlocking_Call {
	_c.Call.Return(asyncTaskCh, v, genericError)
	return _c
}

func (_c *MockAsyncTaskService_GetTaskBlocking_Call) RunAndReturn(run func(taskId uint64) (chan models.AsyncTask, uint64, *utils.GenericError)) *MockAsyncTaskService_GetTaskBlocking_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskIdWithRequestId provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) GetTaskIdWithRequestId(requestId string, accountId uint64) (uint64, *utils.GenericError) {
	ret := _mock.Called(requestId, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskIdWithRequestId")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(string, uint64) (uint64, *utils.GenericError)); ok {
		return returnFunc(requestId, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint64) uint64); ok {
		r0 = returnFunc(requestId, accountId)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint64) *utils.GenericError); ok {
		r1 = returnFunc(requestId, accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAsyncTaskService_GetTaskIdWithRequestId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskIdWithRequestId'
type MockAsyncTaskService_GetTaskIdWithRequestId_Call struct {
	*mock.Call
}

// GetTaskIdWithRequestId is a helper method to define mock.On call
//   - requestId string
//   - accountId uint64
func (_e *MockAsyncTaskService_Expecter) GetTaskIdWithRequestId(requestId interface{}, accountId interface{}) *MockAsyncTaskService_GetTaskIdWithRequestId_Call {
	return &MockAsyncTaskService_GetTaskIdWithRequestId_Call{Call: _e.mock.On("GetTaskIdWithRequestId", requestId, accountId)}
}

func (_c *MockAsyncTaskService_GetTaskIdWithRequestId_Call) Run(run func(requestId string, accountId uint64)) *MockAsyncTaskService_GetTaskIdWithRequestId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_GetTaskIdWithRequestId_Call) Return(v uint64, genericError *utils.GenericError) *MockAsyncTaskService_GetTaskIdWithRequestId_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockAsyncTaskService_GetTaskIdWithRequestId_Call) RunAndReturn(run func(requestId string, accountId uint64) (uint64, *utils.GenericError)) *MockAsyncTaskService_GetTaskIdWithRequestId_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskWithRequestIdBlocking provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) GetTaskWithRequestIdBlocking(requestId string, accountId uint64) (chan models.AsyncTask, uint64, *utils.GenericError) {
	ret := _mock.Called(requestId, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskWithRequestIdBlocking")
	}

	var r0 chan models.AsyncTask
	var r1 uint64
	var r2 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(string, uint64) (chan models.AsyncTask, uint64, *utils.GenericError)); ok {
		return returnFunc(requestId, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint64) chan models.AsyncTask); ok {
		r0 = returnFunc(requestId, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(chan models.AsyncTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint64) uint64); ok {
		r1 = returnFunc(requestId, accountId)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(string, uint64) *utils.GenericError); ok {
		r2 = returnFunc(requestId, accountId)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*utils.GenericError)
		}
	}
	return r0, r1, r2
}

// MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskWithRequestIdBlocking'
type MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call struct {
	*mock.Call
}

// GetTaskWithRequestIdBlocking is a helper method to define mock.On call
//   - requestId string
//   - accountId uint64
func (_e *MockAsyncTaskService_Expecter) GetTaskWithRequestIdBlocking(requestId interface{}, accountId interface{}) *MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call {
	return &MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call{Call: _e.mock.On("GetTaskWithRequestIdBlocking", requestId, accountId)}
}

func (_c *MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call) Run(run func(requestId string, accountId uint64)) *MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call) Return(asyncTaskCh chan models.AsyncTask, v uint64, genericError *utils.GenericError) *MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call {
	_c.Call.Return(asyncTaskCh, v, genericError)
	return _c
}

func (_c *MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call) RunAndReturn(run func(requestId string, accountId uint64) (chan models.AsyncTask, uint64, *utils.GenericError)) *MockAsyncTaskService_GetTaskWithRequestIdBlocking_Call {
	_c.Call.Return(run)
	return _c
}

// GetTaskWithRequestIdNonBlocking provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) GetTaskWithRequestIdNonBlocking(requestId string, accountId uint64) (*models.AsyncTask, *utils.GenericError) {
	ret := _mock.Called(requestId, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskWithRequestIdNonBlocking")
	}

	var r0 *models.AsyncTask
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(string, uint64) (*models.AsyncTask, *utils.GenericError)); ok {
		return returnFunc(requestId, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, uint64) *models.AsyncTask); ok {
		r0 = returnFunc(requestId, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AsyncTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, uint64) *utils.GenericError); ok {
		r1 = returnFunc(requestId, accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTaskWithRequestIdNonBlocking'
type MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call struct {
	*mock.Call
}

// GetTaskWithRequestIdNonBlocking is a helper method to define mock.On call
//   - requestId string
//   - accountId uint64
func (_e *MockAsyncTaskService_Expecter) GetTaskWithRequestIdNonBlocking(requestId interface{}, accountId interface{}) *MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call {
	return &MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call{Call: _e.mock.On("GetTaskWithRequestIdNonBlocking", requestId, accountId)}
}

func (_c *MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call) Run(run func(requestId string, accountId uint64)) *MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call) Return(asyncTask *models.AsyncTask, genericError *utils.GenericError) *MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call {
	_c.Call.Return(asyncTask, genericError)
	return _c
}

func (_c *MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call) RunAndReturn(run func(requestId string, accountId uint64) (*models.AsyncTask, *utils.GenericError)) *MockAsyncTaskService_GetTaskWithRequestIdNonBlocking_Call {
	_c.Call.Return(run)
	return _c
}

// GetUnCommittedTasks provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) GetUnCommittedTasks() ([]models.AsyncTask, *utils.GenericError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUnCommittedTasks")
	}

	var r0 []models.AsyncTask
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func() ([]models.AsyncTask, *utils.GenericError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.AsyncTask); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AsyncTask)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *utils.GenericError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAsyncTaskService_GetUnCommittedTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUnCommittedTasks'
type MockAsyncTaskService_GetUnCommittedTasks_Call struct {
	*mock.Call
}

// GetUnCommittedTasks is a helper method to define mock.On call
func (_e *MockAsyncTaskService_Expecter) GetUnCommittedTasks() *MockAsyncTaskService_GetUnCommittedTasks_Call {
	return &MockAsyncTaskService_GetUnCommittedTasks_Call{Call: _e.mock.On("GetUnCommittedTasks")}
}

func (_c *MockAsyncTaskService_GetUnCommittedTasks_Call) Run(run func()) *MockAsyncTaskService_GetUnCommittedTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAsyncTaskService_GetUnCommittedTasks_Call) Return(asyncTasks []models.AsyncTask, genericError *utils.GenericError) *MockAsyncTaskService_GetUnCommittedTasks_Call {
	_c.Call.Return(asyncTasks, genericError)
	return _c
}

func (_c *MockAsyncTaskService_GetUnCommittedTasks_Call) RunAndReturn(run func() ([]models.AsyncTask, *utils.GenericError)) *MockAsyncTaskService_GetUnCommittedTasks_Call {
	_c.Call.Return(run)
	return _c
}

// ListenForNotifications provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) ListenForNotifications() {
	_mock.Called()
	return
}

// MockAsyncTaskService_ListenForNotifications_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenForNotifications'
type MockAsyncTaskService_ListenForNotifications_Call struct {
	*mock.Call
}

// ListenForNotifications is a helper method to define mock.On call
func (_e *MockAsyncTaskService_Expecter) ListenForNotifications() *MockAsyncTaskService_ListenForNotifications_Call {
	return &MockAsyncTaskService_ListenForNotifications_Call{Call: _e.mock.On("ListenForNotifications")}
}

func (_c *MockAsyncTaskService_ListenForNotifications_Call) Run(run func()) *MockAsyncTaskService_ListenForNotifications_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAsyncTaskService_ListenForNotifications_Call) Return() *MockAsyncTaskService_ListenForNotifications_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncTaskService_ListenForNotifications_Call) RunAndReturn(run func()) *MockAsyncTaskService_ListenForNotifications_Call {
	_c.Run(run)
	return _c
}

// SetNodeIsLeader provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) SetNodeIsLeader(nodeIsLeader bool) {
	_mock.Called(nodeIsLeader)
	return
}

// MockAsyncTaskService_SetNodeIsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodeIsLeader'
type MockAsyncTaskService_SetNodeIsLeader_Call struct {
	*mock.Call
}

// SetNodeIsLeader is a helper method to define mock.On call
//   - nodeIsLeader bool
func (_e *MockAsyncTaskService_Expecter) SetNodeIsLeader(nodeIsLeader interface{}) *MockAsyncTaskService_SetNodeIsLeader_Call {
	return &MockAsyncTaskService_SetNodeIsLeader_Call{Call: _e.mock.On("SetNodeIsLeader", nodeIsLeader)}
}

func (_c *MockAsyncTaskService_SetNodeIsLeader_Call) Run(run func(nodeIsLeader bool)) *MockAsyncTaskService_SetNodeIsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_SetNodeIsLeader_Call) Return() *MockAsyncTaskService_SetNodeIsLeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncTaskService_SetNodeIsLeader_Call) RunAndReturn(run func(nodeIsLeader bool)) *MockAsyncTaskService_SetNodeIsLeader_Call {
	_c.Run(run)
	return _c
}

// SetSingleNodeMode provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) SetSingleNodeMode(singleNodeMode bool) {
	_mock.Called(singleNodeMode)
	return
}

// MockAsyncTaskService_SetSingleNodeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSingleNodeMode'
type MockAsyncTaskService_SetSingleNodeMode_Call struct {
	*mock.Call
}

// SetSingleNodeMode is a helper method to define mock.On call
//   - singleNodeMode bool
func (_e *MockAsyncTaskService_Expecter) SetSingleNodeMode(singleNodeMode interface{}) *MockAsyncTaskService_SetSingleNodeMode_Call {
	return &MockAsyncTaskService_SetSingleNodeMode_Call{Call: _e.mock.On("SetSingleNodeMode", singleNodeMode)}
}

func (_c *MockAsyncTaskService_SetSingleNodeMode_Call) Run(run func(singleNodeMode bool)) *MockAsyncTaskService_SetSingleNodeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_SetSingleNodeMode_Call) Return() *MockAsyncTaskService_SetSingleNodeMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAsyncTaskService_SetSingleNodeMode_Call) RunAndReturn(run func(singleNodeMode bool)) *MockAsyncTaskService_SetSingleNodeMode_Call {
	_c.Run(run)
	return _c
}

// UpdateTasksById provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) UpdateTasksById(taskId uint64, state models.AsyncTaskState, output string) *utils.GenericError {
	ret := _mock.Called(taskId, state, output)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTasksById")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, models.AsyncTaskState, string) *utils.GenericError); ok {
		r0 = returnFunc(taskId, state, output)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAsyncTaskService_UpdateTasksById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTasksById'
type MockAsyncTaskService_UpdateTasksById_Call struct {
	*mock.Call
}

// UpdateTasksById is a helper method to define mock.On call
//   - taskId uint64
//   - state models.AsyncTaskState
//   - output string
func (_e *MockAsyncTaskService_Expecter) UpdateTasksById(taskId interface{}, state interface{}, output interface{}) *MockAsyncTaskService_UpdateTasksById_Call {
	return &MockAsyncTaskService_UpdateTasksById_Call{Call: _e.mock.On("UpdateTasksById", taskId, state, output)}
}

func (_c *MockAsyncTaskService_UpdateTasksById_Call) Run(run func(taskId uint64, state models.AsyncTaskState, output string)) *MockAsyncTaskService_UpdateTasksById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 models.AsyncTaskState
		if args[1] != nil {
			arg1 = args[1].(models.AsyncTaskState)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_UpdateTasksById_Call) Return(genericError *utils.GenericError) *MockAsyncTaskService_UpdateTasksById_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAsyncTaskService_UpdateTasksById_Call) RunAndReturn(run func(taskId uint64, state models.AsyncTaskState, output string) *utils.GenericError) *MockAsyncTaskService_UpdateTasksById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTasksByRequestId provides a mock function for the type MockAsyncTaskService
func (_mock *MockAsyncTaskService) UpdateTasksByRequestId(requestId string, state models.AsyncTaskState, output string) *utils.GenericError {
	ret := _mock.Called(requestId, state, output)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTasksByRequestId")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(string, models.AsyncTaskState, string) *utils.GenericError); ok {
		r0 = returnFunc(requestId, state, output)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAsyncTaskService_UpdateTasksByRequestId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTasksByRequestId'
type MockAsyncTaskService_UpdateTasksByRequestId_Call struct {
	*mock.Call
}

// UpdateTasksByRequestId is a helper method to define mock.On call
//   - requestId string
//   - state models.AsyncTaskState
//   - output string
func (_e *MockAsyncTaskService_Expecter) UpdateTasksByRequestId(requestId interface{}, state interface{}, output interface{}) *MockAsyncTaskService_UpdateTasksByRequestId_Call {
	return &MockAsyncTaskService_UpdateTasksByRequestId_Call{Call: _e.mock.On("UpdateTasksByRequestId", requestId, state, output)}
}

func (_c *MockAsyncTaskService_UpdateTasksByRequestId_Call) Run(run func(requestId string, state models.AsyncTaskState, output string)) *MockAsyncTaskService_UpdateTasksByRequestId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.AsyncTaskState
		if args[1] != nil {
			arg1 = args[1].(models.AsyncTaskState)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAsyncTaskService_UpdateTasksByRequestId_Call) Return(genericError *utils.GenericError) *MockAsyncTaskService_UpdateTasksByRequestId_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAsyncTaskService_UpdateTasksByRequestId_Call) RunAndReturn(run func(requestId string, state models.AsyncTaskState, output string) *utils.GenericError) *MockAsyncTaskService_UpdateTasksByRequestId_Call {
	_c.Call.Return(run)
	return _c
}
