FROM golang:1.13

MAINTAINER Victor Nwaokocha

RUN mkdir -p /usr/src/server
WORKDIR /usr/src/server

ARG PORT
ARG POSTGRES_USER
ARG POSTGRES_ADDRESS
ARG POSTGRES_PASSWORD
ARG POSTGRES_DATABASE
ARG POSTGRES_USER
ARG CLIENT_HOST
ARG BASIC_AUTH_USER
ARG BASIC_AUTH_PASS

COPY . /usr/src/server

ENV PORT $PORT
ENV ENV $ENV
ENV POSTGRES_ADDRESS $POSTGRES_ADDRESS
ENV POSTGRES_USER $POSTGRES_USER
ENV POSTGRES_PASSWORD $POSTGRES_PASSWORD
ENV POSTGRES_DATABASE $POSTGRES_DATABASE
ENV CLIENT_HOST $CLIENT_HOST
ENV BASIC_AUTH_USER $BASIC_AUTH_USER
ENV BASIC_AUTH_PASS $BASIC_AUTH_PASS

RUN go clean -testcache

RUN go test ./src/managers/execution -cover -v -race
RUN go test ./src/managers/job -cover -v -race
RUN go test ./src/managers/project -cover -v -race
RUN go test ./src/managers/credential -cover -v -race

RUN go test ./src/controllers/execution -cover -v -race
RUN go test ./src/controllers/credential -cover -v -race
RUN go test ./src/controllers/job -cover -v -race
RUN go test ./src/controllers/project -cover -v -race

EXPOSE 4321
