// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	"scheduler0/config"
)

// Scheduler0Config is an autogenerated mock type for the Scheduler0Config type
type Scheduler0Config struct {
	mock.Mock
}

// GetConfigurations provides a mock function with given fields:
func (_m *Scheduler0Config) GetConfigurations() *config.scheduler0Configurations {
	ret := _m.Called()

	var r0 *config.scheduler0Configurations
	if rf, ok := ret.Get(0).(func() *config.scheduler0Configurations); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*config.scheduler0Configurations)
		}
	}

	return r0
}

type mockConstructorTestingTNewScheduler0Config interface {
	mock.TestingT
	Cleanup(func())
}

// NewScheduler0Config creates a new instance of Scheduler0Config. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewScheduler0Config(t mockConstructorTestingTNewScheduler0Config) *Scheduler0Config {
	mock := &Scheduler0Config{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
