// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package executor

import (
	"scheduler0/pkg/alerts"
	"scheduler0/pkg/models"
	"scheduler0/pkg/utils"
	"sync"

	"github.com/hashicorp/raft"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobExecutorService creates a new instance of MockJobExecutorService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobExecutorService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobExecutorService {
	mock := &MockJobExecutorService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobExecutorService is an autogenerated mock type for the JobExecutorService type
type MockJobExecutorService struct {
	mock.Mock
}

type MockJobExecutorService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobExecutorService) EXPECT() *MockJobExecutorService_Expecter {
	return &MockJobExecutorService_Expecter{mock: &_m.Mock}
}

// AddJobSchedule provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) AddJobSchedule(job models.Job) {
	_mock.Called(job)
	return
}

// MockJobExecutorService_AddJobSchedule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddJobSchedule'
type MockJobExecutorService_AddJobSchedule_Call struct {
	*mock.Call
}

// AddJobSchedule is a helper method to define mock.On call
//   - job models.Job
func (_e *MockJobExecutorService_Expecter) AddJobSchedule(job interface{}) *MockJobExecutorService_AddJobSchedule_Call {
	return &MockJobExecutorService_AddJobSchedule_Call{Call: _e.mock.On("AddJobSchedule", job)}
}

func (_c *MockJobExecutorService_AddJobSchedule_Call) Run(run func(job models.Job)) *MockJobExecutorService_AddJobSchedule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.Job
		if args[0] != nil {
			arg0 = args[0].(models.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_AddJobSchedule_Call) Return() *MockJobExecutorService_AddJobSchedule_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_AddJobSchedule_Call) RunAndReturn(run func(job models.Job)) *MockJobExecutorService_AddJobSchedule_Call {
	_c.Run(run)
	return _c
}

// CreateExecutor provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) CreateExecutor(newJobExecutor models.JobExecutor) (uint64, *utils.GenericError) {
	ret := _mock.Called(newJobExecutor)

	if len(ret) == 0 {
		panic("no return value specified for CreateExecutor")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(models.JobExecutor) (uint64, *utils.GenericError)); ok {
		return returnFunc(newJobExecutor)
	}
	if returnFunc, ok := ret.Get(0).(func(models.JobExecutor) uint64); ok {
		r0 = returnFunc(newJobExecutor)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(models.JobExecutor) *utils.GenericError); ok {
		r1 = returnFunc(newJobExecutor)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_CreateExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExecutor'
type MockJobExecutorService_CreateExecutor_Call struct {
	*mock.Call
}

// CreateExecutor is a helper method to define mock.On call
//   - newJobExecutor models.JobExecutor
func (_e *MockJobExecutorService_Expecter) CreateExecutor(newJobExecutor interface{}) *MockJobExecutorService_CreateExecutor_Call {
	return &MockJobExecutorService_CreateExecutor_Call{Call: _e.mock.On("CreateExecutor", newJobExecutor)}
}

func (_c *MockJobExecutorService_CreateExecutor_Call) Run(run func(newJobExecutor models.JobExecutor)) *MockJobExecutorService_CreateExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.JobExecutor
		if args[0] != nil {
			arg0 = args[0].(models.JobExecutor)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_CreateExecutor_Call) Return(v uint64, genericError *utils.GenericError) *MockJobExecutorService_CreateExecutor_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockJobExecutorService_CreateExecutor_Call) RunAndReturn(run func(newJobExecutor models.JobExecutor) (uint64, *utils.GenericError)) *MockJobExecutorService_CreateExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// TestInvokeExecutor provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) TestInvokeExecutor(accountId uint64, executorId uint64, req models.TestInvocationRequest) (*models.TestInvocationResult, *utils.GenericError) {
	ret := _mock.Called(accountId, executorId, req)

	if len(ret) == 0 {
		panic("no return value specified for TestInvokeExecutor")
	}

	var r0 *models.TestInvocationResult
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, models.TestInvocationRequest) (*models.TestInvocationResult, *utils.GenericError)); ok {
		return returnFunc(accountId, executorId, req)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, models.TestInvocationRequest) *models.TestInvocationResult); ok {
		r0 = returnFunc(accountId, executorId, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TestInvocationResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, models.TestInvocationRequest) *utils.GenericError); ok {
		r1 = returnFunc(accountId, executorId, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_TestInvokeExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestInvokeExecutor'
type MockJobExecutorService_TestInvokeExecutor_Call struct {
	*mock.Call
}

// TestInvokeExecutor is a helper method to define mock.On call
//   - accountId uint64
//   - executorId uint64
//   - req models.TestInvocationRequest
func (_e *MockJobExecutorService_Expecter) TestInvokeExecutor(accountId interface{}, executorId interface{}, req interface{}) *MockJobExecutorService_TestInvokeExecutor_Call {
	return &MockJobExecutorService_TestInvokeExecutor_Call{Call: _e.mock.On("TestInvokeExecutor", accountId, executorId, req)}
}

func (_c *MockJobExecutorService_TestInvokeExecutor_Call) Run(run func(accountId uint64, executorId uint64, req models.TestInvocationRequest)) *MockJobExecutorService_TestInvokeExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 models.TestInvocationRequest
		if args[2] != nil {
			arg2 = args[2].(models.TestInvocationRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_TestInvokeExecutor_Call) Return(testInvocationResult *models.TestInvocationResult, genericError *utils.GenericError) *MockJobExecutorService_TestInvokeExecutor_Call {
	_c.Call.Return(testInvocationResult, genericError)
	return _c
}

func (_c *MockJobExecutorService_TestInvokeExecutor_Call) RunAndReturn(run func(accountId uint64, executorId uint64, req models.TestInvocationRequest) (*models.TestInvocationResult, *utils.GenericError)) *MockJobExecutorService_TestInvokeExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterLocalExecutor provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) RegisterLocalExecutor(name string, command string, workingDir string, createdBy string, accountId uint64) (uint64, *utils.GenericError) {
	ret := _mock.Called(name, command, workingDir, createdBy, accountId)

	if len(ret) == 0 {
		panic("no return value specified for RegisterLocalExecutor")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, uint64) (uint64, *utils.GenericError)); ok {
		return returnFunc(name, command, workingDir, createdBy, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, uint64) uint64); ok {
		r0 = returnFunc(name, command, workingDir, createdBy, accountId)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, uint64) *utils.GenericError); ok {
		r1 = returnFunc(name, command, workingDir, createdBy, accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_RegisterLocalExecutor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterLocalExecutor'
type MockJobExecutorService_RegisterLocalExecutor_Call struct {
	*mock.Call
}

// RegisterLocalExecutor is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) RegisterLocalExecutor(name interface{}, command interface{}, workingDir interface{}, createdBy interface{}, accountId interface{}) *MockJobExecutorService_RegisterLocalExecutor_Call {
	return &MockJobExecutorService_RegisterLocalExecutor_Call{Call: _e.mock.On("RegisterLocalExecutor", name, command, workingDir, createdBy, accountId)}
}

func (_c *MockJobExecutorService_RegisterLocalExecutor_Call) Run(run func(name string, command string, workingDir string, createdBy string, accountId uint64)) *MockJobExecutorService_RegisterLocalExecutor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_RegisterLocalExecutor_Call) Return(v uint64, genericError *utils.GenericError) *MockJobExecutorService_RegisterLocalExecutor_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockJobExecutorService_RegisterLocalExecutor_Call) RunAndReturn(run func(name string, command string, workingDir string, createdBy string, accountId uint64) (uint64, *utils.GenericError)) *MockJobExecutorService_RegisterLocalExecutor_Call {
	_c.Call.Return(run)
	return _c
}

// PullExecutorJobs provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) PullExecutorJobs(executorId uint64, accountId uint64) ([]models.Job, *utils.GenericError) {
	ret := _mock.Called(executorId, accountId)

	if len(ret) == 0 {
		panic("no return value specified for PullExecutorJobs")
	}

	var r0 []models.Job
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) ([]models.Job, *utils.GenericError)); ok {
		return returnFunc(executorId, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) []models.Job); ok {
		r0 = returnFunc(executorId, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Job)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) *utils.GenericError); ok {
		r1 = returnFunc(executorId, accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_PullExecutorJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullExecutorJobs'
type MockJobExecutorService_PullExecutorJobs_Call struct {
	*mock.Call
}

// PullExecutorJobs is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) PullExecutorJobs(executorId interface{}, accountId interface{}) *MockJobExecutorService_PullExecutorJobs_Call {
	return &MockJobExecutorService_PullExecutorJobs_Call{Call: _e.mock.On("PullExecutorJobs", executorId, accountId)}
}

func (_c *MockJobExecutorService_PullExecutorJobs_Call) Run(run func(executorId uint64, accountId uint64)) *MockJobExecutorService_PullExecutorJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_PullExecutorJobs_Call) Return(jobs []models.Job, genericError *utils.GenericError) *MockJobExecutorService_PullExecutorJobs_Call {
	_c.Call.Return(jobs, genericError)
	return _c
}

func (_c *MockJobExecutorService_PullExecutorJobs_Call) RunAndReturn(run func(executorId uint64, accountId uint64) ([]models.Job, *utils.GenericError)) *MockJobExecutorService_PullExecutorJobs_Call {
	_c.Call.Return(run)
	return _c
}

// ReportExecutions provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) ReportExecutions(executorId uint64, accountId uint64, reports []models.LocalExecutionReport) (int, *utils.GenericError) {
	ret := _mock.Called(executorId, accountId, reports)

	if len(ret) == 0 {
		panic("no return value specified for ReportExecutions")
	}

	var r0 int
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, []models.LocalExecutionReport) (int, *utils.GenericError)); ok {
		return returnFunc(executorId, accountId, reports)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, []models.LocalExecutionReport) int); ok {
		r0 = returnFunc(executorId, accountId, reports)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, []models.LocalExecutionReport) *utils.GenericError); ok {
		r1 = returnFunc(executorId, accountId, reports)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_ReportExecutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportExecutions'
type MockJobExecutorService_ReportExecutions_Call struct {
	*mock.Call
}

// ReportExecutions is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) ReportExecutions(executorId interface{}, accountId interface{}, reports interface{}) *MockJobExecutorService_ReportExecutions_Call {
	return &MockJobExecutorService_ReportExecutions_Call{Call: _e.mock.On("ReportExecutions", executorId, accountId, reports)}
}

func (_c *MockJobExecutorService_ReportExecutions_Call) Run(run func(executorId uint64, accountId uint64, reports []models.LocalExecutionReport)) *MockJobExecutorService_ReportExecutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 []models.LocalExecutionReport
		if args[2] != nil {
			arg2 = args[2].([]models.LocalExecutionReport)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_ReportExecutions_Call) Return(v int, genericError *utils.GenericError) *MockJobExecutorService_ReportExecutions_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockJobExecutorService_ReportExecutions_Call) RunAndReturn(run func(executorId uint64, accountId uint64, reports []models.LocalExecutionReport) (int, *utils.GenericError)) *MockJobExecutorService_ReportExecutions_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementLocalQuota provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) DecrementLocalQuota(accountId uint64) bool {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for DecrementLocalQuota")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(uint64) bool); ok {
		r0 = returnFunc(accountId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockJobExecutorService_DecrementLocalQuota_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementLocalQuota'
type MockJobExecutorService_DecrementLocalQuota_Call struct {
	*mock.Call
}

// DecrementLocalQuota is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockJobExecutorService_Expecter) DecrementLocalQuota(accountId interface{}) *MockJobExecutorService_DecrementLocalQuota_Call {
	return &MockJobExecutorService_DecrementLocalQuota_Call{Call: _e.mock.On("DecrementLocalQuota", accountId)}
}

func (_c *MockJobExecutorService_DecrementLocalQuota_Call) Run(run func(accountId uint64)) *MockJobExecutorService_DecrementLocalQuota_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_DecrementLocalQuota_Call) Return(b bool) *MockJobExecutorService_DecrementLocalQuota_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockJobExecutorService_DecrementLocalQuota_Call) RunAndReturn(run func(accountId uint64) bool) *MockJobExecutorService_DecrementLocalQuota_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteNewUncommittedExecutionLogs provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) DeleteNewUncommittedExecutionLogs(lastInsertedId int64, rowsAffected int64) {
	_mock.Called(lastInsertedId, rowsAffected)
	return
}

// MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteNewUncommittedExecutionLogs'
type MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call struct {
	*mock.Call
}

// DeleteNewUncommittedExecutionLogs is a helper method to define mock.On call
//   - lastInsertedId int64
//   - rowsAffected int64
func (_e *MockJobExecutorService_Expecter) DeleteNewUncommittedExecutionLogs(lastInsertedId interface{}, rowsAffected interface{}) *MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call {
	return &MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call{Call: _e.mock.On("DeleteNewUncommittedExecutionLogs", lastInsertedId, rowsAffected)}
}

func (_c *MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call) Run(run func(lastInsertedId int64, rowsAffected int64)) *MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call) Return() *MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call) RunAndReturn(run func(lastInsertedId int64, rowsAffected int64)) *MockJobExecutorService_DeleteNewUncommittedExecutionLogs_Call {
	_c.Run(run)
	return _c
}

// DeleteOneByID provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) DeleteOneByID(id uint64, accountId uint64, deletedBy string) (uint64, *utils.GenericError) {
	ret := _mock.Called(id, accountId, deletedBy)

	if len(ret) == 0 {
		panic("no return value specified for DeleteOneByID")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, string) (uint64, *utils.GenericError)); ok {
		return returnFunc(id, accountId, deletedBy)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, string) uint64); ok {
		r0 = returnFunc(id, accountId, deletedBy)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, string) *utils.GenericError); ok {
		r1 = returnFunc(id, accountId, deletedBy)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_DeleteOneByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOneByID'
type MockJobExecutorService_DeleteOneByID_Call struct {
	*mock.Call
}

// DeleteOneByID is a helper method to define mock.On call
//   - id uint64
//   - accountId uint64
//   - deletedBy string
func (_e *MockJobExecutorService_Expecter) DeleteOneByID(id interface{}, accountId interface{}, deletedBy interface{}) *MockJobExecutorService_DeleteOneByID_Call {
	return &MockJobExecutorService_DeleteOneByID_Call{Call: _e.mock.On("DeleteOneByID", id, accountId, deletedBy)}
}

func (_c *MockJobExecutorService_DeleteOneByID_Call) Run(run func(id uint64, accountId uint64, deletedBy string)) *MockJobExecutorService_DeleteOneByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_DeleteOneByID_Call) Return(v uint64, genericError *utils.GenericError) *MockJobExecutorService_DeleteOneByID_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockJobExecutorService_DeleteOneByID_Call) RunAndReturn(run func(id uint64, accountId uint64, deletedBy string) (uint64, *utils.GenericError)) *MockJobExecutorService_DeleteOneByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllLocalQuotaAllocations provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) GetAllLocalQuotaAllocations() map[uint64]uint64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllLocalQuotaAllocations")
	}

	var r0 map[uint64]uint64
	if returnFunc, ok := ret.Get(0).(func() map[uint64]uint64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]uint64)
		}
	}
	return r0
}

// MockJobExecutorService_GetAllLocalQuotaAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllLocalQuotaAllocations'
type MockJobExecutorService_GetAllLocalQuotaAllocations_Call struct {
	*mock.Call
}

// GetAllLocalQuotaAllocations is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) GetAllLocalQuotaAllocations() *MockJobExecutorService_GetAllLocalQuotaAllocations_Call {
	return &MockJobExecutorService_GetAllLocalQuotaAllocations_Call{Call: _e.mock.On("GetAllLocalQuotaAllocations")}
}

func (_c *MockJobExecutorService_GetAllLocalQuotaAllocations_Call) Run(run func()) *MockJobExecutorService_GetAllLocalQuotaAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_GetAllLocalQuotaAllocations_Call) Return(uint64ToUint64 map[uint64]uint64) *MockJobExecutorService_GetAllLocalQuotaAllocations_Call {
	_c.Call.Return(uint64ToUint64)
	return _c
}

func (_c *MockJobExecutorService_GetAllLocalQuotaAllocations_Call) RunAndReturn(run func() map[uint64]uint64) *MockJobExecutorService_GetAllLocalQuotaAllocations_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionsCache provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) GetExecutionsCache() *sync.Map {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionsCache")
	}

	var r0 *sync.Map
	if returnFunc, ok := ret.Get(0).(func() *sync.Map); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sync.Map)
		}
	}
	return r0
}

// MockJobExecutorService_GetExecutionsCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionsCache'
type MockJobExecutorService_GetExecutionsCache_Call struct {
	*mock.Call
}

// GetExecutionsCache is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) GetExecutionsCache() *MockJobExecutorService_GetExecutionsCache_Call {
	return &MockJobExecutorService_GetExecutionsCache_Call{Call: _e.mock.On("GetExecutionsCache")}
}

func (_c *MockJobExecutorService_GetExecutionsCache_Call) Run(run func()) *MockJobExecutorService_GetExecutionsCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_GetExecutionsCache_Call) Return(mapParam *sync.Map) *MockJobExecutorService_GetExecutionsCache_Call {
	_c.Call.Return(mapParam)
	return _c
}

func (_c *MockJobExecutorService_GetExecutionsCache_Call) RunAndReturn(run func() *sync.Map) *MockJobExecutorService_GetExecutionsCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetLocalQuotaRemaining provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) GetLocalQuotaRemaining(accountId uint64) (uint64, bool) {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetLocalQuotaRemaining")
	}

	var r0 uint64
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(uint64) (uint64, bool)); ok {
		return returnFunc(accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = returnFunc(accountId)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) bool); ok {
		r1 = returnFunc(accountId)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockJobExecutorService_GetLocalQuotaRemaining_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLocalQuotaRemaining'
type MockJobExecutorService_GetLocalQuotaRemaining_Call struct {
	*mock.Call
}

// GetLocalQuotaRemaining is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockJobExecutorService_Expecter) GetLocalQuotaRemaining(accountId interface{}) *MockJobExecutorService_GetLocalQuotaRemaining_Call {
	return &MockJobExecutorService_GetLocalQuotaRemaining_Call{Call: _e.mock.On("GetLocalQuotaRemaining", accountId)}
}

func (_c *MockJobExecutorService_GetLocalQuotaRemaining_Call) Run(run func(accountId uint64)) *MockJobExecutorService_GetLocalQuotaRemaining_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_GetLocalQuotaRemaining_Call) Return(v uint64, b bool) *MockJobExecutorService_GetLocalQuotaRemaining_Call {
	_c.Call.Return(v, b)
	return _c
}

func (_c *MockJobExecutorService_GetLocalQuotaRemaining_Call) RunAndReturn(run func(accountId uint64) (uint64, bool)) *MockJobExecutorService_GetLocalQuotaRemaining_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeIsLeader provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) GetNodeIsLeader() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNodeIsLeader")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockJobExecutorService_GetNodeIsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeIsLeader'
type MockJobExecutorService_GetNodeIsLeader_Call struct {
	*mock.Call
}

// GetNodeIsLeader is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) GetNodeIsLeader() *MockJobExecutorService_GetNodeIsLeader_Call {
	return &MockJobExecutorService_GetNodeIsLeader_Call{Call: _e.mock.On("GetNodeIsLeader")}
}

func (_c *MockJobExecutorService_GetNodeIsLeader_Call) Run(run func()) *MockJobExecutorService_GetNodeIsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_GetNodeIsLeader_Call) Return(b bool) *MockJobExecutorService_GetNodeIsLeader_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockJobExecutorService_GetNodeIsLeader_Call) RunAndReturn(run func() bool) *MockJobExecutorService_GetNodeIsLeader_Call {
	_c.Call.Return(run)
	return _c
}

// GetOneByID provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) GetOneByID(id uint64, accountId uint64) (*models.JobExecutor, *utils.GenericError) {
	ret := _mock.Called(id, accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetOneByID")
	}

	var r0 *models.JobExecutor
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*models.JobExecutor, *utils.GenericError)); ok {
		return returnFunc(id, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *models.JobExecutor); ok {
		r0 = returnFunc(id, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.JobExecutor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) *utils.GenericError); ok {
		r1 = returnFunc(id, accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_GetOneByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOneByID'
type MockJobExecutorService_GetOneByID_Call struct {
	*mock.Call
}

// GetOneByID is a helper method to define mock.On call
//   - id uint64
//   - accountId uint64
func (_e *MockJobExecutorService_Expecter) GetOneByID(id interface{}, accountId interface{}) *MockJobExecutorService_GetOneByID_Call {
	return &MockJobExecutorService_GetOneByID_Call{Call: _e.mock.On("GetOneByID", id, accountId)}
}

func (_c *MockJobExecutorService_GetOneByID_Call) Run(run func(id uint64, accountId uint64)) *MockJobExecutorService_GetOneByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_GetOneByID_Call) Return(jobExecutor *models.JobExecutor, genericError *utils.GenericError) *MockJobExecutorService_GetOneByID_Call {
	_c.Call.Return(jobExecutor, genericError)
	return _c
}

func (_c *MockJobExecutorService_GetOneByID_Call) RunAndReturn(run func(id uint64, accountId uint64) (*models.JobExecutor, *utils.GenericError)) *MockJobExecutorService_GetOneByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetScheduleQueue provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) GetScheduleQueue() models.ScheduleQueue {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetScheduleQueue")
	}

	var r0 models.ScheduleQueue
	if returnFunc, ok := ret.Get(0).(func() models.ScheduleQueue); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(models.ScheduleQueue)
		}
	}
	return r0
}

// MockJobExecutorService_GetScheduleQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduleQueue'
type MockJobExecutorService_GetScheduleQueue_Call struct {
	*mock.Call
}

// GetScheduleQueue is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) GetScheduleQueue() *MockJobExecutorService_GetScheduleQueue_Call {
	return &MockJobExecutorService_GetScheduleQueue_Call{Call: _e.mock.On("GetScheduleQueue")}
}

func (_c *MockJobExecutorService_GetScheduleQueue_Call) Run(run func()) *MockJobExecutorService_GetScheduleQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_GetScheduleQueue_Call) Return(scheduleQueue models.ScheduleQueue) *MockJobExecutorService_GetScheduleQueue_Call {
	_c.Call.Return(scheduleQueue)
	return _c
}

func (_c *MockJobExecutorService_GetScheduleQueue_Call) RunAndReturn(run func() models.ScheduleQueue) *MockJobExecutorService_GetScheduleQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetSingleNodeMode provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) GetSingleNodeMode() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetSingleNodeMode")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockJobExecutorService_GetSingleNodeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSingleNodeMode'
type MockJobExecutorService_GetSingleNodeMode_Call struct {
	*mock.Call
}

// GetSingleNodeMode is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) GetSingleNodeMode() *MockJobExecutorService_GetSingleNodeMode_Call {
	return &MockJobExecutorService_GetSingleNodeMode_Call{Call: _e.mock.On("GetSingleNodeMode")}
}

func (_c *MockJobExecutorService_GetSingleNodeMode_Call) Run(run func()) *MockJobExecutorService_GetSingleNodeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_GetSingleNodeMode_Call) Return(b bool) *MockJobExecutorService_GetSingleNodeMode_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockJobExecutorService_GetSingleNodeMode_Call) RunAndReturn(run func() bool) *MockJobExecutorService_GetSingleNodeMode_Call {
	_c.Call.Return(run)
	return _c
}

// GetUncommittedLogs provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) GetUncommittedLogs() []models.JobExecutionLog {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUncommittedLogs")
	}

	var r0 []models.JobExecutionLog
	if returnFunc, ok := ret.Get(0).(func() []models.JobExecutionLog); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobExecutionLog)
		}
	}
	return r0
}

// MockJobExecutorService_GetUncommittedLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUncommittedLogs'
type MockJobExecutorService_GetUncommittedLogs_Call struct {
	*mock.Call
}

// GetUncommittedLogs is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) GetUncommittedLogs() *MockJobExecutorService_GetUncommittedLogs_Call {
	return &MockJobExecutorService_GetUncommittedLogs_Call{Call: _e.mock.On("GetUncommittedLogs")}
}

func (_c *MockJobExecutorService_GetUncommittedLogs_Call) Run(run func()) *MockJobExecutorService_GetUncommittedLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_GetUncommittedLogs_Call) Return(jobExecutionLogs []models.JobExecutionLog) *MockJobExecutorService_GetUncommittedLogs_Call {
	_c.Call.Return(jobExecutionLogs)
	return _c
}

func (_c *MockJobExecutorService_GetUncommittedLogs_Call) RunAndReturn(run func() []models.JobExecutionLog) *MockJobExecutorService_GetUncommittedLogs_Call {
	_c.Call.Return(run)
	return _c
}

// ListJobExecutors provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) ListJobExecutors(offset uint64, limit uint64, orderByColumn string, orderByDirection string, accountId uint64) (*models.PaginatedJobExecutor, *utils.GenericError) {
	ret := _mock.Called(offset, limit, orderByColumn, orderByDirection, accountId)

	if len(ret) == 0 {
		panic("no return value specified for ListJobExecutors")
	}

	var r0 *models.PaginatedJobExecutor
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, string, string, uint64) (*models.PaginatedJobExecutor, *utils.GenericError)); ok {
		return returnFunc(offset, limit, orderByColumn, orderByDirection, accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64, string, string, uint64) *models.PaginatedJobExecutor); ok {
		r0 = returnFunc(offset, limit, orderByColumn, orderByDirection, accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PaginatedJobExecutor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64, string, string, uint64) *utils.GenericError); ok {
		r1 = returnFunc(offset, limit, orderByColumn, orderByDirection, accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_ListJobExecutors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJobExecutors'
type MockJobExecutorService_ListJobExecutors_Call struct {
	*mock.Call
}

// ListJobExecutors is a helper method to define mock.On call
//   - offset uint64
//   - limit uint64
//   - orderByColumn string
//   - orderByDirection string
//   - accountId uint64
func (_e *MockJobExecutorService_Expecter) ListJobExecutors(offset interface{}, limit interface{}, orderByColumn interface{}, orderByDirection interface{}, accountId interface{}) *MockJobExecutorService_ListJobExecutors_Call {
	return &MockJobExecutorService_ListJobExecutors_Call{Call: _e.mock.On("ListJobExecutors", offset, limit, orderByColumn, orderByDirection, accountId)}
}

func (_c *MockJobExecutorService_ListJobExecutors_Call) Run(run func(offset uint64, limit uint64, orderByColumn string, orderByDirection string, accountId uint64)) *MockJobExecutorService_ListJobExecutors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_ListJobExecutors_Call) Return(paginatedJobExecutor *models.PaginatedJobExecutor, genericError *utils.GenericError) *MockJobExecutorService_ListJobExecutors_Call {
	_c.Call.Return(paginatedJobExecutor, genericError)
	return _c
}

func (_c *MockJobExecutorService_ListJobExecutors_Call) RunAndReturn(run func(offset uint64, limit uint64, orderByColumn string, orderByDirection string, accountId uint64) (*models.PaginatedJobExecutor, *utils.GenericError)) *MockJobExecutorService_ListJobExecutors_Call {
	_c.Call.Return(run)
	return _c
}

// ListenForJobsToInvokeV1 provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) ListenForJobsToInvokeV1() {
	_mock.Called()
	return
}

// MockJobExecutorService_ListenForJobsToInvokeV1_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenForJobsToInvokeV1'
type MockJobExecutorService_ListenForJobsToInvokeV1_Call struct {
	*mock.Call
}

// ListenForJobsToInvokeV1 is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) ListenForJobsToInvokeV1() *MockJobExecutorService_ListenForJobsToInvokeV1_Call {
	return &MockJobExecutorService_ListenForJobsToInvokeV1_Call{Call: _e.mock.On("ListenForJobsToInvokeV1")}
}

func (_c *MockJobExecutorService_ListenForJobsToInvokeV1_Call) Run(run func()) *MockJobExecutorService_ListenForJobsToInvokeV1_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_ListenForJobsToInvokeV1_Call) Return() *MockJobExecutorService_ListenForJobsToInvokeV1_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_ListenForJobsToInvokeV1_Call) RunAndReturn(run func()) *MockJobExecutorService_ListenForJobsToInvokeV1_Call {
	_c.Run(run)
	return _c
}

// QueueExecutions provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) QueueExecutions(lastInsertedId int64, rowsAffected int64) {
	_mock.Called(lastInsertedId, rowsAffected)
	return
}

// MockJobExecutorService_QueueExecutions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueueExecutions'
type MockJobExecutorService_QueueExecutions_Call struct {
	*mock.Call
}

// QueueExecutions is a helper method to define mock.On call
//   - lastInsertedId int64
//   - rowsAffected int64
func (_e *MockJobExecutorService_Expecter) QueueExecutions(lastInsertedId interface{}, rowsAffected interface{}) *MockJobExecutorService_QueueExecutions_Call {
	return &MockJobExecutorService_QueueExecutions_Call{Call: _e.mock.On("QueueExecutions", lastInsertedId, rowsAffected)}
}

func (_c *MockJobExecutorService_QueueExecutions_Call) Run(run func(lastInsertedId int64, rowsAffected int64)) *MockJobExecutorService_QueueExecutions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_QueueExecutions_Call) Return() *MockJobExecutorService_QueueExecutions_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_QueueExecutions_Call) RunAndReturn(run func(lastInsertedId int64, rowsAffected int64)) *MockJobExecutorService_QueueExecutions_Call {
	_c.Run(run)
	return _c
}

// ResetLocalQuotaAllocations provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) ResetLocalQuotaAllocations() {
	_mock.Called()
	return
}

// MockJobExecutorService_ResetLocalQuotaAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetLocalQuotaAllocations'
type MockJobExecutorService_ResetLocalQuotaAllocations_Call struct {
	*mock.Call
}

// ResetLocalQuotaAllocations is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) ResetLocalQuotaAllocations() *MockJobExecutorService_ResetLocalQuotaAllocations_Call {
	return &MockJobExecutorService_ResetLocalQuotaAllocations_Call{Call: _e.mock.On("ResetLocalQuotaAllocations")}
}

func (_c *MockJobExecutorService_ResetLocalQuotaAllocations_Call) Run(run func()) *MockJobExecutorService_ResetLocalQuotaAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_ResetLocalQuotaAllocations_Call) Return() *MockJobExecutorService_ResetLocalQuotaAllocations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_ResetLocalQuotaAllocations_Call) RunAndReturn(run func()) *MockJobExecutorService_ResetLocalQuotaAllocations_Call {
	_c.Run(run)
	return _c
}

// ScheduleJobs provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) ScheduleJobs(jobs []models.Job) {
	_mock.Called(jobs)
	return
}

// MockJobExecutorService_ScheduleJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ScheduleJobs'
type MockJobExecutorService_ScheduleJobs_Call struct {
	*mock.Call
}

// ScheduleJobs is a helper method to define mock.On call
//   - jobs []models.Job
func (_e *MockJobExecutorService_Expecter) ScheduleJobs(jobs interface{}) *MockJobExecutorService_ScheduleJobs_Call {
	return &MockJobExecutorService_ScheduleJobs_Call{Call: _e.mock.On("ScheduleJobs", jobs)}
}

func (_c *MockJobExecutorService_ScheduleJobs_Call) Run(run func(jobs []models.Job)) *MockJobExecutorService_ScheduleJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []models.Job
		if args[0] != nil {
			arg0 = args[0].([]models.Job)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_ScheduleJobs_Call) Return() *MockJobExecutorService_ScheduleJobs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_ScheduleJobs_Call) RunAndReturn(run func(jobs []models.Job)) *MockJobExecutorService_ScheduleJobs_Call {
	_c.Run(run)
	return _c
}

// SetNodeIsLeader provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) SetNodeIsLeader(nodeIsLeader bool) {
	_mock.Called(nodeIsLeader)
	return
}

// MockJobExecutorService_SetNodeIsLeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNodeIsLeader'
type MockJobExecutorService_SetNodeIsLeader_Call struct {
	*mock.Call
}

// SetNodeIsLeader is a helper method to define mock.On call
//   - nodeIsLeader bool
func (_e *MockJobExecutorService_Expecter) SetNodeIsLeader(nodeIsLeader interface{}) *MockJobExecutorService_SetNodeIsLeader_Call {
	return &MockJobExecutorService_SetNodeIsLeader_Call{Call: _e.mock.On("SetNodeIsLeader", nodeIsLeader)}
}

func (_c *MockJobExecutorService_SetNodeIsLeader_Call) Run(run func(nodeIsLeader bool)) *MockJobExecutorService_SetNodeIsLeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_SetNodeIsLeader_Call) Return() *MockJobExecutorService_SetNodeIsLeader_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_SetNodeIsLeader_Call) RunAndReturn(run func(nodeIsLeader bool)) *MockJobExecutorService_SetNodeIsLeader_Call {
	_c.Run(run)
	return _c
}

// SetNotifyAccountExhaustionCallback provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) SetNotifyAccountExhaustionCallback(callback func(accountId uint64) error) {
	_mock.Called(callback)
	return
}

// MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNotifyAccountExhaustionCallback'
type MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call struct {
	*mock.Call
}

// SetNotifyAccountExhaustionCallback is a helper method to define mock.On call
//   - callback func(accountId uint64) error
func (_e *MockJobExecutorService_Expecter) SetNotifyAccountExhaustionCallback(callback interface{}) *MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call {
	return &MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call{Call: _e.mock.On("SetNotifyAccountExhaustionCallback", callback)}
}

func (_c *MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call) Run(run func(callback func(accountId uint64) error)) *MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(accountId uint64) error
		if args[0] != nil {
			arg0 = args[0].(func(accountId uint64) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call) Return() *MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call) RunAndReturn(run func(callback func(accountId uint64) error)) *MockJobExecutorService_SetNotifyAccountExhaustionCallback_Call {
	_c.Run(run)
	return _c
}

// SetNotifyJobFailureCallback provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) SetNotifyJobFailureCallback(callback func(job models.Job, failCount uint64, executionVersion uint64) error) {
	_mock.Called(callback)
	return
}

// MockJobExecutorService_SetNotifyJobFailureCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetNotifyJobFailureCallback'
type MockJobExecutorService_SetNotifyJobFailureCallback_Call struct {
	*mock.Call
}

// SetNotifyJobFailureCallback is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) SetNotifyJobFailureCallback(callback interface{}) *MockJobExecutorService_SetNotifyJobFailureCallback_Call {
	return &MockJobExecutorService_SetNotifyJobFailureCallback_Call{Call: _e.mock.On("SetNotifyJobFailureCallback", callback)}
}

func (_c *MockJobExecutorService_SetNotifyJobFailureCallback_Call) Run(run func(callback func(job models.Job, failCount uint64, executionVersion uint64) error)) *MockJobExecutorService_SetNotifyJobFailureCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(job models.Job, failCount uint64, executionVersion uint64) error
		if args[0] != nil {
			arg0 = args[0].(func(job models.Job, failCount uint64, executionVersion uint64) error)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockJobExecutorService_SetNotifyJobFailureCallback_Call) Return() *MockJobExecutorService_SetNotifyJobFailureCallback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_SetNotifyJobFailureCallback_Call) RunAndReturn(run func(callback func(job models.Job, failCount uint64, executionVersion uint64) error)) *MockJobExecutorService_SetNotifyJobFailureCallback_Call {
	_c.Run(run)
	return _c
}

// SetSingleNodeMode provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) SetSingleNodeMode(singleNodeMode bool) {
	_mock.Called(singleNodeMode)
	return
}

// MockJobExecutorService_SetSingleNodeMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSingleNodeMode'
type MockJobExecutorService_SetSingleNodeMode_Call struct {
	*mock.Call
}

// SetSingleNodeMode is a helper method to define mock.On call
//   - singleNodeMode bool
func (_e *MockJobExecutorService_Expecter) SetSingleNodeMode(singleNodeMode interface{}) *MockJobExecutorService_SetSingleNodeMode_Call {
	return &MockJobExecutorService_SetSingleNodeMode_Call{Call: _e.mock.On("SetSingleNodeMode", singleNodeMode)}
}

func (_c *MockJobExecutorService_SetSingleNodeMode_Call) Run(run func(singleNodeMode bool)) *MockJobExecutorService_SetSingleNodeMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_SetSingleNodeMode_Call) Return() *MockJobExecutorService_SetSingleNodeMode_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_SetSingleNodeMode_Call) RunAndReturn(run func(singleNodeMode bool)) *MockJobExecutorService_SetSingleNodeMode_Call {
	_c.Run(run)
	return _c
}

// SetAlertPublisher provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) SetAlertPublisher(publisher alerts.Publisher) {
	_mock.Called(publisher)
	return
}

// MockJobExecutorService_SetAlertPublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAlertPublisher'
type MockJobExecutorService_SetAlertPublisher_Call struct {
	*mock.Call
}

// SetAlertPublisher is a helper method to define mock.On call
//   - publisher alerts.Publisher
func (_e *MockJobExecutorService_Expecter) SetAlertPublisher(publisher interface{}) *MockJobExecutorService_SetAlertPublisher_Call {
	return &MockJobExecutorService_SetAlertPublisher_Call{Call: _e.mock.On("SetAlertPublisher", publisher)}
}

func (_c *MockJobExecutorService_SetAlertPublisher_Call) Run(run func(publisher alerts.Publisher)) *MockJobExecutorService_SetAlertPublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 alerts.Publisher
		if args[0] != nil {
			arg0 = args[0].(alerts.Publisher)
		}
		run(arg0)
	})
	return _c
}

func (_c *MockJobExecutorService_SetAlertPublisher_Call) Return() *MockJobExecutorService_SetAlertPublisher_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_SetAlertPublisher_Call) RunAndReturn(run func(publisher alerts.Publisher)) *MockJobExecutorService_SetAlertPublisher_Call {
	_c.Run(run)
	return _c
}

// SetUpdateJobOnLeaderCallback provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) SetUpdateJobOnLeaderCallback(callback func(job models.Job) error) {
	_mock.Called(callback)
	return
}

// MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUpdateJobOnLeaderCallback'
type MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call struct {
	*mock.Call
}

// SetUpdateJobOnLeaderCallback is a helper method to define mock.On call
//   - callback func(job models.Job) error
func (_e *MockJobExecutorService_Expecter) SetUpdateJobOnLeaderCallback(callback interface{}) *MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call {
	return &MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call{Call: _e.mock.On("SetUpdateJobOnLeaderCallback", callback)}
}

func (_c *MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call) Run(run func(callback func(job models.Job) error)) *MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func(job models.Job) error
		if args[0] != nil {
			arg0 = args[0].(func(job models.Job) error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call) Return() *MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call) RunAndReturn(run func(callback func(job models.Job) error)) *MockJobExecutorService_SetUpdateJobOnLeaderCallback_Call {
	_c.Run(run)
	return _c
}

// StopAll provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) StopAll() {
	_mock.Called()
	return
}

// MockJobExecutorService_StopAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopAll'
type MockJobExecutorService_StopAll_Call struct {
	*mock.Call
}

// StopAll is a helper method to define mock.On call
func (_e *MockJobExecutorService_Expecter) StopAll() *MockJobExecutorService_StopAll_Call {
	return &MockJobExecutorService_StopAll_Call{Call: _e.mock.On("StopAll")}
}

func (_c *MockJobExecutorService_StopAll_Call) Run(run func()) *MockJobExecutorService_StopAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockJobExecutorService_StopAll_Call) Return() *MockJobExecutorService_StopAll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_StopAll_Call) RunAndReturn(run func()) *MockJobExecutorService_StopAll_Call {
	_c.Run(run)
	return _c
}

// UpdateLocalQuotaAllocations provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) UpdateLocalQuotaAllocations(accountAllocations map[uint64]uint64) {
	_mock.Called(accountAllocations)
	return
}

// MockJobExecutorService_UpdateLocalQuotaAllocations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateLocalQuotaAllocations'
type MockJobExecutorService_UpdateLocalQuotaAllocations_Call struct {
	*mock.Call
}

// UpdateLocalQuotaAllocations is a helper method to define mock.On call
//   - accountAllocations map[uint64]uint64
func (_e *MockJobExecutorService_Expecter) UpdateLocalQuotaAllocations(accountAllocations interface{}) *MockJobExecutorService_UpdateLocalQuotaAllocations_Call {
	return &MockJobExecutorService_UpdateLocalQuotaAllocations_Call{Call: _e.mock.On("UpdateLocalQuotaAllocations", accountAllocations)}
}

func (_c *MockJobExecutorService_UpdateLocalQuotaAllocations_Call) Run(run func(accountAllocations map[uint64]uint64)) *MockJobExecutorService_UpdateLocalQuotaAllocations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[uint64]uint64
		if args[0] != nil {
			arg0 = args[0].(map[uint64]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_UpdateLocalQuotaAllocations_Call) Return() *MockJobExecutorService_UpdateLocalQuotaAllocations_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_UpdateLocalQuotaAllocations_Call) RunAndReturn(run func(accountAllocations map[uint64]uint64)) *MockJobExecutorService_UpdateLocalQuotaAllocations_Call {
	_c.Run(run)
	return _c
}

// UpdateOneBy provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) UpdateOneBy(executor models.JobExecutor) (uint64, *utils.GenericError) {
	ret := _mock.Called(executor)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOneBy")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(models.JobExecutor) (uint64, *utils.GenericError)); ok {
		return returnFunc(executor)
	}
	if returnFunc, ok := ret.Get(0).(func(models.JobExecutor) uint64); ok {
		r0 = returnFunc(executor)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(models.JobExecutor) *utils.GenericError); ok {
		r1 = returnFunc(executor)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockJobExecutorService_UpdateOneBy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOneBy'
type MockJobExecutorService_UpdateOneBy_Call struct {
	*mock.Call
}

// UpdateOneBy is a helper method to define mock.On call
//   - executor models.JobExecutor
func (_e *MockJobExecutorService_Expecter) UpdateOneBy(executor interface{}) *MockJobExecutorService_UpdateOneBy_Call {
	return &MockJobExecutorService_UpdateOneBy_Call{Call: _e.mock.On("UpdateOneBy", executor)}
}

func (_c *MockJobExecutorService_UpdateOneBy_Call) Run(run func(executor models.JobExecutor)) *MockJobExecutorService_UpdateOneBy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.JobExecutor
		if args[0] != nil {
			arg0 = args[0].(models.JobExecutor)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_UpdateOneBy_Call) Return(v uint64, genericError *utils.GenericError) *MockJobExecutorService_UpdateOneBy_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockJobExecutorService_UpdateOneBy_Call) RunAndReturn(run func(executor models.JobExecutor) (uint64, *utils.GenericError)) *MockJobExecutorService_UpdateOneBy_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRaft provides a mock function for the type MockJobExecutorService
func (_mock *MockJobExecutorService) UpdateRaft(rft *raft.Raft) {
	_mock.Called(rft)
	return
}

// MockJobExecutorService_UpdateRaft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRaft'
type MockJobExecutorService_UpdateRaft_Call struct {
	*mock.Call
}

// UpdateRaft is a helper method to define mock.On call
//   - rft *raft.Raft
func (_e *MockJobExecutorService_Expecter) UpdateRaft(rft interface{}) *MockJobExecutorService_UpdateRaft_Call {
	return &MockJobExecutorService_UpdateRaft_Call{Call: _e.mock.On("UpdateRaft", rft)}
}

func (_c *MockJobExecutorService_UpdateRaft_Call) Run(run func(rft *raft.Raft)) *MockJobExecutorService_UpdateRaft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *raft.Raft
		if args[0] != nil {
			arg0 = args[0].(*raft.Raft)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockJobExecutorService_UpdateRaft_Call) Return() *MockJobExecutorService_UpdateRaft_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockJobExecutorService_UpdateRaft_Call) RunAndReturn(run func(rft *raft.Raft)) *MockJobExecutorService_UpdateRaft_Call {
	_c.Run(run)
	return _c
}
