// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"scheduler0/pkg/models"
	"scheduler0/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountJobExecutionsCountRepo creates a new instance of MockAccountJobExecutionsCountRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountJobExecutionsCountRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountJobExecutionsCountRepo {
	mock := &MockAccountJobExecutionsCountRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountJobExecutionsCountRepo is an autogenerated mock type for the AccountJobExecutionsCountRepo type
type MockAccountJobExecutionsCountRepo struct {
	mock.Mock
}

type MockAccountJobExecutionsCountRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountJobExecutionsCountRepo) EXPECT() *MockAccountJobExecutionsCountRepo_Expecter {
	return &MockAccountJobExecutionsCountRepo_Expecter{mock: &_m.Mock}
}

// AddTokens provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) AddTokens(accountId uint64, delta uint64) (uint64, *utils.GenericError) {
	ret := _mock.Called(accountId, delta)

	if len(ret) == 0 {
		panic("no return value specified for AddTokens")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (uint64, *utils.GenericError)); ok {
		return returnFunc(accountId, delta)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) uint64); ok {
		r0 = returnFunc(accountId, delta)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountId, delta)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountJobExecutionsCountRepo_AddTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTokens'
type MockAccountJobExecutionsCountRepo_AddTokens_Call struct {
	*mock.Call
}

// AddTokens is a helper method to define mock.On call
//   - accountId uint64
//   - delta uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) AddTokens(accountId interface{}, delta interface{}) *MockAccountJobExecutionsCountRepo_AddTokens_Call {
	return &MockAccountJobExecutionsCountRepo_AddTokens_Call{Call: _e.mock.On("AddTokens", accountId, delta)}
}

func (_c *MockAccountJobExecutionsCountRepo_AddTokens_Call) Run(run func(accountId uint64, delta uint64)) *MockAccountJobExecutionsCountRepo_AddTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_AddTokens_Call) Return(v uint64, genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_AddTokens_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_AddTokens_Call) RunAndReturn(run func(accountId uint64, delta uint64) (uint64, *utils.GenericError)) *MockAccountJobExecutionsCountRepo_AddTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) Create(accountId uint64, count uint64) (*models.AccountJobExecutionsCount, *utils.GenericError) {
	ret := _mock.Called(accountId, count)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.AccountJobExecutionsCount
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (*models.AccountJobExecutionsCount, *utils.GenericError)); ok {
		return returnFunc(accountId, count)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *models.AccountJobExecutionsCount); ok {
		r0 = returnFunc(accountId, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccountJobExecutionsCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountId, count)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountJobExecutionsCountRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAccountJobExecutionsCountRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - accountId uint64
//   - count uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) Create(accountId interface{}, count interface{}) *MockAccountJobExecutionsCountRepo_Create_Call {
	return &MockAccountJobExecutionsCountRepo_Create_Call{Call: _e.mock.On("Create", accountId, count)}
}

func (_c *MockAccountJobExecutionsCountRepo_Create_Call) Run(run func(accountId uint64, count uint64)) *MockAccountJobExecutionsCountRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_Create_Call) Return(accountJobExecutionsCount *models.AccountJobExecutionsCount, genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_Create_Call {
	_c.Call.Return(accountJobExecutionsCount, genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_Create_Call) RunAndReturn(run func(accountId uint64, count uint64) (*models.AccountJobExecutionsCount, *utils.GenericError)) *MockAccountJobExecutionsCountRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeductTokens provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) DeductTokens(accountId uint64, amount uint64) (bool, uint64, *utils.GenericError) {
	ret := _mock.Called(accountId, amount)

	if len(ret) == 0 {
		panic("no return value specified for DeductTokens")
	}

	var r0 bool
	var r1 uint64
	var r2 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (bool, uint64, *utils.GenericError)); ok {
		return returnFunc(accountId, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) bool); ok {
		r0 = returnFunc(accountId, amount)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) uint64); ok {
		r1 = returnFunc(accountId, amount)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(uint64, uint64) *utils.GenericError); ok {
		r2 = returnFunc(accountId, amount)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*utils.GenericError)
		}
	}
	return r0, r1, r2
}

// MockAccountJobExecutionsCountRepo_DeductTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductTokens'
type MockAccountJobExecutionsCountRepo_DeductTokens_Call struct {
	*mock.Call
}

// DeductTokens is a helper method to define mock.On call
//   - accountId uint64
//   - amount uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) DeductTokens(accountId interface{}, amount interface{}) *MockAccountJobExecutionsCountRepo_DeductTokens_Call {
	return &MockAccountJobExecutionsCountRepo_DeductTokens_Call{Call: _e.mock.On("DeductTokens", accountId, amount)}
}

func (_c *MockAccountJobExecutionsCountRepo_DeductTokens_Call) Run(run func(accountId uint64, amount uint64)) *MockAccountJobExecutionsCountRepo_DeductTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_DeductTokens_Call) Return(b bool, v uint64, genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_DeductTokens_Call {
	_c.Call.Return(b, v, genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_DeductTokens_Call) RunAndReturn(run func(accountId uint64, amount uint64) (bool, uint64, *utils.GenericError)) *MockAccountJobExecutionsCountRepo_DeductTokens_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByAccountId provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) DeleteByAccountId(accountId uint64) *utils.GenericError {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByAccountId")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByAccountId'
type MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call struct {
	*mock.Call
}

// DeleteByAccountId is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) DeleteByAccountId(accountId interface{}) *MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call {
	return &MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call{Call: _e.mock.On("DeleteByAccountId", accountId)}
}

func (_c *MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call) Run(run func(accountId uint64)) *MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call) Return(genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call) RunAndReturn(run func(accountId uint64) *utils.GenericError) *MockAccountJobExecutionsCountRepo_DeleteByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccountsWithZeroExecutionCount provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) GetAccountsWithZeroExecutionCount() ([]uint64, *utils.GenericError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAccountsWithZeroExecutionCount")
	}

	var r0 []uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func() ([]uint64, *utils.GenericError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []uint64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *utils.GenericError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccountsWithZeroExecutionCount'
type MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call struct {
	*mock.Call
}

// GetAccountsWithZeroExecutionCount is a helper method to define mock.On call
func (_e *MockAccountJobExecutionsCountRepo_Expecter) GetAccountsWithZeroExecutionCount() *MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call {
	return &MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call{Call: _e.mock.On("GetAccountsWithZeroExecutionCount")}
}

func (_c *MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call) Run(run func()) *MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call) Return(uint64s []uint64, genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call {
	_c.Call.Return(uint64s, genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call) RunAndReturn(run func() ([]uint64, *utils.GenericError)) *MockAccountJobExecutionsCountRepo_GetAccountsWithZeroExecutionCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllExpiredResetDates provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) GetAllExpiredResetDates() ([]models.AccountJobExecutionsCount, *utils.GenericError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllExpiredResetDates")
	}

	var r0 []models.AccountJobExecutionsCount
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func() ([]models.AccountJobExecutionsCount, *utils.GenericError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []models.AccountJobExecutionsCount); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.AccountJobExecutionsCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *utils.GenericError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllExpiredResetDates'
type MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call struct {
	*mock.Call
}

// GetAllExpiredResetDates is a helper method to define mock.On call
func (_e *MockAccountJobExecutionsCountRepo_Expecter) GetAllExpiredResetDates() *MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call {
	return &MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call{Call: _e.mock.On("GetAllExpiredResetDates")}
}

func (_c *MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call) Run(run func()) *MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call) Return(accountJobExecutionsCounts []models.AccountJobExecutionsCount, genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call {
	_c.Call.Return(accountJobExecutionsCounts, genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call) RunAndReturn(run func() ([]models.AccountJobExecutionsCount, *utils.GenericError)) *MockAccountJobExecutionsCountRepo_GetAllExpiredResetDates_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAccountId provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) GetByAccountId(accountId uint64) (*models.AccountJobExecutionsCount, *utils.GenericError) {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetByAccountId")
	}

	var r0 *models.AccountJobExecutionsCount
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (*models.AccountJobExecutionsCount, *utils.GenericError)); ok {
		return returnFunc(accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *models.AccountJobExecutionsCount); ok {
		r0 = returnFunc(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccountJobExecutionsCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountJobExecutionsCountRepo_GetByAccountId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAccountId'
type MockAccountJobExecutionsCountRepo_GetByAccountId_Call struct {
	*mock.Call
}

// GetByAccountId is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) GetByAccountId(accountId interface{}) *MockAccountJobExecutionsCountRepo_GetByAccountId_Call {
	return &MockAccountJobExecutionsCountRepo_GetByAccountId_Call{Call: _e.mock.On("GetByAccountId", accountId)}
}

func (_c *MockAccountJobExecutionsCountRepo_GetByAccountId_Call) Run(run func(accountId uint64)) *MockAccountJobExecutionsCountRepo_GetByAccountId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetByAccountId_Call) Return(accountJobExecutionsCount *models.AccountJobExecutionsCount, genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_GetByAccountId_Call {
	_c.Call.Return(accountJobExecutionsCount, genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetByAccountId_Call) RunAndReturn(run func(accountId uint64) (*models.AccountJobExecutionsCount, *utils.GenericError)) *MockAccountJobExecutionsCountRepo_GetByAccountId_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionCountsByAccountIds provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) GetExecutionCountsByAccountIds(accountIds []uint64) (map[uint64]uint64, *utils.GenericError) {
	ret := _mock.Called(accountIds)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionCountsByAccountIds")
	}

	var r0 map[uint64]uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func([]uint64) (map[uint64]uint64, *utils.GenericError)); ok {
		return returnFunc(accountIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint64) map[uint64]uint64); ok {
		r0 = returnFunc(accountIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountIds)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionCountsByAccountIds'
type MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call struct {
	*mock.Call
}

// GetExecutionCountsByAccountIds is a helper method to define mock.On call
//   - accountIds []uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) GetExecutionCountsByAccountIds(accountIds interface{}) *MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call {
	return &MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call{Call: _e.mock.On("GetExecutionCountsByAccountIds", accountIds)}
}

func (_c *MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call) Run(run func(accountIds []uint64)) *MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		if args[0] != nil {
			arg0 = args[0].([]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call) Return(uint64ToUint64 map[uint64]uint64, genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call {
	_c.Call.Return(uint64ToUint64, genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call) RunAndReturn(run func(accountIds []uint64) (map[uint64]uint64, *utils.GenericError)) *MockAccountJobExecutionsCountRepo_GetExecutionCountsByAccountIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokensByAccountIds provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) GetTokensByAccountIds(accountIds []uint64) (map[uint64]uint64, *utils.GenericError) {
	ret := _mock.Called(accountIds)

	if len(ret) == 0 {
		panic("no return value specified for GetTokensByAccountIds")
	}

	var r0 map[uint64]uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func([]uint64) (map[uint64]uint64, *utils.GenericError)); ok {
		return returnFunc(accountIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint64) map[uint64]uint64); ok {
		r0 = returnFunc(accountIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountIds)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokensByAccountIds'
type MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call struct {
	*mock.Call
}

// GetTokensByAccountIds is a helper method to define mock.On call
//   - accountIds []uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) GetTokensByAccountIds(accountIds interface{}) *MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call {
	return &MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call{Call: _e.mock.On("GetTokensByAccountIds", accountIds)}
}

func (_c *MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call) Run(run func(accountIds []uint64)) *MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		if args[0] != nil {
			arg0 = args[0].([]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call) Return(uint64ToUint64 map[uint64]uint64, genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call {
	_c.Call.Return(uint64ToUint64, genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call) RunAndReturn(run func(accountIds []uint64) (map[uint64]uint64, *utils.GenericError)) *MockAccountJobExecutionsCountRepo_GetTokensByAccountIds_Call {
	_c.Call.Return(run)
	return _c
}

// ResetExecutionCount provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) ResetExecutionCount(accountId uint64, count uint64) *utils.GenericError {
	ret := _mock.Called(accountId, count)

	if len(ret) == 0 {
		panic("no return value specified for ResetExecutionCount")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetExecutionCount'
type MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call struct {
	*mock.Call
}

// ResetExecutionCount is a helper method to define mock.On call
//   - accountId uint64
//   - count uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) ResetExecutionCount(accountId interface{}, count interface{}) *MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call {
	return &MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call{Call: _e.mock.On("ResetExecutionCount", accountId, count)}
}

func (_c *MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call) Run(run func(accountId uint64, count uint64)) *MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call) Return(genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call) RunAndReturn(run func(accountId uint64, count uint64) *utils.GenericError) *MockAccountJobExecutionsCountRepo_ResetExecutionCount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExecutionCount provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) UpdateExecutionCount(accountId uint64, count uint64) *utils.GenericError {
	ret := _mock.Called(accountId, count)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExecutionCount")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExecutionCount'
type MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call struct {
	*mock.Call
}

// UpdateExecutionCount is a helper method to define mock.On call
//   - accountId uint64
//   - count uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) UpdateExecutionCount(accountId interface{}, count interface{}) *MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call {
	return &MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call{Call: _e.mock.On("UpdateExecutionCount", accountId, count)}
}

func (_c *MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call) Run(run func(accountId uint64, count uint64)) *MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call) Return(genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call) RunAndReturn(run func(accountId uint64, count uint64) *utils.GenericError) *MockAccountJobExecutionsCountRepo_UpdateExecutionCount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTokens provides a mock function for the type MockAccountJobExecutionsCountRepo
func (_mock *MockAccountJobExecutionsCountRepo) UpdateTokens(accountId uint64, tokens uint64) *utils.GenericError {
	ret := _mock.Called(accountId, tokens)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTokens")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId, tokens)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountJobExecutionsCountRepo_UpdateTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTokens'
type MockAccountJobExecutionsCountRepo_UpdateTokens_Call struct {
	*mock.Call
}

// UpdateTokens is a helper method to define mock.On call
//   - accountId uint64
//   - tokens uint64
func (_e *MockAccountJobExecutionsCountRepo_Expecter) UpdateTokens(accountId interface{}, tokens interface{}) *MockAccountJobExecutionsCountRepo_UpdateTokens_Call {
	return &MockAccountJobExecutionsCountRepo_UpdateTokens_Call{Call: _e.mock.On("UpdateTokens", accountId, tokens)}
}

func (_c *MockAccountJobExecutionsCountRepo_UpdateTokens_Call) Run(run func(accountId uint64, tokens uint64)) *MockAccountJobExecutionsCountRepo_UpdateTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_UpdateTokens_Call) Return(genericError *utils.GenericError) *MockAccountJobExecutionsCountRepo_UpdateTokens_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountJobExecutionsCountRepo_UpdateTokens_Call) RunAndReturn(run func(accountId uint64, tokens uint64) *utils.GenericError) *MockAccountJobExecutionsCountRepo_UpdateTokens_Call {
	_c.Call.Return(run)
	return _c
}
