// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"scheduler0/pkg/models"
	"scheduler0/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountService creates a new instance of MockAccountService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountService {
	mock := &MockAccountService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountService is an autogenerated mock type for the AccountService type
type MockAccountService struct {
	mock.Mock
}

type MockAccountService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountService) EXPECT() *MockAccountService_Expecter {
	return &MockAccountService_Expecter{mock: &_m.Mock}
}

// AddAllFeatures provides a mock function for the type MockAccountService
func (_mock *MockAccountService) AddAllFeatures(accountId uint64) *utils.GenericError {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for AddAllFeatures")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountService_AddAllFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAllFeatures'
type MockAccountService_AddAllFeatures_Call struct {
	*mock.Call
}

// AddAllFeatures is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountService_Expecter) AddAllFeatures(accountId interface{}) *MockAccountService_AddAllFeatures_Call {
	return &MockAccountService_AddAllFeatures_Call{Call: _e.mock.On("AddAllFeatures", accountId)}
}

func (_c *MockAccountService_AddAllFeatures_Call) Run(run func(accountId uint64)) *MockAccountService_AddAllFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_AddAllFeatures_Call) Return(genericError *utils.GenericError) *MockAccountService_AddAllFeatures_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountService_AddAllFeatures_Call) RunAndReturn(run func(accountId uint64) *utils.GenericError) *MockAccountService_AddAllFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddFeature provides a mock function for the type MockAccountService
func (_mock *MockAccountService) AddFeature(accountId uint64, featureId uint64) *utils.GenericError {
	ret := _mock.Called(accountId, featureId)

	if len(ret) == 0 {
		panic("no return value specified for AddFeature")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId, featureId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountService_AddFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeature'
type MockAccountService_AddFeature_Call struct {
	*mock.Call
}

// AddFeature is a helper method to define mock.On call
//   - accountId uint64
//   - featureId uint64
func (_e *MockAccountService_Expecter) AddFeature(accountId interface{}, featureId interface{}) *MockAccountService_AddFeature_Call {
	return &MockAccountService_AddFeature_Call{Call: _e.mock.On("AddFeature", accountId, featureId)}
}

func (_c *MockAccountService_AddFeature_Call) Run(run func(accountId uint64, featureId uint64)) *MockAccountService_AddFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_AddFeature_Call) Return(genericError *utils.GenericError) *MockAccountService_AddFeature_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountService_AddFeature_Call) RunAndReturn(run func(accountId uint64, featureId uint64) *utils.GenericError) *MockAccountService_AddFeature_Call {
	_c.Call.Return(run)
	return _c
}

// AddTokens provides a mock function for the type MockAccountService
func (_mock *MockAccountService) AddTokens(accountId uint64, amount uint64) (uint64, *utils.GenericError) {
	ret := _mock.Called(accountId, amount)

	if len(ret) == 0 {
		panic("no return value specified for AddTokens")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (uint64, *utils.GenericError)); ok {
		return returnFunc(accountId, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) uint64); ok {
		r0 = returnFunc(accountId, amount)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountId, amount)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_AddTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTokens'
type MockAccountService_AddTokens_Call struct {
	*mock.Call
}

// AddTokens is a helper method to define mock.On call
//   - accountId uint64
//   - amount uint64
func (_e *MockAccountService_Expecter) AddTokens(accountId interface{}, amount interface{}) *MockAccountService_AddTokens_Call {
	return &MockAccountService_AddTokens_Call{Call: _e.mock.On("AddTokens", accountId, amount)}
}

func (_c *MockAccountService_AddTokens_Call) Run(run func(accountId uint64, amount uint64)) *MockAccountService_AddTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_AddTokens_Call) Return(v uint64, genericError *utils.GenericError) *MockAccountService_AddTokens_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockAccountService_AddTokens_Call) RunAndReturn(run func(accountId uint64, amount uint64) (uint64, *utils.GenericError)) *MockAccountService_AddTokens_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) CreateAccount(account *models.Account) (uint64, *utils.GenericError) {
	ret := _mock.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(*models.Account) (uint64, *utils.GenericError)); ok {
		return returnFunc(account)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Account) uint64); ok {
		r0 = returnFunc(account)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Account) *utils.GenericError); ok {
		r1 = returnFunc(account)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockAccountService_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - account *models.Account
func (_e *MockAccountService_Expecter) CreateAccount(account interface{}) *MockAccountService_CreateAccount_Call {
	return &MockAccountService_CreateAccount_Call{Call: _e.mock.On("CreateAccount", account)}
}

func (_c *MockAccountService_CreateAccount_Call) Run(run func(account *models.Account)) *MockAccountService_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Account
		if args[0] != nil {
			arg0 = args[0].(*models.Account)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_CreateAccount_Call) Return(v uint64, genericError *utils.GenericError) *MockAccountService_CreateAccount_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockAccountService_CreateAccount_Call) RunAndReturn(run func(account *models.Account) (uint64, *utils.GenericError)) *MockAccountService_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// DeductTokens provides a mock function for the type MockAccountService
func (_mock *MockAccountService) DeductTokens(accountId uint64, amount uint64) (bool, uint64, *utils.GenericError) {
	ret := _mock.Called(accountId, amount)

	if len(ret) == 0 {
		panic("no return value specified for DeductTokens")
	}

	var r0 bool
	var r1 uint64
	var r2 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (bool, uint64, *utils.GenericError)); ok {
		return returnFunc(accountId, amount)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) bool); ok {
		r0 = returnFunc(accountId, amount)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) uint64); ok {
		r1 = returnFunc(accountId, amount)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(uint64, uint64) *utils.GenericError); ok {
		r2 = returnFunc(accountId, amount)
	} else {
		if ret.Get(2) != nil {
			r2 = ret.Get(2).(*utils.GenericError)
		}
	}
	return r0, r1, r2
}

// MockAccountService_DeductTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeductTokens'
type MockAccountService_DeductTokens_Call struct {
	*mock.Call
}

// DeductTokens is a helper method to define mock.On call
//   - accountId uint64
//   - amount uint64
func (_e *MockAccountService_Expecter) DeductTokens(accountId interface{}, amount interface{}) *MockAccountService_DeductTokens_Call {
	return &MockAccountService_DeductTokens_Call{Call: _e.mock.On("DeductTokens", accountId, amount)}
}

func (_c *MockAccountService_DeductTokens_Call) Run(run func(accountId uint64, amount uint64)) *MockAccountService_DeductTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_DeductTokens_Call) Return(b bool, v uint64, genericError *utils.GenericError) *MockAccountService_DeductTokens_Call {
	_c.Call.Return(b, v, genericError)
	return _c
}

func (_c *MockAccountService_DeductTokens_Call) RunAndReturn(run func(accountId uint64, amount uint64) (bool, uint64, *utils.GenericError)) *MockAccountService_DeductTokens_Call {
	_c.Call.Return(run)
	return _c
}

// GetAIUsage provides a mock function for the type MockAccountService
func (_mock *MockAccountService) GetAIUsage(accountId uint64) (*models.AIUsage, *utils.GenericError) {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetAIUsage")
	}

	var r0 *models.AIUsage
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (*models.AIUsage, *utils.GenericError)); ok {
		return returnFunc(accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *models.AIUsage); ok {
		r0 = returnFunc(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AIUsage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_GetAIUsage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAIUsage'
type MockAccountService_GetAIUsage_Call struct {
	*mock.Call
}

// GetAIUsage is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountService_Expecter) GetAIUsage(accountId interface{}) *MockAccountService_GetAIUsage_Call {
	return &MockAccountService_GetAIUsage_Call{Call: _e.mock.On("GetAIUsage", accountId)}
}

func (_c *MockAccountService_GetAIUsage_Call) Run(run func(accountId uint64)) *MockAccountService_GetAIUsage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_GetAIUsage_Call) Return(aIUsage *models.AIUsage, genericError *utils.GenericError) *MockAccountService_GetAIUsage_Call {
	_c.Call.Return(aIUsage, genericError)
	return _c
}

func (_c *MockAccountService_GetAIUsage_Call) RunAndReturn(run func(accountId uint64) (*models.AIUsage, *utils.GenericError)) *MockAccountService_GetAIUsage_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) GetAccount(id uint64) (*models.Account, *utils.GenericError) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *models.Account
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (*models.Account, *utils.GenericError)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *models.Account); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockAccountService_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - id uint64
func (_e *MockAccountService_Expecter) GetAccount(id interface{}) *MockAccountService_GetAccount_Call {
	return &MockAccountService_GetAccount_Call{Call: _e.mock.On("GetAccount", id)}
}

func (_c *MockAccountService_GetAccount_Call) Run(run func(id uint64)) *MockAccountService_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_GetAccount_Call) Return(account *models.Account, genericError *utils.GenericError) *MockAccountService_GetAccount_Call {
	_c.Call.Return(account, genericError)
	return _c
}

func (_c *MockAccountService_GetAccount_Call) RunAndReturn(run func(id uint64) (*models.Account, *utils.GenericError)) *MockAccountService_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetExecutionCount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) GetExecutionCount(accountId uint64) (*models.AccountJobExecutionsCount, *utils.GenericError) {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetExecutionCount")
	}

	var r0 *models.AccountJobExecutionsCount
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (*models.AccountJobExecutionsCount, *utils.GenericError)); ok {
		return returnFunc(accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *models.AccountJobExecutionsCount); ok {
		r0 = returnFunc(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.AccountJobExecutionsCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_GetExecutionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExecutionCount'
type MockAccountService_GetExecutionCount_Call struct {
	*mock.Call
}

// GetExecutionCount is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountService_Expecter) GetExecutionCount(accountId interface{}) *MockAccountService_GetExecutionCount_Call {
	return &MockAccountService_GetExecutionCount_Call{Call: _e.mock.On("GetExecutionCount", accountId)}
}

func (_c *MockAccountService_GetExecutionCount_Call) Run(run func(accountId uint64)) *MockAccountService_GetExecutionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_GetExecutionCount_Call) Return(accountJobExecutionsCount *models.AccountJobExecutionsCount, genericError *utils.GenericError) *MockAccountService_GetExecutionCount_Call {
	_c.Call.Return(accountJobExecutionsCount, genericError)
	return _c
}

func (_c *MockAccountService_GetExecutionCount_Call) RunAndReturn(run func(accountId uint64) (*models.AccountJobExecutionsCount, *utils.GenericError)) *MockAccountService_GetExecutionCount_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeatures provides a mock function for the type MockAccountService
func (_mock *MockAccountService) GetFeatures(id uint64) (*[]models.AccountFeature, *utils.GenericError) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFeatures")
	}

	var r0 *[]models.AccountFeature
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (*[]models.AccountFeature, *utils.GenericError)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *[]models.AccountFeature); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.AccountFeature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_GetFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeatures'
type MockAccountService_GetFeatures_Call struct {
	*mock.Call
}

// GetFeatures is a helper method to define mock.On call
//   - id uint64
func (_e *MockAccountService_Expecter) GetFeatures(id interface{}) *MockAccountService_GetFeatures_Call {
	return &MockAccountService_GetFeatures_Call{Call: _e.mock.On("GetFeatures", id)}
}

func (_c *MockAccountService_GetFeatures_Call) Run(run func(id uint64)) *MockAccountService_GetFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_GetFeatures_Call) Return(accountFeatures *[]models.AccountFeature, genericError *utils.GenericError) *MockAccountService_GetFeatures_Call {
	_c.Call.Return(accountFeatures, genericError)
	return _c
}

func (_c *MockAccountService_GetFeatures_Call) RunAndReturn(run func(id uint64) (*[]models.AccountFeature, *utils.GenericError)) *MockAccountService_GetFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeaturesByAccountIds provides a mock function for the type MockAccountService
func (_mock *MockAccountService) GetFeaturesByAccountIds(accountIds []uint64) (map[uint64][]models.AccountFeature, *utils.GenericError) {
	ret := _mock.Called(accountIds)

	if len(ret) == 0 {
		panic("no return value specified for GetFeaturesByAccountIds")
	}

	var r0 map[uint64][]models.AccountFeature
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func([]uint64) (map[uint64][]models.AccountFeature, *utils.GenericError)); ok {
		return returnFunc(accountIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint64) map[uint64][]models.AccountFeature); ok {
		r0 = returnFunc(accountIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64][]models.AccountFeature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountIds)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_GetFeaturesByAccountIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeaturesByAccountIds'
type MockAccountService_GetFeaturesByAccountIds_Call struct {
	*mock.Call
}

// GetFeaturesByAccountIds is a helper method to define mock.On call
//   - accountIds []uint64
func (_e *MockAccountService_Expecter) GetFeaturesByAccountIds(accountIds interface{}) *MockAccountService_GetFeaturesByAccountIds_Call {
	return &MockAccountService_GetFeaturesByAccountIds_Call{Call: _e.mock.On("GetFeaturesByAccountIds", accountIds)}
}

func (_c *MockAccountService_GetFeaturesByAccountIds_Call) Run(run func(accountIds []uint64)) *MockAccountService_GetFeaturesByAccountIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		if args[0] != nil {
			arg0 = args[0].([]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_GetFeaturesByAccountIds_Call) Return(uint64ToAccountFeatures map[uint64][]models.AccountFeature, genericError *utils.GenericError) *MockAccountService_GetFeaturesByAccountIds_Call {
	_c.Call.Return(uint64ToAccountFeatures, genericError)
	return _c
}

func (_c *MockAccountService_GetFeaturesByAccountIds_Call) RunAndReturn(run func(accountIds []uint64) (map[uint64][]models.AccountFeature, *utils.GenericError)) *MockAccountService_GetFeaturesByAccountIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokens provides a mock function for the type MockAccountService
func (_mock *MockAccountService) GetTokens(accountId uint64) (uint64, *utils.GenericError) {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for GetTokens")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (uint64, *utils.GenericError)); ok {
		return returnFunc(accountId)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) uint64); ok {
		r0 = returnFunc(accountId)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_GetTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokens'
type MockAccountService_GetTokens_Call struct {
	*mock.Call
}

// GetTokens is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountService_Expecter) GetTokens(accountId interface{}) *MockAccountService_GetTokens_Call {
	return &MockAccountService_GetTokens_Call{Call: _e.mock.On("GetTokens", accountId)}
}

func (_c *MockAccountService_GetTokens_Call) Run(run func(accountId uint64)) *MockAccountService_GetTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_GetTokens_Call) Return(v uint64, genericError *utils.GenericError) *MockAccountService_GetTokens_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockAccountService_GetTokens_Call) RunAndReturn(run func(accountId uint64) (uint64, *utils.GenericError)) *MockAccountService_GetTokens_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseExecutionCount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) IncreaseExecutionCount(accountId uint64, count uint64) (uint64, *utils.GenericError) {
	ret := _mock.Called(accountId, count)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseExecutionCount")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) (uint64, *utils.GenericError)); ok {
		return returnFunc(accountId, count)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) uint64); ok {
		r0 = returnFunc(accountId, count)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(uint64, uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountId, count)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountService_IncreaseExecutionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseExecutionCount'
type MockAccountService_IncreaseExecutionCount_Call struct {
	*mock.Call
}

// IncreaseExecutionCount is a helper method to define mock.On call
//   - accountId uint64
//   - count uint64
func (_e *MockAccountService_Expecter) IncreaseExecutionCount(accountId interface{}, count interface{}) *MockAccountService_IncreaseExecutionCount_Call {
	return &MockAccountService_IncreaseExecutionCount_Call{Call: _e.mock.On("IncreaseExecutionCount", accountId, count)}
}

func (_c *MockAccountService_IncreaseExecutionCount_Call) Run(run func(accountId uint64, count uint64)) *MockAccountService_IncreaseExecutionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_IncreaseExecutionCount_Call) Return(v uint64, genericError *utils.GenericError) *MockAccountService_IncreaseExecutionCount_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockAccountService_IncreaseExecutionCount_Call) RunAndReturn(run func(accountId uint64, count uint64) (uint64, *utils.GenericError)) *MockAccountService_IncreaseExecutionCount_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllFeatures provides a mock function for the type MockAccountService
func (_mock *MockAccountService) RemoveAllFeatures(accountId uint64) *utils.GenericError {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllFeatures")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountService_RemoveAllFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllFeatures'
type MockAccountService_RemoveAllFeatures_Call struct {
	*mock.Call
}

// RemoveAllFeatures is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountService_Expecter) RemoveAllFeatures(accountId interface{}) *MockAccountService_RemoveAllFeatures_Call {
	return &MockAccountService_RemoveAllFeatures_Call{Call: _e.mock.On("RemoveAllFeatures", accountId)}
}

func (_c *MockAccountService_RemoveAllFeatures_Call) Run(run func(accountId uint64)) *MockAccountService_RemoveAllFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountService_RemoveAllFeatures_Call) Return(genericError *utils.GenericError) *MockAccountService_RemoveAllFeatures_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountService_RemoveAllFeatures_Call) RunAndReturn(run func(accountId uint64) *utils.GenericError) *MockAccountService_RemoveAllFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFeature provides a mock function for the type MockAccountService
func (_mock *MockAccountService) RemoveFeature(accountId uint64, featureId uint64) *utils.GenericError {
	ret := _mock.Called(accountId, featureId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFeature")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId, featureId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountService_RemoveFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFeature'
type MockAccountService_RemoveFeature_Call struct {
	*mock.Call
}

// RemoveFeature is a helper method to define mock.On call
//   - accountId uint64
//   - featureId uint64
func (_e *MockAccountService_Expecter) RemoveFeature(accountId interface{}, featureId interface{}) *MockAccountService_RemoveFeature_Call {
	return &MockAccountService_RemoveFeature_Call{Call: _e.mock.On("RemoveFeature", accountId, featureId)}
}

func (_c *MockAccountService_RemoveFeature_Call) Run(run func(accountId uint64, featureId uint64)) *MockAccountService_RemoveFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_RemoveFeature_Call) Return(genericError *utils.GenericError) *MockAccountService_RemoveFeature_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountService_RemoveFeature_Call) RunAndReturn(run func(accountId uint64, featureId uint64) *utils.GenericError) *MockAccountService_RemoveFeature_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAccount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) UpdateAccount(id uint64, name string) *utils.GenericError {
	ret := _mock.Called(id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAccount")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, string) *utils.GenericError); ok {
		r0 = returnFunc(id, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountService_UpdateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAccount'
type MockAccountService_UpdateAccount_Call struct {
	*mock.Call
}

// UpdateAccount is a helper method to define mock.On call
//   - id uint64
//   - name string
func (_e *MockAccountService_Expecter) UpdateAccount(id interface{}, name interface{}) *MockAccountService_UpdateAccount_Call {
	return &MockAccountService_UpdateAccount_Call{Call: _e.mock.On("UpdateAccount", id, name)}
}

func (_c *MockAccountService_UpdateAccount_Call) Run(run func(id uint64, name string)) *MockAccountService_UpdateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_UpdateAccount_Call) Return(genericError *utils.GenericError) *MockAccountService_UpdateAccount_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountService_UpdateAccount_Call) RunAndReturn(run func(id uint64, name string) *utils.GenericError) *MockAccountService_UpdateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateExecutionCount provides a mock function for the type MockAccountService
func (_mock *MockAccountService) UpdateExecutionCount(accountId uint64, count uint64) *utils.GenericError {
	ret := _mock.Called(accountId, count)

	if len(ret) == 0 {
		panic("no return value specified for UpdateExecutionCount")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountService_UpdateExecutionCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateExecutionCount'
type MockAccountService_UpdateExecutionCount_Call struct {
	*mock.Call
}

// UpdateExecutionCount is a helper method to define mock.On call
//   - accountId uint64
//   - count uint64
func (_e *MockAccountService_Expecter) UpdateExecutionCount(accountId interface{}, count interface{}) *MockAccountService_UpdateExecutionCount_Call {
	return &MockAccountService_UpdateExecutionCount_Call{Call: _e.mock.On("UpdateExecutionCount", accountId, count)}
}

func (_c *MockAccountService_UpdateExecutionCount_Call) Run(run func(accountId uint64, count uint64)) *MockAccountService_UpdateExecutionCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountService_UpdateExecutionCount_Call) Return(genericError *utils.GenericError) *MockAccountService_UpdateExecutionCount_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountService_UpdateExecutionCount_Call) RunAndReturn(run func(accountId uint64, count uint64) *utils.GenericError) *MockAccountService_UpdateExecutionCount_Call {
	_c.Call.Return(run)
	return _c
}
