// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"scheduler0/pkg/models"
	"scheduler0/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockAccountRepository creates a new instance of MockAccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepository {
	mock := &MockAccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAccountRepository is an autogenerated mock type for the AccountRepository type
type MockAccountRepository struct {
	mock.Mock
}

type MockAccountRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepository) EXPECT() *MockAccountRepository_Expecter {
	return &MockAccountRepository_Expecter{mock: &_m.Mock}
}

// AddAllFeatures provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) AddAllFeatures(accountId uint64) *utils.GenericError {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for AddAllFeatures")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountRepository_AddAllFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddAllFeatures'
type MockAccountRepository_AddAllFeatures_Call struct {
	*mock.Call
}

// AddAllFeatures is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountRepository_Expecter) AddAllFeatures(accountId interface{}) *MockAccountRepository_AddAllFeatures_Call {
	return &MockAccountRepository_AddAllFeatures_Call{Call: _e.mock.On("AddAllFeatures", accountId)}
}

func (_c *MockAccountRepository_AddAllFeatures_Call) Run(run func(accountId uint64)) *MockAccountRepository_AddAllFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_AddAllFeatures_Call) Return(genericError *utils.GenericError) *MockAccountRepository_AddAllFeatures_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountRepository_AddAllFeatures_Call) RunAndReturn(run func(accountId uint64) *utils.GenericError) *MockAccountRepository_AddAllFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// AddFeature provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) AddFeature(accountId uint64, featureId uint64) *utils.GenericError {
	ret := _mock.Called(accountId, featureId)

	if len(ret) == 0 {
		panic("no return value specified for AddFeature")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId, featureId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountRepository_AddFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFeature'
type MockAccountRepository_AddFeature_Call struct {
	*mock.Call
}

// AddFeature is a helper method to define mock.On call
//   - accountId uint64
//   - featureId uint64
func (_e *MockAccountRepository_Expecter) AddFeature(accountId interface{}, featureId interface{}) *MockAccountRepository_AddFeature_Call {
	return &MockAccountRepository_AddFeature_Call{Call: _e.mock.On("AddFeature", accountId, featureId)}
}

func (_c *MockAccountRepository_AddFeature_Call) Run(run func(accountId uint64, featureId uint64)) *MockAccountRepository_AddFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_AddFeature_Call) Return(genericError *utils.GenericError) *MockAccountRepository_AddFeature_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountRepository_AddFeature_Call) RunAndReturn(run func(accountId uint64, featureId uint64) *utils.GenericError) *MockAccountRepository_AddFeature_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAccount provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) CreateAccount(account *models.Account) (uint64, *utils.GenericError) {
	ret := _mock.Called(account)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccount")
	}

	var r0 uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(*models.Account) (uint64, *utils.GenericError)); ok {
		return returnFunc(account)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.Account) uint64); ok {
		r0 = returnFunc(account)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.Account) *utils.GenericError); ok {
		r1 = returnFunc(account)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountRepository_CreateAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccount'
type MockAccountRepository_CreateAccount_Call struct {
	*mock.Call
}

// CreateAccount is a helper method to define mock.On call
//   - account *models.Account
func (_e *MockAccountRepository_Expecter) CreateAccount(account interface{}) *MockAccountRepository_CreateAccount_Call {
	return &MockAccountRepository_CreateAccount_Call{Call: _e.mock.On("CreateAccount", account)}
}

func (_c *MockAccountRepository_CreateAccount_Call) Run(run func(account *models.Account)) *MockAccountRepository_CreateAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.Account
		if args[0] != nil {
			arg0 = args[0].(*models.Account)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_CreateAccount_Call) Return(v uint64, genericError *utils.GenericError) *MockAccountRepository_CreateAccount_Call {
	_c.Call.Return(v, genericError)
	return _c
}

func (_c *MockAccountRepository_CreateAccount_Call) RunAndReturn(run func(account *models.Account) (uint64, *utils.GenericError)) *MockAccountRepository_CreateAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccount provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetAccount(id uint64) (*models.Account, *utils.GenericError) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAccount")
	}

	var r0 *models.Account
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (*models.Account, *utils.GenericError)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *models.Account); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountRepository_GetAccount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccount'
type MockAccountRepository_GetAccount_Call struct {
	*mock.Call
}

// GetAccount is a helper method to define mock.On call
//   - id uint64
func (_e *MockAccountRepository_Expecter) GetAccount(id interface{}) *MockAccountRepository_GetAccount_Call {
	return &MockAccountRepository_GetAccount_Call{Call: _e.mock.On("GetAccount", id)}
}

func (_c *MockAccountRepository_GetAccount_Call) Run(run func(id uint64)) *MockAccountRepository_GetAccount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetAccount_Call) Return(account *models.Account, genericError *utils.GenericError) *MockAccountRepository_GetAccount_Call {
	_c.Call.Return(account, genericError)
	return _c
}

func (_c *MockAccountRepository_GetAccount_Call) RunAndReturn(run func(id uint64) (*models.Account, *utils.GenericError)) *MockAccountRepository_GetAccount_Call {
	_c.Call.Return(run)
	return _c
}

// GetAccounts provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetAccounts(accountIds []uint64) ([]models.Account, *utils.GenericError) {
	ret := _mock.Called(accountIds)

	if len(ret) == 0 {
		panic("no return value specified for GetAccounts")
	}

	var r0 []models.Account
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func([]uint64) ([]models.Account, *utils.GenericError)); ok {
		return returnFunc(accountIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint64) []models.Account); ok {
		r0 = returnFunc(accountIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.Account)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountIds)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountRepository_GetAccounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAccounts'
type MockAccountRepository_GetAccounts_Call struct {
	*mock.Call
}

// GetAccounts is a helper method to define mock.On call
//   - accountIds []uint64
func (_e *MockAccountRepository_Expecter) GetAccounts(accountIds interface{}) *MockAccountRepository_GetAccounts_Call {
	return &MockAccountRepository_GetAccounts_Call{Call: _e.mock.On("GetAccounts", accountIds)}
}

func (_c *MockAccountRepository_GetAccounts_Call) Run(run func(accountIds []uint64)) *MockAccountRepository_GetAccounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		if args[0] != nil {
			arg0 = args[0].([]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetAccounts_Call) Return(accounts []models.Account, genericError *utils.GenericError) *MockAccountRepository_GetAccounts_Call {
	_c.Call.Return(accounts, genericError)
	return _c
}

func (_c *MockAccountRepository_GetAccounts_Call) RunAndReturn(run func(accountIds []uint64) ([]models.Account, *utils.GenericError)) *MockAccountRepository_GetAccounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAccountIds provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetAllAccountIds() ([]uint64, *utils.GenericError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAccountIds")
	}

	var r0 []uint64
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func() ([]uint64, *utils.GenericError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []uint64); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint64)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *utils.GenericError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountRepository_GetAllAccountIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAccountIds'
type MockAccountRepository_GetAllAccountIds_Call struct {
	*mock.Call
}

// GetAllAccountIds is a helper method to define mock.On call
func (_e *MockAccountRepository_Expecter) GetAllAccountIds() *MockAccountRepository_GetAllAccountIds_Call {
	return &MockAccountRepository_GetAllAccountIds_Call{Call: _e.mock.On("GetAllAccountIds")}
}

func (_c *MockAccountRepository_GetAllAccountIds_Call) Run(run func()) *MockAccountRepository_GetAllAccountIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAccountRepository_GetAllAccountIds_Call) Return(uint64s []uint64, genericError *utils.GenericError) *MockAccountRepository_GetAllAccountIds_Call {
	_c.Call.Return(uint64s, genericError)
	return _c
}

func (_c *MockAccountRepository_GetAllAccountIds_Call) RunAndReturn(run func() ([]uint64, *utils.GenericError)) *MockAccountRepository_GetAllAccountIds_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeatures provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetFeatures(id uint64) (*[]models.AccountFeature, *utils.GenericError) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFeatures")
	}

	var r0 *[]models.AccountFeature
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (*[]models.AccountFeature, *utils.GenericError)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *[]models.AccountFeature); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.AccountFeature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountRepository_GetFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeatures'
type MockAccountRepository_GetFeatures_Call struct {
	*mock.Call
}

// GetFeatures is a helper method to define mock.On call
//   - id uint64
func (_e *MockAccountRepository_Expecter) GetFeatures(id interface{}) *MockAccountRepository_GetFeatures_Call {
	return &MockAccountRepository_GetFeatures_Call{Call: _e.mock.On("GetFeatures", id)}
}

func (_c *MockAccountRepository_GetFeatures_Call) Run(run func(id uint64)) *MockAccountRepository_GetFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetFeatures_Call) Return(accountFeatures *[]models.AccountFeature, genericError *utils.GenericError) *MockAccountRepository_GetFeatures_Call {
	_c.Call.Return(accountFeatures, genericError)
	return _c
}

func (_c *MockAccountRepository_GetFeatures_Call) RunAndReturn(run func(id uint64) (*[]models.AccountFeature, *utils.GenericError)) *MockAccountRepository_GetFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeaturesByAccountIds provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) GetFeaturesByAccountIds(accountIds []uint64) (map[uint64][]models.AccountFeature, *utils.GenericError) {
	ret := _mock.Called(accountIds)

	if len(ret) == 0 {
		panic("no return value specified for GetFeaturesByAccountIds")
	}

	var r0 map[uint64][]models.AccountFeature
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func([]uint64) (map[uint64][]models.AccountFeature, *utils.GenericError)); ok {
		return returnFunc(accountIds)
	}
	if returnFunc, ok := ret.Get(0).(func([]uint64) map[uint64][]models.AccountFeature); ok {
		r0 = returnFunc(accountIds)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uint64][]models.AccountFeature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]uint64) *utils.GenericError); ok {
		r1 = returnFunc(accountIds)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockAccountRepository_GetFeaturesByAccountIds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeaturesByAccountIds'
type MockAccountRepository_GetFeaturesByAccountIds_Call struct {
	*mock.Call
}

// GetFeaturesByAccountIds is a helper method to define mock.On call
//   - accountIds []uint64
func (_e *MockAccountRepository_Expecter) GetFeaturesByAccountIds(accountIds interface{}) *MockAccountRepository_GetFeaturesByAccountIds_Call {
	return &MockAccountRepository_GetFeaturesByAccountIds_Call{Call: _e.mock.On("GetFeaturesByAccountIds", accountIds)}
}

func (_c *MockAccountRepository_GetFeaturesByAccountIds_Call) Run(run func(accountIds []uint64)) *MockAccountRepository_GetFeaturesByAccountIds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []uint64
		if args[0] != nil {
			arg0 = args[0].([]uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_GetFeaturesByAccountIds_Call) Return(uint64ToAccountFeatures map[uint64][]models.AccountFeature, genericError *utils.GenericError) *MockAccountRepository_GetFeaturesByAccountIds_Call {
	_c.Call.Return(uint64ToAccountFeatures, genericError)
	return _c
}

func (_c *MockAccountRepository_GetFeaturesByAccountIds_Call) RunAndReturn(run func(accountIds []uint64) (map[uint64][]models.AccountFeature, *utils.GenericError)) *MockAccountRepository_GetFeaturesByAccountIds_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveAllFeatures provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) RemoveAllFeatures(accountId uint64) *utils.GenericError {
	ret := _mock.Called(accountId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveAllFeatures")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountRepository_RemoveAllFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveAllFeatures'
type MockAccountRepository_RemoveAllFeatures_Call struct {
	*mock.Call
}

// RemoveAllFeatures is a helper method to define mock.On call
//   - accountId uint64
func (_e *MockAccountRepository_Expecter) RemoveAllFeatures(accountId interface{}) *MockAccountRepository_RemoveAllFeatures_Call {
	return &MockAccountRepository_RemoveAllFeatures_Call{Call: _e.mock.On("RemoveAllFeatures", accountId)}
}

func (_c *MockAccountRepository_RemoveAllFeatures_Call) Run(run func(accountId uint64)) *MockAccountRepository_RemoveAllFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAccountRepository_RemoveAllFeatures_Call) Return(genericError *utils.GenericError) *MockAccountRepository_RemoveAllFeatures_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountRepository_RemoveAllFeatures_Call) RunAndReturn(run func(accountId uint64) *utils.GenericError) *MockAccountRepository_RemoveAllFeatures_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFeature provides a mock function for the type MockAccountRepository
func (_mock *MockAccountRepository) RemoveFeature(accountId uint64, featureId uint64) *utils.GenericError {
	ret := _mock.Called(accountId, featureId)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFeature")
	}

	var r0 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64, uint64) *utils.GenericError); ok {
		r0 = returnFunc(accountId, featureId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*utils.GenericError)
		}
	}
	return r0
}

// MockAccountRepository_RemoveFeature_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFeature'
type MockAccountRepository_RemoveFeature_Call struct {
	*mock.Call
}

// RemoveFeature is a helper method to define mock.On call
//   - accountId uint64
//   - featureId uint64
func (_e *MockAccountRepository_Expecter) RemoveFeature(accountId interface{}, featureId interface{}) *MockAccountRepository_RemoveFeature_Call {
	return &MockAccountRepository_RemoveFeature_Call{Call: _e.mock.On("RemoveFeature", accountId, featureId)}
}

func (_c *MockAccountRepository_RemoveFeature_Call) Run(run func(accountId uint64, featureId uint64)) *MockAccountRepository_RemoveFeature_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAccountRepository_RemoveFeature_Call) Return(genericError *utils.GenericError) *MockAccountRepository_RemoveFeature_Call {
	_c.Call.Return(genericError)
	return _c
}

func (_c *MockAccountRepository_RemoveFeature_Call) RunAndReturn(run func(accountId uint64, featureId uint64) *utils.GenericError) *MockAccountRepository_RemoveFeature_Call {
	_c.Call.Return(run)
	return _c
}
