// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"scheduler0/pkg/models"
	"scheduler0/pkg/utils"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFeatureRepository creates a new instance of MockFeatureRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFeatureRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFeatureRepository {
	mock := &MockFeatureRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFeatureRepository is an autogenerated mock type for the FeatureRepository type
type MockFeatureRepository struct {
	mock.Mock
}

type MockFeatureRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFeatureRepository) EXPECT() *MockFeatureRepository_Expecter {
	return &MockFeatureRepository_Expecter{mock: &_m.Mock}
}

// GetFeatureByID provides a mock function for the type MockFeatureRepository
func (_mock *MockFeatureRepository) GetFeatureByID(id uint64) (*models.Feature, *utils.GenericError) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetFeatureByID")
	}

	var r0 *models.Feature
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func(uint64) (*models.Feature, *utils.GenericError)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(uint64) *models.Feature); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Feature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(uint64) *utils.GenericError); ok {
		r1 = returnFunc(id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockFeatureRepository_GetFeatureByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeatureByID'
type MockFeatureRepository_GetFeatureByID_Call struct {
	*mock.Call
}

// GetFeatureByID is a helper method to define mock.On call
//   - id uint64
func (_e *MockFeatureRepository_Expecter) GetFeatureByID(id interface{}) *MockFeatureRepository_GetFeatureByID_Call {
	return &MockFeatureRepository_GetFeatureByID_Call{Call: _e.mock.On("GetFeatureByID", id)}
}

func (_c *MockFeatureRepository_GetFeatureByID_Call) Run(run func(id uint64)) *MockFeatureRepository_GetFeatureByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uint64
		if args[0] != nil {
			arg0 = args[0].(uint64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFeatureRepository_GetFeatureByID_Call) Return(feature *models.Feature, genericError *utils.GenericError) *MockFeatureRepository_GetFeatureByID_Call {
	_c.Call.Return(feature, genericError)
	return _c
}

func (_c *MockFeatureRepository_GetFeatureByID_Call) RunAndReturn(run func(id uint64) (*models.Feature, *utils.GenericError)) *MockFeatureRepository_GetFeatureByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetFeatures provides a mock function for the type MockFeatureRepository
func (_mock *MockFeatureRepository) GetFeatures() (*[]models.Feature, *utils.GenericError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFeatures")
	}

	var r0 *[]models.Feature
	var r1 *utils.GenericError
	if returnFunc, ok := ret.Get(0).(func() (*[]models.Feature, *utils.GenericError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *[]models.Feature); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]models.Feature)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *utils.GenericError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*utils.GenericError)
		}
	}
	return r0, r1
}

// MockFeatureRepository_GetFeatures_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFeatures'
type MockFeatureRepository_GetFeatures_Call struct {
	*mock.Call
}

// GetFeatures is a helper method to define mock.On call
func (_e *MockFeatureRepository_Expecter) GetFeatures() *MockFeatureRepository_GetFeatures_Call {
	return &MockFeatureRepository_GetFeatures_Call{Call: _e.mock.On("GetFeatures")}
}

func (_c *MockFeatureRepository_GetFeatures_Call) Run(run func()) *MockFeatureRepository_GetFeatures_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFeatureRepository_GetFeatures_Call) Return(features *[]models.Feature, genericError *utils.GenericError) *MockFeatureRepository_GetFeatures_Call {
	_c.Call.Return(features, genericError)
	return _c
}

func (_c *MockFeatureRepository_GetFeatures_Call) RunAndReturn(run func() (*[]models.Feature, *utils.GenericError)) *MockFeatureRepository_GetFeatures_Call {
	_c.Call.Return(run)
	return _c
}
