// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	db "scheduler0/pkg/db"
	models "scheduler0/pkg/models"

	mock "github.com/stretchr/testify/mock"
)

// SharedRepo is an autogenerated mock type for the SharedRepo type
type SharedRepo struct {
	mock.Mock
}

// DeleteAsyncTasksLogs provides a mock function with given fields: _a0, committed, asyncTasks
func (_m *SharedRepo) DeleteAsyncTasksLogs(_a0 db.DataStore, committed bool, asyncTasks []models.AsyncTask) error {
	ret := _m.Called(_a0, committed, asyncTasks)

	var r0 error
	if rf, ok := ret.Get(0).(func(db.DataStore, bool, []models.AsyncTask) error); ok {
		r0 = rf(_a0, committed, asyncTasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteExecutionLogs provides a mock function with given fields: _a0, committed, jobExecutionLogs
func (_m *SharedRepo) DeleteExecutionLogs(_a0 db.DataStore, committed bool, jobExecutionLogs []models.JobExecutionLog) error {
	ret := _m.Called(_a0, committed, jobExecutionLogs)

	var r0 error
	if rf, ok := ret.Get(0).(func(db.DataStore, bool, []models.JobExecutionLog) error); ok {
		r0 = rf(_a0, committed, jobExecutionLogs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetExecutionLogs provides a mock function with given fields: _a0, committed
func (_m *SharedRepo) GetExecutionLogs(_a0 db.DataStore, committed bool) ([]models.JobExecutionLog, error) {
	ret := _m.Called(_a0, committed)

	var r0 []models.JobExecutionLog
	var r1 error
	if rf, ok := ret.Get(0).(func(db.DataStore, bool) ([]models.JobExecutionLog, error)); ok {
		return rf(_a0, committed)
	}
	if rf, ok := ret.Get(0).(func(db.DataStore, bool) []models.JobExecutionLog); ok {
		r0 = rf(_a0, committed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]models.JobExecutionLog)
		}
	}

	if rf, ok := ret.Get(1).(func(db.DataStore, bool) error); ok {
		r1 = rf(_a0, committed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertAsyncTasksLogs provides a mock function with given fields: _a0, committed, asyncTasks
func (_m *SharedRepo) InsertAsyncTasksLogs(_a0 db.DataStore, committed bool, asyncTasks []models.AsyncTask) error {
	ret := _m.Called(_a0, committed, asyncTasks)

	var r0 error
	if rf, ok := ret.Get(0).(func(db.DataStore, bool, []models.AsyncTask) error); ok {
		r0 = rf(_a0, committed, asyncTasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// InsertExecutionLogs provides a mock function with given fields: _a0, committed, jobExecutionLogs
func (_m *SharedRepo) InsertExecutionLogs(_a0 db.DataStore, committed bool, jobExecutionLogs []models.JobExecutionLog) error {
	ret := _m.Called(_a0, committed, jobExecutionLogs)

	var r0 error
	if rf, ok := ret.Get(0).(func(db.DataStore, bool, []models.JobExecutionLog) error); ok {
		r0 = rf(_a0, committed, jobExecutionLogs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewSharedRepo interface {
	mock.TestingT
	Cleanup(func())
}

// NewSharedRepo creates a new instance of SharedRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSharedRepo(t mockConstructorTestingTNewSharedRepo) *SharedRepo {
	mock := &SharedRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
