// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package queue

import (
	"context"
	"scheduler0-private/pkg/config"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQuotaAllocationSender creates a new instance of MockQuotaAllocationSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuotaAllocationSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuotaAllocationSender {
	mock := &MockQuotaAllocationSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQuotaAllocationSender is an autogenerated mock type for the QuotaAllocationSender type
type MockQuotaAllocationSender struct {
	mock.Mock
}

type MockQuotaAllocationSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuotaAllocationSender) EXPECT() *MockQuotaAllocationSender_Expecter {
	return &MockQuotaAllocationSender_Expecter{mock: &_m.Mock}
}

// SendQuotaAllocation provides a mock function for the type MockQuotaAllocationSender
func (_mock *MockQuotaAllocationSender) SendQuotaAllocation(ctx context.Context, peer config.RaftNode, accountAllocations map[uint64]uint64) error {
	ret := _mock.Called(ctx, peer, accountAllocations)

	if len(ret) == 0 {
		panic("no return value specified for SendQuotaAllocation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, config.RaftNode, map[uint64]uint64) error); ok {
		r0 = returnFunc(ctx, peer, accountAllocations)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQuotaAllocationSender_SendQuotaAllocation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendQuotaAllocation'
type MockQuotaAllocationSender_SendQuotaAllocation_Call struct {
	*mock.Call
}

// SendQuotaAllocation is a helper method to define mock.On call
//   - ctx context.Context
//   - peer config.RaftNode
//   - accountAllocations map[uint64]uint64
func (_e *MockQuotaAllocationSender_Expecter) SendQuotaAllocation(ctx interface{}, peer interface{}, accountAllocations interface{}) *MockQuotaAllocationSender_SendQuotaAllocation_Call {
	return &MockQuotaAllocationSender_SendQuotaAllocation_Call{Call: _e.mock.On("SendQuotaAllocation", ctx, peer, accountAllocations)}
}

func (_c *MockQuotaAllocationSender_SendQuotaAllocation_Call) Run(run func(ctx context.Context, peer config.RaftNode, accountAllocations map[uint64]uint64)) *MockQuotaAllocationSender_SendQuotaAllocation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 config.RaftNode
		if args[1] != nil {
			arg1 = args[1].(config.RaftNode)
		}
		var arg2 map[uint64]uint64
		if args[2] != nil {
			arg2 = args[2].(map[uint64]uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQuotaAllocationSender_SendQuotaAllocation_Call) Return(err error) *MockQuotaAllocationSender_SendQuotaAllocation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQuotaAllocationSender_SendQuotaAllocation_Call) RunAndReturn(run func(ctx context.Context, peer config.RaftNode, accountAllocations map[uint64]uint64) error) *MockQuotaAllocationSender_SendQuotaAllocation_Call {
	_c.Call.Return(run)
	return _c
}
