name: Deploy Scheduler0-Private to Amazon ECS (production)

on:
  release:
    types: [published]

concurrency:
  group: scheduler0-private-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    uses: ./.github/workflows/_deploy.yml
    with:
      environment: production
      env_name: production
      log_level: "INFO"
      max_workers: "250"
      platform_webhook_url: https://app.scheduler0.com/scheduler0_callback
    secrets: inherit
